### PR TITLE
METRON-1008: Updating travis to use trusty

### PR DESCRIPTION
**Pull request by jjmeyer0**
….npm to cache.

Added some more cacheing from 1004 ticket.

Revert some changes.

Reverted environment and put maven opts in the correct spot.

Trying multiple vm build.

Revert back to two threads on maven install.

## Contributor Comments
I made travis use trusty. On top of this the following were added before 1004 was made, but I thought some things were worth keeping:

* Call to verify license is made right away to get quicker failures. 
* Cache $HOME/.npm; After bringing in METRON-1004 it looks like this may not be needed anymore?
* Set MAVEN_OPTS to set `-Xmx2g` out of curiosity
* Out of curiosity, multiple environments were added to see if build times would dramatically increase. I know this may be undesirable, but I thought I'd leave it in to discuss some. I'm leaning towards reverting this back as it only seems to get it down to ~23 minutes. Any thoughts?

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [ ] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root incubating-metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by JonZeolla** [comment]
One brief note - I spoke to a friend on the travis infrastructure team and she recommended that if our build takes > 5m we should run on the VM (sudo: true).

**Comment by justinleet** [comment]
@JonZeolla Completely counterintuitively, `sudo: required` is the counterpart of `sudo: false`.  So this already got taken care of as part of METRON-1004.  See: https://docs.travis-ci.com/user/trusty-ci-environment.

If you check out the Travis build (https://travis-ci.org/apache/metron/jobs/250503026, for example), it says it's running the Trusty as expected.

**Comment by justinleet** [comment]
I'd be inclined towards avoiding splitting the build if we were only getting a couple minutes out of it.  I'm a little worried about being able to get three slots on the occasionally stretched Apache setup.  Integration tests and building are the long poles in the tent, so splitting out the other tests doesn't really save us much time here, unfortunately.

**Comment by JonZeolla** [comment]
I was addressing "Testing sudo as false." In the body of the message above.

**Comment by jjmeyer0** [comment]
@JonZeolla that was a squashed commit that was probably a typo. I'll remove it.

**Comment by ottobackwards** [comment]
I'm going to be honest.  Now that we have the builds kind of working again, I'm a little hesitant to change them for anything but an absolute certainty of a return, that we completely understand.

I think the travis build strategy should be a longer living branch maybe.

**Comment by justinleet** [comment]
@JonZeolla ahh, I thought you were just making a note, so everyone knew that recommendation.  Sorry about that.

**Comment by JonZeolla** [comment]
Obviously I was not very clear about what I was commenting on either so sorry about that.

**Comment by jjmeyer0** [comment]
Unfortunately I will have to open a new PR. I squashed my commits when this PR was closed. Github doesn't allow to reopen PRs when force pushes occur when the PR is closed.  @justinleet and @ottobackwards I'll address your comments on the new PR.

My apologies, I was not aware of this.

**Pull request closed without merging**
