### PR TITLE
METRON-2250 : Missing services in HDP 3.1 metron mpack and installer stuck

### PR DESCRIPTION
**Pull request by MohanDV**
## Contributor Comments
This change is added as work around for https://issues.apache.org/jira/browse/AMBARI-25375
This only affects the recommendations in Ambari - users can still modify the hosts for the components as they see fit.

### Testing

In order reproduce the error being fixed in this bug, pull the latest feature branch code without this fix and follow the following test plan that also verifies the fix.

### Test Plan

In order reproduce the error being fixed in this bug, pull the latest feature branch code without this fix and follow the following test plan that also verifies the fix.

#### Testing in fulldev

1. Spin up full dev with Centos 7
    ```
    cd ./metron-deployment/development/centos7/
    vagrant up
    ```

#### Uninstall Metron service

1. Once the install completes, open Ambari http://node1:8080 and stop all Metron services under the Metron service option. We need to do this in order to uninstall.
2. Click Actions and choose delete service. Confirm.
3. The Metron Ambari service should be deleted

#### Re-install Metron service

1. Click the ellipses next to "Services" in Ambari and choose "Add Service"
2. Select Metron in the list of services to install. Accept the additional components by clicking "Ok" for each.
3. The "Assign Masters" page is where the bug previously existed. The "Next" option was greyed out due to the hostname errors. At this point, you can accept the defaults (node1 for full dev) and click "Next."
4. You can finish the installation if you like, but at this point the bug fix has been validated.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [X] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

- [ ] Have you ensured that any documentation diagrams have been updated, along with their source files, using [draw.io](https://www.draw.io/)? See [Metron Development Guidelines](https://cwiki.apache.org/confluence/display/METRON/Development+Guidelines) for instructions.

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by nickwallen** [comment]
Thanks @MohanDV !  This is working for me.

I do have one concern. Rather than relying on the `METRON_ENRICHMENT_MASTER` component to be assigned (which might not always be the case) just look for a host that has any Metron component. If none exist, then default to the first known host.

I opened a PR against your branch with this suggestion.

**Comment by MohanDV** [comment]
Thanks @nickwallen !! I merged your PR changes and verified it on full dev also on 5 node cluster. This is working for me with no issues .

**Comment by nickwallen** [comment]
+1 Thanks @MohanDV.  Great job finding a work around to this issue.

**Comment by nickwallen** [comment]
This has been merged into the feature branch.

**Pull request closed without merging**
