### PR TITLE
METRON-877 Extract core implementation and UDF support, create metron-stellar module

### PR DESCRIPTION
**Pull request by mattf-horton**
## Contributor Comments
The design document has been available for some time at https://docs.google.com/document/d/1EP7Jt4ePHe2A-_oboLl2QbN1muh7uKeET_kbpIgjcJM/edit#
I have now added a new section, starting on p. 7, titled "Retrospective: Changes made for Parts 1 & 2" that details the specific changes actually done in this PR to extract Stellar.

## Pull Request Checklist
In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
The intent of these changes is to achieve an architecture change WITHOUT any functional change.  The continued working of all unit tests, integration tests and real-world applications should result.  In addition, it generates (in metron-stellar/stellar-common/target) a stellar-common uber-jar (including all dependencies), which among other things can run the Stellar shell as a stand-alone Java application (although missing those Stellar functions that remain as part of Metron):
```
java -cp target/stellar-common-0.4.0-uber.jar \
    org.apache.metron.stellar.common.shell.StellarShell
```
Note that this PR does not yet have RPM generation (Step 6).  Thus, the Stellar jar will need to be manually added to the lib/ directory of test deployments.

- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root incubating-metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [IN PROCESS] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book?

### CODE REVIEW

**Comment by cestella** [comment]
Ok, for testing this, I'd suggest we go through #468 's test plan.  That touches every place we use Stellar atm, I think.

**Comment by mattf-horton** [comment]
>  #468 's test plan

Sounds good.  I'll start working through it myself.  Thanks for the suggestion.

**Comment by mattf-horton** [comment]
The Metron RPM build is broken with this patch, which interferes with testing.  Will have it fixed shortly. --Matt

**Comment by ottobackwards** [comment]
Don't forget - if you add an rpm, add the rpm to the ambari repo xml config

**Comment by mattf-horton** [comment]
Metron RPMs are back to working.  At this time, the stellar-common jar and its dependencies are being built into the metron-common uber-jar, and the metron-common RPM during Metron RPM generation.  This keeps Metron RPMs working until separate Stellar RPMs are generated in the future (Step 6).

**Comment by mattf-horton** [comment]
Due to large number of conflicting files in the last few commits on master, I will now rebase the PR.

**Pull request closed without merging**
