### PR TITLE
[METRON-1214] rpm build fails due to npm absence in Dockerfile

### PR DESCRIPTION
**Pull request by DimDroll**
Added npm to line 28 in Dockerfile

## Contributor Comments
[Please place any comments here.  A description of the problem/enhancement, how to reproduce the issue, your testing methodology, etc.]

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by simonellistonball** [comment]
Do we need to ensure we're picking this from the right repos? We should probably use the nodesource rpm repo rather than relying on the centos build, which is a very very old version, and could cause issues. Adding a the repo file in might be a good call.

**Comment by ottobackwards** [comment]
How would you reproduce this?  I have not been seeing failures.

**Comment by DimDroll** [comment]
@ottobackwards , true, it does not fail the rpm build as it ends with:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.284 s
[INFO] Finished at: 2017-10-11T08:52:01-04:00
[INFO] Final Memory: 23M/299M
[INFO] ------------------------------------------------------------------------

```
However there are no RPMs in respective folders and when I scroll up I can see:
```
/var/tmp/rpm-tmp.qHTcZj: line 58: npm: command not found
error: Bad exit status from /var/tmp/rpm-tmp.qHTcZj (%install)
    Macro %_prerelease has empty body
    Macro %_prerelease has empty body
    Bad exit status from /var/tmp/rpm-tmp.qHTcZj (%install)

RPM build errors:
```
I replicate it using:
1. Clone repo.
2. cd metron
3. mvn clean package -DskipTests -T 2C -P HDP-2.5.0.0,mpack
4. cd metron-deployment/packaging/docker/rpm-docker
5. mvn clean install -DskipTests -PHDP-2.5.0.0
If finishes build with success as shown above, but with the error shown above. Attached full log
[rpm_build_failure.txt](https://github.com/apache/metron/files/1376787/rpm_build_failure.txt)

**Comment by ottobackwards** [comment]
I just did your steps with a fresh branch from apache/master.  And although I get rpm lint errors about scripts without shebangs for all the node js scripts, I **do** get RPMs built.

[build.log](https://github.com/apache/metron/files/1376934/build.log)

**Comment by ottobackwards** [comment]
Building your PR branch, with the same commands, I see the same results basically.  Can anyone else reproduce this?

**Comment by nickwallen** [comment]
I am not able to replicate the problem, nor do I understand why this would be needed.  Node and NPM already get installed directly below where the changes are in this PR.

**Comment by DimDroll** [comment]
@nickwallen , I do agree, wonder why it fails though, I will login into container to check out what happens with the command curl and yum install nodejs command.

**Comment by ottobackwards** [comment]
Can you run platform_info and attach?

**Comment by ottobackwards** [comment]
@DimDroll any reproduction?  Is this still happening for you?

**Comment by ottobackwards** [comment]
@DimDroll any update?  Or can you close this?

**Comment by nickwallen** [comment]
@DimDroll  Please close this PR unless you believe it is still needed.  This PR will be closed per the [Metron Development Guidelines](https://cwiki.apache.org/confluence/display/METRON/Development+Guidelines) on Inactive PRs, unless you provide some reasoning as to why it is stil needed. Thanks!

**Comment by DimDroll** [comment]
It's been a while, sorry for ignorance. I am not able to replicate it now.

I appreciate your follow up on this.
It can be rejected and closed.

**Pull request closed without merging**
