### PR TITLE
METRON-2304: Update node and npm version to LTS releases

### PR DESCRIPTION
**Pull request by sardell**
## Contributor Comments
Link to ASF ticket here: https://issues.apache.org/jira/browse/METRON-2304

We are currently using node 9.11.1 and npm 6.2.0 in the project (this is specified in both the Alerts UI and Management UI pom.xml files). This version of node is no longer supported. [Per Node.js' documents](https://nodejs.org/en/about/releases/), "Production applications should only use Active LTS or Maintenance LTS releases." 

In this PR, I updated the project to use the current active LTS release (10.17.0). I also updated the npm version to the latest minor/patch release (6.11.3).

In addition, I added an .nvmrc file to the Management UI so that local developers using nvm will be able to use the same version as our production build.

## Testing
There shouldn't be a noticeable difference since node v10 is just the LTS release of v9. If you run `mvn install -pl ':metron-config'` and `mvn install -pl ':metron-alerts'`, you will notice the versions of node and npm mentioned above are installed. The tests suites for both UIs will also be ran and should pass. To visually test for regressions, spin up full dev and open both the Alerts and Management UI. You should see no differences.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- N/A ~[ ] Have you written or updated unit tests and or integration tests to verify your changes?~
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- N/A ~[ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:~

  ```
  cd site-book
  mvn site
  ```

- N/A ~[ ] Have you ensured that any documentation diagrams have been updated, along with their source files, using [draw.io](https://www.draw.io/)? See [Metron Development Guidelines](https://cwiki.apache.org/confluence/display/METRON/Development+Guidelines) for instructions.~

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by nickwallen** [comment]
Hi @sardell - On the [container that we use to build the RPMs](https://github.com/apache/metron/blob/a1e25a4bf618e544b2062bf7f7f25bec0029956a/metron-deployment/packaging/docker/rpm-docker/Dockerfile#L42-L46), we currently install from `https://rpm.nodesource.com/setup_6.x` which doesn't seem right.  I assume this also needs updated. Should this be changed to `https://rpm.nodesource.com/setup_10.x`?

**Comment by sardell** [comment]
@nickwallen You're correct, that doesn't look right. It looks like we'll have to update there as well, and you're correct about the version it needs to be bumped to. Thanks for pointing this out. I can update this line as part of this PR. Is building full dev with CentOS6 the best way to test this? I'm assuming I should do the same with CentOS7.

**Comment by nickwallen** [comment]
@sardell Yes, you are right.  Just spinning up the dev environments is the way to go.  Just testing centos6 is sufficient.  

We do not need to test centos7 here IMO.  In the HDP-3.1 upgrade feature branch, the container we build the RPMs on has changed to be based on centos7 versus centos6.  So we will need to validate this change when merging on the feature branch.  I can take care of this when merging master into the feature branch.

**Comment by sardell** [comment]
@nickwallen I made the change as promised above, but the build for centos6 fails for me. I tried troubleshooting locally, but I'm clueless why I'm running into an issue here. The error is pretty cryptic to me:

```
"[INFO] metron-rpm ......................................... FAILURE [03:43 min]", "[INFO] ------------------------------------------------------------------------", "[INFO] BUILD FAILURE", "[INFO] ------------------------------------------------------------------------", "[INFO] Total time: 03:45 min (Wall Clock)", "[INFO] Finished at: 2019-11-06T16:01:01-06:00", "[INFO] Final Memory: 14M/245M", "[INFO] ------------------------------------------------------------------------", "[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (rpm-build) on project metron-rpm: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]", "[ERROR] ", "[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.", "[ERROR] Re-run Maven using the -X switch to enable full debug logging.", "[ERROR] ", "[ERROR] For more information about the errors and possible solutions, please read the following articles:", "[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException", "[ERROR] ", "[ERROR] After correcting the problems, you can resume the build with the command", "[ERROR]   mvn <goals> -rf :metron-rpm"]}
```

I tested the curl script and it seems to work fine. Any chance I could get you to give it a go locally and see if you can make any sense of it?

**Comment by nickwallen** [comment]
Sure, I will take a look and see.

**Comment by nickwallen** [comment]
It is failing when building the RPMs.  It is really difficult to discern error messages via the Ansible output, so what I usually do is figure out where it is failing in the build process, then just run that command myself on the command line.

When building the RPMS, we get this error output.
```
$ cd metron-deployment/
$ mvn clean package -Pbuild-rpms
...
RPM build errors:
error: Installed (but unpackaged) file(s) found:
   /usr/metron/0.7.2/web/expressjs/package-lock.json
    Macro %_prerelease has empty body
    Macro %_prerelease has empty body
    Installed (but unpackaged) file(s) found:
   /usr/metron/0.7.2/web/expressjs/package-lock.json
RPM build errors encountered
```

I see there is a `package-lock.json` that is present in the location where the RPMs are being packaged.
```
$ find ./ -name package-lock.json
.//packaging/docker/rpm-docker/BUILDROOT/metron-0.7.2-root/usr/metron/0.7.2/web/expressjs/package-lock.json
```

But I do not see a `package-lock.json` defined in the `metron.spec` file.  Am I correct in assuming that we should NOT be including this file in the RPMs?

**Comment by sardell** [comment]
@nickwallen Thanks for your help and the hot tip about running the failing part of the build to get better/more readable output.

Something did change in the Node/NPM version upgrade. That `package-lock.json` file was introduced in NPM v5. Before my changes, the rpm and deb files in the project were using Node 6.x, which is bundled with NPM v3. With the up-to-date version of npm, anywhere there is a `package.json` file, there should be a correlating `package-lock.json` to ensure NPM dependency versions match. It looks like we are using NPM for the express server in the RPM, so that `package-lock.json` file should be there as well. I'll add it to the metron.spec file. That should resolve my issue. Thanks for your help!

**Comment by nickwallen** [comment]
+1 Thanks for taking care of this @sardell .  Works like a charm.

**Pull request closed without merging**
