### PR TITLE
METRON-1381: Add Apache license to MD files and remove the Rat exclusion

### PR DESCRIPTION
**Pull request by justinleet**
Added an HTML comment license header to all the MD files.  Removed the RAT exclusion for MD files, so we make sure to do it going forward.

It can be tested by looking at the GitHub rendering, along with building the site-book and making sure no Apache headers show up.  You can also create a .md file without a header and run the rat check to ensure that it catches the problem.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by nickwallen** [comment]
+1 (pending Travis) Looks good.  Ran through some tests as you described and everything worked.  Validated both Github and site-book rendering.

**Comment by ottobackwards** [comment]
+1

**Comment by justinleet** [comment]
@ottobackwards @JonZeolla Merged in master and added header to new markdown file (the deb deployment one).  Once you two are satisfied with the new commit, and I've run through the outstanding PRs for potentially problematic ones, I'm good with merging this in.

**Comment by JonZeolla** [comment]
Did you mean to tag @nickwallen in that last comment?  I took a quick look and it all looks good to me but didn't do any verification that you got all of the md files (depending on Travis), and didn't spin up the site-book.

**Comment by justinleet** [comment]
@JonZeolla Yes, I did. No idea what I was thinking, in all honesty.

@nickwallen You're the actual person I wanted here.

**Comment by justinleet** [comment]
@nickwallen @ottobackwards I'm going to (possibly annoyingly) ping again and use the excuse that the holidays are over.

**Comment by ottobackwards** [comment]
I'm +1

**Comment by nickwallen** [comment]
+1

**Pull request closed without merging**
