### PR TITLE
METRON-2316: [UI] Drag drop sorting for the selected fields in the Alerts UI

### PR DESCRIPTION
**Pull request by ruffle1986**
## Contributor Comments

Link to the ASF Jira ticket: https://issues.apache.org/jira/browse/METRON-2316

Currently, the users are able to change the order of the columns in the alerts list table by clicking the arrow buttons on the right side of each list item (in the configure table pane). 
But it would be more comfortable if we allowed the user to rearrange the columns by using drag and drop.

This PR introduces this capability of the Alerts UI application.

Testing
=====

1. Go to the Alerts UI and somehow generate a list of alerts on the screen
2. Click on the cog icon above the table, on the top right corner
3. Grab a column item on the left side of the pane
4. Put it somewhere else in the list (at the beginning, at the end, somewhere between the two)
5. You can also add new columns to the list from the right side of the pane
6. Try to rearrange the columns on the left involving the newly added columns

Demo
====

Kapture 2019-11-15 at 14 12 02

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [X] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [X] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [X] Have you included steps or a guide to how the change may be verified and tested manually?
- [X] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [X] Have you written or updated unit tests and or integration tests to verify your changes?
- [X] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [X] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

- [ ] Have you ensured that any documentation diagrams have been updated, along with their source files, using [draw.io](https://www.draw.io/)? See [Metron Development Guidelines](https://cwiki.apache.org/confluence/display/METRON/Development+Guidelines) for instructions.

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by sardell** [comment]
@ruffle1986 Once again, really nice work. Thanks for the thorough documentation of what you did. Not only does it help with my understanding, it also will help future users understand what we are doing here since we are deviating from the normal use of Dragula (for the good reason, as you pointed out).

I'm good with everything you've done, but I'm wondering if we should keep the up/down arrows for arranging columns. On the one hand, part of me wants to keep it for accessibility reasons (although we need to make it tab-able and add a key event binding to make that happen). On the other hand, I wonder if we are actually confusing users by keeping the up/down arrows. Maybe we should go with the first suggestion since it's a low amount of effort, and if we get feedback in Slack or the mailing list that it's confusing users, we can remove it. Are you good with this?

**Comment by ruffle1986** [comment]
Thank you, @sardell. I'm glad you like it. Dragula is fine. It's just the nature of Alerts UI why I had to choose the sideway.

I agree. Let's ask users about the arrow buttons and if they confuse people, we should definitely get rid of them.

**Comment by sardell** [comment]
@ruffle1986 I opened a PR against your branch which adds keyboard accessibility to the up/down arrows. Let's keep them for now, and in the future, if we hear from the users via the mailing list or Slack that it's causing confusion or not helping, we can remove them (or hide them until triggered by a keyboard user navigating through the page).

**Comment by sardell** [comment]
+1. Thanks for the contribution, @ruffle1986!

**Pull request closed without merging**
