### PR TITLE
METRON-2241 Profiler Integration Test Fails After Storm 1.2.1 Upgrade

### PR DESCRIPTION
**Pull request by nickwallen**
After the upgrade to Storm 1.2.1, there have been intermittent failures in the Storm Profiler integration tests.  

This integration test is the only one where multiple topologies are stopped and started during the test lifecycle. This is likely why it is only a problem for this test case.  The root cause is due to the way that the storm-kafka integration handles the Kafka consumer when a topology is stopped.   

This was identified as a bug in [STORM-3013](https://issues.apache.org/jira/browse/STORM-3013) and has been patched in storm-kafka version 1.2.3. This PR ensures that we are building against a build where this bug has been fixed.

## Acceptance Testing

- Run up Full Dev in centOS 7 and validate that alerts are visible in the Alerts UI.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

- [x] Have you ensured that any documentation diagrams have been updated, along with their source files, using [draw.io](https://www.draw.io/)? See [Metron Development Guidelines](https://cwiki.apache.org/confluence/display/METRON/Development+Guidelines) for instructions.

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by mmiklavc** [comment]
Considering the high exposure to classpath issues we have, what's the test plan for this beyond the basic Travis build?

**Comment by nickwallen** [comment]
What do you suggest?

**Comment by nickwallen** [comment]
I just did the basic 'vagrant up'.  I added that to the description.  Let me know if you think we should do more.

**Comment by mmiklavc** [comment]
@nickwallen I think that is reasonable here, specifically because I don't think your change is going to have ripple effects on the classpath. I did a quick comparison of the transitive dependencies and they don't seem to have changed. This is generally the type of exercise I'd use when deciding how far to go with a test plan.

1.2.2

image

1.2.3

image

+1 by inspection

**Comment by nickwallen** [comment]
This has been committed to the feature branch as 1004b694b2157acb9c8dda51fa49dd088d47fbbe.

**Pull request closed without merging**
