### PR TITLE
METRON-1615 Default endpoint locations based on Ambari service locations and config

### PR DESCRIPTION
**Pull request by simonellistonball**
## Contributor Comments
For certain values, the mpacks will now default values for the following settings:

- location of storm ui
- location of elastic search
- location of zeppelin notebook server

Testing involves spinning up full dev, and ensuring that while the settings es_url, storm_rest_url and zeppelin_url are set blank, the correct values (node1...) are set in the config files on disk. 

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by mmiklavc** [comment]
@simonellistonball - I'm happy to test this out if you can resolve the conflicts.

**Comment by mmiklavc** [comment]
@simonellistonball - Bump

**Comment by simonellistonball** [comment]
Turns out this is (in theory) done by the service advisor at             https://github.com/apache/metron/blob/ff1f9cf52b31ae866eb3de1cf8993af97af1790f/metron-deployment/packaging/ambari/metron-mpack/src/main/resources/common-services/METRON/CURRENT/service_advisor.py#L137 which doesn't look to have been significantly tested (doesn't for example work on a real cluster, and only works with overrides to blueprint templates to force application of settings (since the required field insists you enter a custom value). That therefore doesn't fire in default Ambari blueprint installs. 

You won't see that on full dev, or a platform that explicitly sets storm_rest_addr in blueprints to a correct value, but on something like a cloudbreak install (where you can't change the ambari configStrategy) it is impossible to get the service advisor to run. Since the fields in question are marked required, the service advisor cannot override them, and the blueprint cannot be submitted without setting them, so you're in a catch 22 if you do not know the host names upfront prior to install (the cloud install case).

In any case, this is probably not a good Apache fix, since from the Apache point of view this already 'works as designed'. Maybe I should file a separate ticket on the removing the required attribute from the settings which are not actually required, or it should be handled by rewriting the automation engine elsewhere, which would allow the service advisor to set them.

**Comment by mmiklavc** [comment]
> In any case, this is probably not a good Apache fix, since from the Apache point of view this already 'works as designed'.

Why would a bug fix for incomplete behavior not be a good fix for Apache?

**Comment by simonellistonball** [comment]
The fix is not necessary in pure Apache Ambari, and is only required in a non-Apache toolchain, hence from a pure Apache perspective 'works as designed' (just not very inclusively designed)

**Pull request closed without merging**
