### PR TITLE
METRON-2250 Missing services in HDP 3.1 metron mpack and installer stuck

### PR DESCRIPTION
**Pull request by zhaoyim**
## Contributor Comments
[Please place any comments here.  A description of the problem/enhancement, how to reproduce the issue, your testing methodology, etc.]

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [ ] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

- [ ] Have you ensured that any documentation diagrams have been updated, along with their source files, using [draw.io](https://www.draw.io/)? See [Metron Development Guidelines](https://cwiki.apache.org/confluence/display/METRON/Development+Guidelines) for instructions.

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by ottobackwards** [comment]
We currently don't support 3.1.  There is feature branch where that work is being done.  You may want to send an email to the dev@  list and ask about the status.

-1

**Comment by zhaoyim** [comment]
@ottobackwards Do you means the HDP 3.1? HDP 3.1 use ambari 2.7.3. Also the fix is also can used in ambari 2.4+ , because from ambari 2.4 it introduce the service advisor. And Thanks for you suggestion. I will send a mail to dev list to comfirm.

**Comment by nickwallen** [comment]
Thanks for the contribution @zhaoyim. Instead of submitting this PR against master, you could submit it against the feature branch with the HDP-3.1 upgrade; `feature/METRON-2088-support-hdp-3.1`.

**Comment by zhaoyim** [comment]
@nickwallen  Thanks for your suggestion. I will close this pr and resubmit to 'feature/METRON-2088-support-hdp-3.1'

**Comment by zhaoyim** [comment]
@nickwallen I saw in the 'feature/METRON-2088-support-hdp-3.1' branch already implements the 'colocateService' interface to fix the issue. So please ignore my fix. Thanks!

**Pull request closed without merging**
