### PR TITLE
METRON-2248 Merge Master into Feature Branch

### PR DESCRIPTION
**Pull request by nickwallen**
This change merges the latest from master into the `feature/METRON-2088-support-hdp-3.1` feature branch.  The most significant changes impacting the feature branch including METRON-2217 and METRON-2149.

Since the merge with master resulted in some merge conflicts and additional changes to ensure that things continued to work, I want to open a PR for this work.  

This PR will show all of the commits from master that are being merged into the feature branch, followed by a merge commit.  After the merge commit, the last 5 commits are changes that I ultimately needed to make the merge successful.

## Acceptance Testing

This PR should be tested using the centos7 development environment.  The feature branch is partially updated to work with HDP 3.1 at this point.  While Storm, Kafka, Zeppelin, and Solr have been updated HBase and Hadoop have not.  This means that only some functionality is working in the feature branch.  Anything that interacts with HBase and HDFS will most likely not work.

1. Start up the centos7 dev environment.
```
cd metron-deployment/development/centos7
vagrant destroy -f
vagrant up
```

### Setup

We need to turn off all enrichments that interact with HBase.  HBase is not yet functioning in the feature branch.

1.  Stop the Enrichment topology.

1. Launch the REPL.
    ```
    source /etc/default/metron
    cd $METRON_HOME
    bin/stellar -z $ZOOKEEPER
    ```

1.  Run the following commands in the REPL which turns-off any enrichments that interact with HBase.
    ```
    [Stellar]>>> conf := SHELL_EDIT()
    {
      "enrichment" : {
        "fieldMap" : {
          "geo" : [ "ip_dst_addr", "ip_src_addr" ]
        },
        "fieldToTypeMap" : { },
        "config" : { }
      },
      "threatIntel" : {
        "fieldMap" : {
        },
        "fieldToTypeMap" : {
        },
        "config" : { },
        "triageConfig" : {
          "riskLevelRules" : [ ],
          "aggregator" : "MAX",
          "aggregationConfig" : { }
        }
      },
      "configuration" : { }
    }

    [Stellar]>>> CONFIG_PUT("ENRICHMENT", conf, "bro")
    [Stellar]>>> CONFIG_PUT("ENRICHMENT", conf, "yaf")
    [Stellar]>>> CONFIG_PUT("ENRICHMENT", conf, "snort")
    ```

1. After the Enrichment topology has restarted, ensure that no errors are shown in the Storm UI.  

### Basics

Ensure that we can continue to parse, enrich, and index telemetry.  Verify data is flowing through the system, from parsing to indexing

1. Open Ambari and navigate to the Metron service http://node1:8080/#/main/services/METRON/summary

1. Open the Alerts UI.  Verify alerts show up in the main UI - click the search icon (you may need to wait a moment for them to appear)

1. Go to the Alerts UI and ensure that an ever increasing number of telemetry from Bro, Snort, and YAF are visible by watching the total alert count increase over time.

1. Ensure that geoip enrichment is occurring.  The telemetry should contain fields like `enrichments:geo:ip_src_addr:location_point`.

1. Head back to Ambari and select the Kibana service http://node1:8080/#/main/services/KIBANA/summary

  1. Open the Kibana dashboard via the "Metron UI" option in the quick links

  1. Verify the dashboard is populating

### Profiler in the REPL

1. Test a profile in the REPL according to [these instructions](https://github.com/apache/metron/tree/master/metron-analytics/metron-profiler-repl#getting-started).

    ```
    [Stellar]>>> values := PROFILER_FLUSH(profiler)
    [{period={duration=900000, period=1723089, start=1550780100000, end=1550781000000}, profile=hello-world, groups=[], value=4, entity=192.168.138.158}]
    ```

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

- [x] Have you ensured that any documentation diagrams have been updated, along with their source files, using [draw.io](https://www.draw.io/)? See [Metron Development Guidelines](https://cwiki.apache.org/confluence/display/METRON/Development+Guidelines) for instructions.

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by mmiklavc** [comment]
@nickwallen we need to be testing on a Centos 7 box for the feature branch, no?

**Comment by mmiklavc** [comment]
@nickwallen I reviewed the commits you made to get this working post-merge and it looks good to me. I'm +1 by inspection, unless you want to definitely have another person run through the test plan on this.

**Comment by nickwallen** [comment]
> @mmiklavc we need to be testing on a Centos 7 box for the feature branch, no?

You are right. I updated the description and test instructions to help better clarify what is and is not working in the feature branch and how it should be tested.  Since we are mid-upgrade only some functionality will work.

**Comment by mmiklavc** [comment]
+1

**Comment by nickwallen** [comment]
This has been merged in master.

**Pull request closed without merging**
