### PR TITLE
METRON-1864 fix issue where daylight savings breaks tests

### PR DESCRIPTION
**Pull request by ottobackwards**
Thanks to @justinleet for the fix.  I would have use a totally awesome but overdone regex.

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [-] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [-] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [-] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [-] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [-] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by mmiklavc** [comment]
Thanks @ottobackwards and @justinleet!

Did you mean to completely remove the assertions for that test? It seems like we would still want to validate the results somehow.

Also, since the context for this PR came from discussions in Slack that don't show up on the dev list, can you add a comment about the motivation/origin for this fix?

**Comment by justinleet** [comment]
@mmiklavc Right now the function just tests that the result is properly formatted (which is really all the original test did, but it just checked the string matched a timezone).  This will throw an exception if it's not.

The problem with validating further on this test is that it's essentially against "now", which means that we don't know exactly what the date is, other than what we get back.  Anything we choose would be slightly off.

We could probably refactor things around to make it possible to inject a given timestamp for a no arg run of the statement, but I'm not convinced that needs to happen to resolve the current unit test problem.

**Comment by mmiklavc** [comment]
@justinleet We do use mock clocks in other parts of the platform, but for the sake of this fix I think this is fine. @ottobackwards Can we just throw a comment in the test so it's obvious that this is intentionally without assertions here?

**Comment by ottobackwards** [comment]
I think that the test logically tests what we are concerned about, that the format of the produced string matches the desired format.  Testing that the value is explicitly x,y,z isn't testing the format, it is testing something else.

I propose, with a mind to getting master and pr's building again, that I comment as requested but not change the test, and that any other ideas for improvement and or expansion of the tests be put to a jira for later work.

**Comment by justinleet** [comment]
@ottobackwards I'm good with that

**Comment by mmiklavc** [comment]
+1

**Pull request closed without merging**
