### PR TITLE
METRON-1636: Fix broken unit test setup in metron-alerts

### PR DESCRIPTION
**Pull request by tiborm**
## Contributor Comments

I made changes in the unit tests of the metron-alert UI to make test runnable.
All the dependencies of the tested components, directives, and pipes were mocked out or included to avoid runtime errors. I also unified the naming of the tests.

I also removed Router from table-view.component and tree-view.component because it was just injected as an unused dependency which also has had to be mocked out in the tests otherwise.
This change was checked and manually tested with caution to avoid any regression.

### Steps to run Unit Test in metron-alert:
1. clone repo
2. go to metron-interface/metron-alert/
3. run: npm install
4. run: npm test

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by cestella** [comment]
Hey, thanks for the contribution!  Can you make the title METRON-1636: Fix broken unit test setup in metron-alerts?  Also, if you could mark the boxes in the pull request checklist to let us know that you've done them (e.g. instead of `[]`, make the ones that are done `[x]` in the markdown).

**Comment by tiborm** [comment]
Fixed the title. Checking why travis check fails...

**Comment by sardell** [comment]
I tested this in full-dev and the unit tests now pass when run. I'm really happy to see this done so we can start to build upon these base tests. +1.

**Comment by cestella** [comment]
It looks like this is a conflict and the unit tests aren't quite running, past that I'm +1

**Comment by cestella** [comment]
@nickwallen these tests are failing because of:
```
Results :

Failed tests: 
  ProfileBuilderBoltTest.testFlushExpiredProfiles:205->getProfileMeasurements:265 
outputCollector.emit(
    "hbase",
    <Capturing argument>
);
Wanted 1 time:
-> at org.apache.metron.profiler.bolt.ProfileBuilderBoltTest.getProfileMeasurements(ProfileBuilderBoltTest.java:265)
But was 2 times. Undesired invocation:
-> at org.apache.metron.profiler.bolt.HBaseEmitter.emit(HBaseEmitter.java:54)
```

I'm pretty sure this PR isn't causing those failures, have you (or anyone else who is watching) seen `ProfileBuilderBoltTest` fail intermittently?

**Comment by nickwallen** [comment]
I have not seen that before.  Fun.  I'll take a look-see.

**Comment by tiborm** [comment]
Conflict resolved.

**Comment by tiborm** [comment]
Reopening to trigger new travis build.

**Pull request closed without merging**
