### PR TITLE
METRON-1713: PCAP UI - Add a way to kill a pcap job

### PR DESCRIPTION
**Pull request by tiborm**
## Contributor Comments
This PR contains the implementation of the cancel button of a running pcap query.

screen shot 2018-08-07 at 5 59 34 pm

Please find more detail about it in https://issues.apache.org/jira/browse/METRON-1713

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by justinleet** [comment]
Please change the title to "METRON-1713: PCAP UI - Add a way to kill a pcap job" to match https://issues.apache.org/jira/browse/METRON-1713

**Comment by justinleet** [comment]
If the job has been submitted, but not yet returned with a job id (because it takes a few seconds to kick of a job), the kill request fails.

The request goes to (for example) http://node1:4201/api/v1/pcap/kill/undefined

The job continues in the background with no progress bar or ability to cancel.

Otherwise, this seems to function pretty well.

Once the conflicts are cleaned up, I'll take another look.

**Comment by tiborm** [comment]
Thanks, Justin! I updated the PR with a small fix.

**Comment by justinleet** [comment]
Hey, I played around with this a bit.  I think there's more nuance here.  When I do a kill a job in the middle of submission, what happens is it kicks off a kill that fails still:

```
{"timestamp":"2018-08-07 22:12:29","status":405,"error":"Method Not Allowed","message":"Request method 'DELETE' not supported","path":"/api/v1/pcap/kill/"}
```

The job still kicks off (which doesn't terribly surprise me, since it's async).  At that point, the progress bar has disappeared, but you can't kick off another job (it'll throw an error since you're already running a job).

It seems like something like this (and feel free to throw out more ideas) would be ncie:
1. The UI indicates cancellation of submitted job is in progress. E.g. the progress bar or something similar to how error messages are displayed says "Cancellation in progress". I'm not really sure what the best way to to it is.
2. The call to create a job waits until it gets back it's job id.  It then calls kill on the returned job.  That way we aren't running the job in the background and locking the user out.
3. After cancellation of the submitting job, the user is again free to submit a new job.  They're only locked out for the duration of the cancellation, not until job completion.

**Comment by merrimanr** [comment]
Does this PR also contain METRON-1712?  I don't see anything in the PR description stating that and I see several changes that are not related to this PR.

**Comment by merrimanr** [comment]
@justinleet I am seeing different behavior.  When I submit a query, the cancel button appears but is disabled.  I am not able to kill a job in the middle of submission.  After the job submission request returns with a job id, the cancel button becomes active.  When I click the cancel button, the kill command succeeds with no errors.  If we want to add a "Cancellation in progress" message while the kill request is being processed I think that makes sense.  For me, this is working as expected.

The error you posted has nothing to do with the state of a job submission.  My guess is that you don't have the most recent code deployed in full dev.  That 405 error suggests that endpoint doesn't exist.  Let me know if I am misunderstanding something.

**Comment by justinleet** [comment]
Sigh, my inability to get my browser in a consistent state strikes again.  Clearing everything out and trying again shows the behavior you describe.

**Comment by tiborm** [comment]
@merrimanr Yes, it contains the latest state of METRON-1712 and feature/METRON-1554-pcap-query-panel.

**Comment by merrimanr** [comment]
@tiborm can you merge the latest feature branch in?  @justinleet are there any other outstanding requests or are you satisfied?

**Comment by merrimanr** [comment]
This is merged.  Can you close @tiborm?

**Pull request closed without merging**
