### PR TITLE
METRON-1482: Update REST to work with Solr

### PR DESCRIPTION
**Pull request by merrimanr**
## Contributor Comments
This PR updates the REST start script to properly include the correct indexing jar on the classpath depending on the configured indexing writer (Elasticsearch or Solr).  To test this:

1. Spin up full dev and follow the instructions for manually installing Solr:  https://github.com/apache/metron/tree/feature/METRON-1416-upgrade-solr/metron-platform/metron-solr#installing. 
2. Change the Index Writer to "Solr" in Ambari (Metron > Indexing tab) and restart the Indexing component.
3. Verify data is landing in the Solr collections
4. Restart the REST component in Ambari
5. You should be able to execute search queries in Swagger

I had to include a stubbed SolrMetaAlertDao class that doesn't do anything to get everything to start up.  This will eventually be replaced by the work being done in https://issues.apache.org/jira/browse/METRON-1421.  I also fixed a bug in the SolrDao that was causing in issue in the Alerts UI.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by justinleet** [comment]
There's a bunch of @cestella commits in here.  Do you need to merge feature/METRON-1416-upgrade-solr into this PR?

**Comment by merrimanr** [comment]
I've been maintaining this branch for a while and have been merging in other branches before they were committed to master.  I think that's why you see all these commits.  I merged in feature/METRON-1416-upgrade-solr right before I submitted this PR.  It's the commit right before "fixed metron version".

**Comment by justinleet** [comment]
yeah, don't worry about it, it's not important, just a bit odd.

**Comment by justinleet** [comment]
I'm unable to get a fairly basic query working. A matching doc exists, based on querying solr directly. I assume I'm doing something obviously wrong here?

```
{
  "fields": [
    "*"
  ],
  "from": 0,
  "indices": [
    "bro"
  ],
  "query": "adapter.threatinteladapter.end.ts:1520528353609"
  ]
}
```

**Comment by justinleet** [comment]
Error code is just a 400, btw.

**Comment by justinleet** [comment]
Don't leave an extra square brace. Sigh. My bad

**Comment by justinleet** [comment]
+1, I'm able to spin it up and query.  Good job!

**Pull request closed without merging**
