### PR TITLE
METRON-1826: Update librdkafka and devtoolset

### PR DESCRIPTION
**Pull request by JonZeolla**
## Contributor Comments
This fixes a build issue with pycapa due to a dependency on a newer version of librdkafka, updates the librdkafka plugin as used in the bro plugin, and updates librdkafka as used in fastcapa.  Without this, spinning up the full dev environment (not skipping sensors) is broken.

### Testing

Spin up full dev without skipping 'sensors'.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by JonZeolla** [comment]
Looks like something happened to devtoolset-4, moving to -6 as well.

**Comment by nickwallen** [comment]
+1 Thanks

This took a bit more work to validate since the sensors don't just work auto-magically.  I had to manually restart each of the sensors and pcap-replay for things to really start functioning.

After running the following commands, I am able to see the number of alerts growing for each of the 3 demo sensors.

```
vagrant --ansible-skip-tags="sensor-stubs" up
vagrant ssh
sudo su - 
service pcap-replay restart
service yaf restart
service snortd restart
service snort-producer restart
```

screen shot 2018-10-20 at 3 27 52 pm

**Comment by JonZeolla** [comment]
Right, I was actually considering documenting that a bit better.  I'll add something [here](https://github.com/apache/metron/tree/master/metron-deployment/development/centos6#working-with-metron) and [here](https://github.com/apache/metron/tree/master/metron-deployment/development/ubuntu14#working-with-metron).

**Comment by JonZeolla** [comment]
@nickwallen any concerns with my doc update?

**Comment by nickwallen** [comment]
It is a good add, but I think it is a little confusing. I would suggest that we add this in a new section under "Working with Metron";  something like "Working with Sensors". 

It should describes from start-to-finish how to build an environment with sensors. It might look something like this.

### Working with Sensors

By default, the development environment does not install and run the demo sensors...yada yada.

1. Launch the development environment.
   ```
   vagrant --ansible-skip-tags="sensor-stubs" up
   ```

1. Start the sensors.
    ```
    vagrant ssh
    sudo su - 
    service pcap-replay restart
    service yaf restart
    service snortd restart
    service snort-producer restart  
    ```

**Comment by JonZeolla** [comment]
Took a stab at better explaining how sensors work and how to use them.

**Comment by nickwallen** [comment]
+1 LGTM

**Pull request closed without merging**
