### PR TITLE
Metron 451 SerDeUtils - java.lang.ClassNotFoundException: org.apache.storm.shade.org.joda.time.DateTime

### PR DESCRIPTION
**Pull request by danieljue**
Fix for METRON-451
SerDeUtils - java.lang.ClassNotFoundException: org.apache.storm.shade.org.joda.time.DateTime

Sorry guys and gals, forgot to put this fix in it's own branch, might have screwed up previous PR.

### CODE REVIEW

**Comment by nickwallen** [comment]
The license check failed.  Take a look at the [`build_utils/README`](build_utils/README.md).  I believe we just need to update the `dependencies_with_url.csv` file with joda-time.

**Comment by nickwallen** [comment]
It would be great if we could add a unit test that exercises this bug.

**Comment by danieljue** [comment]
@nickwallen , interesting because the jodatime dependency is already in that CSV (it was included in API, but had to add it to the Common module pom)

Seems to  be failing at the same place as METRON-363 Fix Cisco ASA Parser :

`Sep 27, 2016 1:28:55 AM com.google.inject.servlet.InternalServletModule$BackwardsCompatibleServletContextProvider get
WARNING: You are attempting to use a deprecated API (specifically, attempting to @Inject ServletContext inside an eagerly created singleton. While we allow this for backwards compatibility, be warned that this MAY have unexpected behavior if you have more than one injector (with ServletModule) running in the same JVM. Please consult the Guice documentation at http://code.google.com/p/google-guice/wiki/Servlets for more information.
Sep 27, 2016 1:28:55 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.apache.hadoop.yarn.webapp.YarnJacksonJaxbJsonProvider as a provider class
Sep 27, 2016 1:28:55 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.apache.hadoop.yarn.server.applicationhistoryservice.webapp.AHSWebServices as a root resource class
Sep 27, 2016 1:28:55 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.apache.hadoop.yarn.server.timeline.webapp.TimelineWebServices as a root resource class
Sep 27, 2016 1:28:55 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
INFO: Registering org.apache.hadoop.yarn.webapp.GenericExceptionHandler as a provider class
Sep 27, 2016 1:28:55 AM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
Sep 27, 2016 1:28:55 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.apache.hadoop.yarn.webapp.GenericExceptionHandler to GuiceManagedComponentProvider with the scope "Singleton"
Sep 27, 2016 1:28:55 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.apache.hadoop.yarn.webapp.YarnJacksonJaxbJsonProvider to GuiceManagedComponentProvider with the scope "Singleton"
Sep 27, 2016 1:28:55 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.apache.hadoop.yarn.server.applicationhistoryservice.webapp.AHSWebServices to GuiceManagedComponentProvider with the scope "Singleton"
Sep 27, 2016 1:28:55 AM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
INFO: Binding org.apache.hadoop.yarn.server.timeline.webapp.TimelineWebServices to GuiceManagedComponentProvider with the scope "Singleton"
2016-09-27 01:28:59,179 ERROR [Curator-TreeCache-0] curator.ConnectionState (ConnectionState.java:checkTimeouts(200)) - Connection timed out for connection string (127.0.0.1:48078) and timeout (15000) / elapsed (31009)
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:197)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:87)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:477)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:200)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:191)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38)
	at org.apache.curator.x.discovery.details.ServiceDiscoveryImpl.queryForNames(ServiceDiscoveryImpl.java:276)
	at org.apache.metron.maas.discovery.ServiceDiscoverer.updateState(ServiceDiscoverer.java:129)
	at org.apache.metron.maas.discovery.ServiceDiscoverer.lambda$new$2(ServiceDiscoverer.java:93)
	at org.apache.metron.maas.discovery.ServiceDiscoverer$$Lambda$34/648409124.childEvent(Unknown Source)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:685)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:679)
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:92)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:84)
	at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:678)
	at org.apache.curator.framework.recipes.cache.TreeCache.access$1400(TreeCache.java:69)
	at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:790)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by danieljue** [comment]
Am I supposed to be able to build Metron from the command line on a Mac with Java 8?

**Comment by cestella** [comment]
So, maven from the command line should work.  Also the tests do function from intellij, I can attest.

**Comment by danieljue** [comment]
Thanks for the info @cestella !

I get build success on all the modules if I do `mvn clean install -U -DskipTests=true`  from the top level Metron directory.  ;)

I think the integrations tests in maas-common that are getting triggered are causing builds to fail for me.  (Could be others if it would get passed that).

I'll open a new ticket so this doesn't get lost in the weeds on this thread.

**Comment by nickwallen** [comment]
@danieljue - can you merge this branch with master?  hopefully then we can get a clean CI build.  if we get a good build, we can get your PR committed.

**Comment by nickwallen** [comment]
Actually sorry, I was thinking of your other outstanding PR.  For this one, I think we need some way to test the change.  If you can provide a means for testing, we can get some reviewers on this.

**Comment by danieljue** [comment]
Roger that, will devise a test.

**Comment by ottobackwards** [comment]
What is the status of this?

**Comment by ottobackwards** [comment]
This PR will be closed soon if not updated.  Is there any update for it's status?

**Comment by nickwallen** [comment]
@danieljue Please close this PR unless you believe it is still needed.  This PR will be closed per the [Metron Development Guidelines](https://cwiki.apache.org/confluence/display/METRON/Development+Guidelines) on Inactive PRs, unless you provide some reasoning as to why it is stil needed. Thanks!

**Comment by nickwallen** [comment]
-1 Based on the [Metron Development Guidelines](https://cwiki.apache.org/confluence/display/METRON/Development+Guidelines) on Inactive PR.  Missing contributor feedback.  I will open an Apache Infra request to close this PR.

**Pull request closed without merging**
