### PR TITLE
METRON-2039: Time range queries do not work with Solr

### PR DESCRIPTION
**Pull request by merrimanr**
## Contributor Comments
This PR updates the query generated from the time select control to work with both Elasticsearch and Solr.  Before this query would be generated and only worked with Elasticsearch:
```
{
  "indices": [],
  "facetFields": [],
  "query": "(timestamp:(>=1552674515000 AND  <=1552674815000) OR metron_alert.timestamp:(>=1552674515000 AND  <=1552674815000))",
  "from": 0,
  "size": 25
}
```
The same query fails in Solr with an `Invalid Number` exception.  Now the same query is generated with syntax that works in both:
```
{
  "indices": [],
  "facetFields": [],
  "query": "(timestamp:[1552539600000 TO 1552625999000] OR metron_alert.timestamp:[1552539600000 TO 1552625999000])",
  "from": 0,
  "size": 25
}
```

### Testing
I have verified this in full dev with Solr.  Navigate to the Alerts UI and select a filter in the time widget (just to the left of the search icon).  The search should return a 200 instead of a 500.  The syntax was tested directly against REST in a separate cluster with Elasticsearch.  Testing in full dev with Elasticsearch is still needed.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by nickwallen** [comment]
I was testing this using the Alerts UI.  All the pre-defined "Quick Ranges" work for me.  But when using the calendar widget, an error occurs.

Screen Shot 2019-03-15 at 5 14 25 PM

Request:
```
{"indices":[],"facetFields":[],"query":"(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])","from":0,"size":25}
```

REST Logs:
```
2019-03-15 21:14:19.224 ERROR 2036 --- [nio-8082-exec-5] o.a.m.r.c.RestExceptionHandler           : Encountered error: Failed to execute search; error='ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]', search='{"from":0,"size":25,"query":{"constant_score":{"filter":{"bool":{"must":[{"bool":{"should":[{"query_string":{"query":"(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])","fields":[],"use_dis_max":true,"tie_breaker":0.0,"default_operator":"or","auto_generate_phrase_queries":false,"max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"split_on_whitespace":true,"boost":1.0}},{"nested":{"query":{"query_string":{"query":"(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])","fields":[],"use_dis_max":true,"tie_breaker":0.0,"default_operator":"or","auto_generate_phrase_queries":false,"max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"split_on_whitespace":true,"boost":1.0}},"path":"metron_alert","ignore_unmapped":false,"score_mode":"none","boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}},{"bool":{"should":[{"term":{"status":{"value":"active","boost":1.0}}},{"bool":{"must_not":[{"exists":{"field":"status","boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}}],"must_not":[{"exists":{"field":"metaalerts","boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}},"boost":1.0}},"_source":{"includes":[],"excludes":[]},"sort":[{"timestamp":{"order":"desc","missing":"_last","unmapped_type":"date"}}],"track_scores":true,"aggregations":{"source:type_count":{"terms":{"field":"source:type","size":10,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_term":"asc"}]}},"ip_src_addr_count":{"terms":{"field":"ip_src_addr","size":10,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_term":"asc"}]}},"ip_dst_addr_count":{"terms":{"field":"ip_dst_addr","size":10,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_term":"asc"}]}},"enrichments:geo:ip_dst_addr:country_count":{"terms":{"field":"enrichments:geo:ip_dst_addr:country","size":10,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_term":"asc"}]}}}}'

org.apache.metron.rest.RestException: Failed to execute search; error='ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]', search='{"from":0,"size":25,"query":{"constant_score":{"filter":{"bool":{"must":[{"bool":{"should":[{"query_string":{"query":"(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])","fields":[],"use_dis_max":true,"tie_breaker":0.0,"default_operator":"or","auto_generate_phrase_queries":false,"max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"split_on_whitespace":true,"boost":1.0}},{"nested":{"query":{"query_string":{"query":"(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])","fields":[],"use_dis_max":true,"tie_breaker":0.0,"default_operator":"or","auto_generate_phrase_queries":false,"max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"split_on_whitespace":true,"boost":1.0}},"path":"metron_alert","ignore_unmapped":false,"score_mode":"none","boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}},{"bool":{"should":[{"term":{"status":{"value":"active","boost":1.0}}},{"bool":{"must_not":[{"exists":{"field":"status","boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}}],"must_not":[{"exists":{"field":"metaalerts","boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}},"boost":1.0}},"_source":{"includes":[],"excludes":[]},"sort":[{"timestamp":{"order":"desc","missing":"_last","unmapped_type":"date"}}],"track_scores":true,"aggregations":{"source:type_count":{"terms":{"field":"source:type","size":10,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_term":"asc"}]}},"ip_src_addr_count":{"terms":{"field":"ip_src_addr","size":10,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_term":"asc"}]}},"ip_dst_addr_count":{"terms":{"field":"ip_dst_addr","size":10,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_term":"asc"}]}},"enrichments:geo:ip_dst_addr:country_count":{"terms":{"field":"enrichments:geo:ip_dst_addr:country","size":10,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_term":"asc"}]}}}}'
        at org.apache.metron.rest.service.impl.SearchServiceImpl.search(SearchServiceImpl.java:95) ~[metron-rest-0.7.1.jar:?]
        at org.apache.metron.rest.controller.SearchController.search(SearchController.java:54) ~[metron-rest-0.7.1.jar:?]
Caused by: org.apache.metron.indexing.dao.search.InvalidSearchException: Failed to execute search; error='ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]', search='{"from":0,"size":25,"query":{"constant_score":{"filter":{"bool":{"must":[{"bool":{"should":[{"query_string":{"query":"(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])","fields":[],"use_dis_max":true,"tie_breaker":0.0,"default_operator":"or","auto_generate_phrase_queries":false,"max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"split_on_whitespace":true,"boost":1.0}},{"nested":{"query":{"query_string":{"query":"(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])","fields":[],"use_dis_max":true,"tie_breaker":0.0,"default_operator":"or","auto_generate_phrase_queries":false,"max_determinized_states":10000,"enable_position_increments":true,"fuzziness":"AUTO","fuzzy_prefix_length":0,"fuzzy_max_expansions":50,"phrase_slop":0,"escape":false,"split_on_whitespace":true,"boost":1.0}},"path":"metron_alert","ignore_unmapped":false,"score_mode":"none","boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}},{"bool":{"should":[{"term":{"status":{"value":"active","boost":1.0}}},{"bool":{"must_not":[{"exists":{"field":"status","boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}}],"must_not":[{"exists":{"field":"metaalerts","boost":1.0}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}},"boost":1.0}},"_source":{"includes":[],"excludes":[]},"sort":[{"timestamp":{"order":"desc","missing":"_last","unmapped_type":"date"}}],"track_scores":true,"aggregations":{"source:type_count":{"terms":{"field":"source:type","size":10,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_term":"asc"}]}},"ip_src_addr_count":{"terms":{"field":"ip_src_addr","size":10,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_term":"asc"}]}},"ip_dst_addr_count":{"terms":{"field":"ip_dst_addr","size":10,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_term":"asc"}]}},"enrichments:geo:ip_dst_addr:country_count":{"terms":{"field":"enrichments:geo:ip_dst_addr:country","size":10,"min_doc_count":1,"shard_min_doc_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_term":"asc"}]}}}}'
        at org.apache.metron.elasticsearch.dao.ElasticsearchRequestSubmitter.submitSearch(ElasticsearchRequestSubmitter.java:72) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.apache.metron.elasticsearch.dao.ElasticsearchSearchDao.search(ElasticsearchSearchDao.java:128) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.apache.metron.elasticsearch.dao.ElasticsearchDao.search(ElasticsearchDao.java:199) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.apache.metron.elasticsearch.dao.ElasticsearchMetaAlertSearchDao.search(ElasticsearchMetaAlertSearchDao.java:81) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.apache.metron.elasticsearch.dao.ElasticsearchMetaAlertDao.search(ElasticsearchMetaAlertDao.java:209) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.apache.metron.rest.service.impl.SearchServiceImpl.search(SearchServiceImpl.java:92) ~[metron-rest-0.7.1.jar:?]
        ... 95 more
Caused by: org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
        at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:526) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:502) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:409) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:382) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:323) ~[metron-elasticsearch-0.7.1-uber.jar:?]
Caused by: org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
        at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:526) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:502) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:409) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:382) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:323) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.apache.metron.elasticsearch.dao.ElasticsearchRequestSubmitter.submitSearch(ElasticsearchRequestSubmitter.java:62) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.apache.metron.elasticsearch.dao.ElasticsearchSearchDao.search(ElasticsearchSearchDao.java:128) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.apache.metron.elasticsearch.dao.ElasticsearchDao.search(ElasticsearchDao.java:199) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.apache.metron.elasticsearch.dao.ElasticsearchMetaAlertSearchDao.search(ElasticsearchMetaAlertSearchDao.java:81) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.apache.metron.elasticsearch.dao.ElasticsearchMetaAlertDao.search(ElasticsearchMetaAlertDao.java:209) ~[metron-elasticsearch-0.7.1-uber.jar:?]
        at org.apache.metron.rest.service.impl.SearchServiceImpl.search(SearchServiceImpl.java:92) ~[metron-rest-0.7.1.jar:?]
        ... 95 more
        Suppressed: org.elasticsearch.client.ResponseException: POST http://node1:9200/websphere_index*,syslog5424_index*,jsonMap_index*,syslog3164_index*,jsonMapQuery_index*,squid_index*,jsonMapWrappedQuery_index*,snort_index*,bro_index*,asa_index*,yaf_index*,metaalert_index*/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=query_then_fetch&batched_reduce_size=512: HTTP/1.1 400 Bad Request
{"error":{"root_cause":[{"type":"query_shard_exception","reason":"Failed to parse query [(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])]","index_uuid":"O6bqu6rTRXySqi8aOupasg","index":"bro_index_2019.03.15.20"},{"type":"query_shard_exception","reason":"Failed to parse query [(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])]","index_uuid":"kJxGt42kSomXDTo4NttPGw","index":"bro_index_2019.03.15.21"},{"type":"query_shard_exception","reason":"Failed to parse query [(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])]","index_uuid":"Ir-zkIuHQPeDOJLXmTdCzA","index":"snort_index_2019.03.15.20"},{"type":"query_shard_exception","reason":"Failed to parse query [(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])]","index_uuid":"i9abS3seQiuYAH7nYxi9pQ","index":"snort_index_2019.03.15.21"},{"type":"query_shard_exception","reason":"Failed to parse query [(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])]","index_uuid":"jCTMIw44RPa34CSdOtVdcQ","index":"yaf_index_2019.03.15.20"},{"type":"query_shard_exception","reason":"Failed to parse query [(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])]","index_uuid":"96uwr_x7SVeZUPLrLY-reA","index":"yaf_index_2019.03.15.21"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"bro_index_2019.03.15.20","node":"86-b1IQRRiOleDiyH4r54A","reason":{"type":"query_shard_exception","reason":"Failed to parse query [(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])]","index_uuid":"O6bqu6rTRXySqi8aOupasg","index":"bro_index_2019.03.15.20","caused_by":{"type":"parse_exception","reason":"Cannot parse '(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])': Encountered \" \"]\" \"] \"\" at line 1, column 25.\nWas expecting:\n    \"TO\" ...\n    ","caused_by":{"type":"parse_exception","reason":"Encountered \" \"]\" \"] \"\" at line 1, column 25.\nWas expecting:\n    \"TO\" ...\n    "}}}},{"shard":0,"index":"bro_index_2019.03.15.21","node":"86-b1IQRRiOleDiyH4r54A","reason":{"type":"query_shard_exception","reason":"Failed to parse query [(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])]","index_uuid":"kJxGt42kSomXDTo4NttPGw","index":"bro_index_2019.03.15.21","caused_by":{"type":"parse_exception","reason":"Cannot parse '(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])': Encountered \" \"]\" \"] \"\" at line 1, column 25.\nWas expecting:\n    \"TO\" ...\n    ","caused_by":{"type":"parse_exception","reason":"Encountered \" \"]\" \"] \"\" at line 1, column 25.\nWas expecting:\n    \"TO\" ...\n    "}}}},{"shard":0,"index":"snort_index_2019.03.15.20","node":"86-b1IQRRiOleDiyH4r54A","reason":{"type":"query_shard_exception","reason":"Failed to parse query [(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])]","index_uuid":"Ir-zkIuHQPeDOJLXmTdCzA","index":"snort_index_2019.03.15.20","caused_by":{"type":"parse_exception","reason":"Cannot parse '(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])': Encountered \" \"]\" \"] \"\" at line 1, column 25.\nWas expecting:\n    \"TO\" ...\n    ","caused_by":{"type":"parse_exception","reason":"Encountered \" \"]\" \"] \"\" at line 1, column 25.\nWas expecting:\n    \"TO\" ...\n    "}}}},{"shard":0,"index":"snort_index_2019.03.15.21","node":"86-b1IQRRiOleDiyH4r54A","reason":{"type":"query_shard_exception","reason":"Failed to parse query [(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])]","index_uuid":"i9abS3seQiuYAH7nYxi9pQ","index":"snort_index_2019.03.15.21","caused_by":{"type":"parse_exception","reason":"Cannot parse '(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])': Encountered \" \"]\" \"] \"\" at line 1, column 25.\nWas expecting:\n    \"TO\" ...\n    ","caused_by":{"type":"parse_exception","reason":"Encountered \" \"]\" \"] \"\" at line 1, column 25.\nWas expecting:\n    \"TO\" ...\n    "}}}},{"shard":0,"index":"yaf_index_2019.03.15.20","node":"86-b1IQRRiOleDiyH4r54A","reason":{"type":"query_shard_exception","reason":"Failed to parse query [(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])]","index_uuid":"jCTMIw44RPa34CSdOtVdcQ","index":"yaf_index_2019.03.15.20","caused_by":{"type":"parse_exception","reason":"Cannot parse '(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])': Encountered \" \"]\" \"] \"\" at line 1, column 25.\nWas expecting:\n    \"TO\" ...\n    ","caused_by":{"type":"parse_exception","reason":"Encountered \" \"]\" \"] \"\" at line 1, column 25.\nWas expecting:\n    \"TO\" ...\n    "}}}},{"shard":0,"index":"yaf_index_2019.03.15.21","node":"86-b1IQRRiOleDiyH4r54A","reason":{"type":"query_shard_exception","reason":"Failed to parse query [(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])]","index_uuid":"96uwr_x7SVeZUPLrLY-reA","index":"yaf_index_2019.03.15.21","caused_by":{"type":"parse_exception","reason":"Cannot parse '(timestamp:[1552622400000] OR metron_alert.timestamp:[1552622400000])': Encountered \" \"]\" \"] \"\" at line 1, column 25.\nWas expecting:\n    \"TO\" ...\n    ","caused_by":{"type":"parse_exception","reason":"Encountered \" \"]\" \"] \"\" at line 1, column 25.\nWas expecting:\n    \"TO\" ...\n    "}}}}]},"status":400}
                at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123) ~[metron-rest-0.7.1.jar:?]
                at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) ~[metron-elasticsearch-0.7.1-uber.jar:?]
                at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by nickwallen** [comment]
Also, are there unit tests that we can add/enhance around this bug?

**Comment by tiborm** [comment]
Tested against Full Dev/Elasticsearch and experienced the same as @nickwallen.

**Comment by nickwallen** [comment]
+1 Looks good.  Thanks for the fix @merrimanr and @tiborm

**Pull request closed without merging**
