### PR TITLE
METRON-1233: Remove description of Global configuration from Enrichment doc

### PR DESCRIPTION
**Pull request by DimDroll**
It confuses reader. Description of Global configuration is available ahead of the enrichment and listed here:
https://metron.apache.org/current-book/metron-platform/metron-common/index.html
Global config is used for validation of the fields.
Enrichment is used for fields enrichment and probably can also be used for validation of the fields (which is not covered in the doc).
From available doc I can see that they serve two different purposes.

So, I don't see any reason to mention global config in enrichment description. What's the benefit of knowing about global configuration when you want deep dive in enrichment?

## Contributor Comments
[Please place any comments here.  A description of the problem/enhancement, how to reproduce the issue, your testing methodology, etc.]

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by mmiklavc** [comment]
Thanks for the contribution @DimDroll. Can you take a look at https://github.com/apache/metron/pull/791 - does this help? There are some relevant global config options for enrichment.

**Comment by justinleet** [comment]
@DimDroll Is this still relevant with Mike's comment about #791?

**Comment by mmiklavc** [comment]
Bump

**Comment by ottobackwards** [comment]
This needs deconflict, and a relevant check

**Comment by ottobackwards** [comment]
Still needs conflict resolution, still needs relevancy check

**Comment by DimDroll** [comment]
@mmiklavc , I still don't see anything helpful specified about enrichment in here:
https://metron.apache.org/current-book/metron-platform/metron-common/index.html
I guess we can reference enrichment configuration in global configuration, but I still don't see sense of mentioning Global configuration in Enrichment section without anything relevant to enrichment in Global configuration.

**Comment by ottobackwards** [comment]
bump.  Let's get a response on this @mmiklavc , @JonZeolla , @nickwallen

**Comment by mmiklavc** [comment]
@DimDroll @ottobackwards - All of our topologies pull in the global config. One such more recent example is that we now provide an option for specifying batching details for enrichment:
```
enrichment.writer.batchSize
enrichment.writer.batchTimeout
```

The reason for this is that we don't have a global-only-per-topology type of configuration, with the exception parsers because of how they can be deployed independently. If you think there's some better clarification that could be made, I'm open to it. But I think the link between parsers, enrichment, indexing, and the global configs should be maintained as it is relevant.

**Comment by ottobackwards** [comment]
@mmiklavc can you re-visit this and if it is not going to land close it?

**Comment by mmiklavc** [comment]
@ottobackwards - considering the current state of enrichment and global config options, I think we should close this. Anything special we need to do to close someone else's PR? We've crossed the threshold for activity lapse, so maybe that's all.

**Comment by ottobackwards** [comment]
@DimDroll we are going to close this at this time.  Please feel free to open a DISCUSS thread on the dev list to continue the discussion.

**Pull request closed without merging**
