### PR TITLE
METRON-1273: Website documentation link should point to the current site-book

### PR DESCRIPTION
**Pull request by JonZeolla**
## Contributor Comments
Changed a link on the website.  Tested by following the steps [here](https://cwiki.apache.org/confluence/display/METRON/Website+PR+Merge).

Once this is +1'd, I will push to master and asf-site appropriately.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [X] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by ottobackwards** [comment]
+1
Ran up, Docs Home [Learn More] takes you to https://metron.apache.org/current-book/index.html

**Comment by justinleet** [comment]
+1

@JonZeolla You should be good to go, if you're still going to be the one to push it through.

**Comment by nickwallen** [comment]
Bump.  @JonZeolla You are good to go here.  Let me know if you need help merging/deploying the changes.

**Comment by JonZeolla** [comment]
Sorry, I'm not at a computer right now but if anybody wants to push this before our release candidate is cut feel free

**Comment by mmiklavc** [comment]
I'm going to attempt to do this now - https://cwiki.apache.org/confluence/display/METRON/Website+PR+Merge. Link copied here so I can hopefully Google search for "how to update the apache metron website" more easily in the future :)

**Comment by JonZeolla** [comment]
Thanks @mmiklavc this totally fell off my plate

**Comment by mmiklavc** [comment]
Sigh, will push to the asf-site branch asap. My Jekyll config is broken.

**Comment by mmiklavc** [comment]
Yeesh, getting Jekyll to work was a pain. I re-installed Ruby from Homebrew and then had to install a number of packages to get it to compile. I've updated the wiki with notes on this as well.
```
brew install ruby
brew install autoconf
brew install automake
brew install libtool
```

**Pull request closed without merging**
