### PR TITLE
METRON-739 Create Local Profile Runner

### PR DESCRIPTION
**Pull request by nickwallen**
Troubleshooting issues when programming against a live stream of data can be difficult.  This is the primary reason that drove the creation of the REPL.  Similarly it would be useful to have a means to run a profile locally to troubleshoot, validate, or debug a profile.  Now you can, right in the REPL!

There are no external dependencies like Storm, Zookeeper or HBase, so you can develop your profiles completely disconnected from a live cluster.

Take it for a test spin.  

1.  Create your profiles.  For this example, In the editor copy/paste in the basic "Hello, World" profile.
    ```
    [Stellar]>>> conf := SHELL_EDIT()
    {
      "profiles": [
        {
          "profile": "hello-world",
          "onlyif":  "exists(ip_src_addr)",
          "foreach": "ip_src_addr",
          "init":    { "count": "0" },
          "update":  { "count": "count + 1" },
          "result":  "count"
        }
      ]
    }
    ```

1.  Initialize the Profiler.
    ```
    [Stellar]>>> profiler := PROFILER_INIT(conf)
    [Stellar]>>> profiler
    org.apache.metron.profiler.StandAloneProfiler@4f8ef473
    ```

1. Create some telemetry.   In the editor, copy/paste in the message JSON.
    ```
    [Stellar]>>> message := SHELL_EDIT()
    [Stellar]>>> message
    {
      "ip_src_addr": "10.0.0.1",
      "protocol": "HTTPS",
      "length": "10",
      "bytes_in": "234"
    }
    ```

1. Apply some telemetry messages to your profiles.
    ```
    [Stellar]>>> PROFILER_APPLY(message, profiler)
    org.apache.metron.profiler.StandAloneProfiler@4f8ef473

    [Stellar]>>> PROFILER_APPLY(message, profiler)
    org.apache.metron.profiler.StandAloneProfiler@4f8ef473

    [Stellar]>>> PROFILER_APPLY(message, profiler)
    org.apache.metron.profiler.StandAloneProfiler@4f8ef473
    ```

1. Flush the profiles, to see what it has calculated.  The result is a list of profile measurements.  Each value is a map containing detailed information about the profile measurements that were taken.
    ```
    [Stellar]>>> values := PROFILER_FLUSH(profiler)
    [Stellar]>>> values := PROFILER_FLUSH(profiler)
    [Stellar]>>> values
    [{period={duration=900000, period=1669628, start=1502665200000, end=1502666100000}, 
       profile=hello-world, groups=[], value=3, entity=10.0.0.1}]
    ```

I have added unit tests to cover all of the functionality, have tested the new Stellar functions in the REPL and have also completed a basic regression test for the Profiler itself.

## Pull Request Checklist
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

### CODE REVIEW

**Comment by cestella** [comment]
+1 by inspection.  I really like..well, pretty much ANYTHING that will help us debug is the tip-top in my book.  Great job @nickwallen

**Comment by ottobackwards** [comment]
@nickwallen , I think this would be great to put in the stellar stand alone shell, we should think of how to package it

**Comment by nickwallen** [comment]
It is just part of the Profiler Client lib.  Do we need to do anything special?

**Comment by ottobackwards** [comment]
Depends if it has dependencies.

**Pull request closed without merging**
