### PR TITLE
METRON-1726: Refactor PcapTopologyIntegrationTest

### PR DESCRIPTION
**Pull request by mmiklavc**
## Contributor Comments

https://issues.apache.org/jira/browse/METRON-1726

While working on issues with multi-threading and the pcap job I found it useful  to split up the monolithic pcap integration test into multiple tests with a separate setup and teardown method using @Before/AfterClass. Also fixed a regression/bug where the integration tests were writing out to the module root instead of `target`. Added back the file output path prefix along with defaults for the PcapCLI to write to the exec dir. Verification of this PR is checking that the tests appear correct and that the integration test passes.

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
n/a

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by mmiklavc** [comment]
I also ran this up in full dev to verify the pcap_query.sh CLI tool still works as expected.

`$METRON_HOME/bin/pcap_query.sh fixed -bp /apps/metron/pcap/input -df "yyyy-MM-dd-HH-mm" -st 2018-07-26-00-00 -et 2018-07-26-00-10 -rpf 500`

This output 1,518 records in 4 files, as expected (1518 / 500 = 3 R 18), in the user's current execution directory.

**Comment by justinleet** [comment]
+1 by inspection. This is great cleanup and makes it a lot easier to understand.

**Comment by merrimanr** [comment]
First off, I think this is definitely an improvement.  Putting the individual pcap queries into separate tests makes it easier to understand when things go wrong.

Would it make sense to move the pcap job/query related code to it's own test?  For me it makes more sense to have these tests in something like PcapJobIntegrationTest in metron-pcap.  It feels awkward for the pcap topology test to be in a setup or `@BeforeClass` method.  If I introduced a bug to the pcap topology code, which test would fail?

What do you think?

**Comment by mmiklavc** [comment]
> If I introduced a bug to the pcap topology code, which test would fail?

@merrimanr They would all fail because the writing to HDFS sequence files is incorrect. Prior to this refactoring, only 1 test would fail if a bug was introduced, and likely only the first test. This test is, and has been, a 2-phase broad e2e/acceptance test since the beginning. I didn't seek to change the fundamental operation of the test in this refactoring, but rather the organization of those units to make it easier to pinpoint specific failures. I definitely see your point about the setup, though this is still a definite improvement imo that moves us in the direction of being able to make additional refactorings should we so choose.

To answer your question more broadly, I've dealt with similar questions when testing DAO layers with databases. The approach I've used in the past that yielded optimal results without duplicating almost verbatim the code under test and test code itself was to use the code under test to read/write to the system and verify the expected values. To your point, however, this test is really 2 phases. 
1. `Raw pcap -> pcap topology processes it -> pcap as sequence files in HDFS`
2. `pcap as sequence files in HDFS -> pcap query filters it -> written to local  FS or HDFS`

Each of those can be tested independently, similar to what I described about DAO's. Even so, I think there's probably value in doing the full e2e as it's currently being done since we also have some spot-check unit tests around the individual components as well. We could spin up a test for the pcaptopology distinct from the querying, but there's definitely more work there. We would need
to:
1. write test code that correctly reads the sequence files from HDFS
2. choose additional test conditions for the topology validation (e.g. validating specific pcap values)
3. create a sequence file (probably just pulled from the output of the existing integration test after the topology creates the files in HDFS) for input to the query test.

All that being said, could I convince you that the improvements made by this PR are a good first step that moves us closer to additional improvements should we choose to make them?

**Comment by merrimanr** [comment]
That's fine with me.  Just wanted to point out that this test is still deficient because the pcap topology part really isn't tested that well and the only coverage we have right now is that it sets up other tests.  It also doesn't match the way we integration test other topologies or DAOs in Metron.  For example, our indexing integration test and search DAO integration tests are completely separate from each other.

Maybe that's something we improve in the future.  I imagine it will make sense to do it when (if) the pcap topology is updated.  +1

**Comment by mmiklavc** [comment]
@merrimanr - agreed. Pcap hasn't gotten nearly as much attention as the rest of the core infrastructure for quite some time. I created a Jira to track this - https://issues.apache.org/jira/browse/METRON-1729

**Pull request closed without merging**
