### PR TITLE
METRON-1142: Add Geo Hashing functions to stellar

### PR DESCRIPTION
**Pull request by cestella**
## Contributor Comments
Adding geo hashing functions to stellar would be a nice complement to the geo enrichment. Furthermore, geo hashing would provide binning and geographic based outlier analysis as a threat triage indicator.

Test plan imminent.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by cestella** [comment]
Please note: I have not spun this up in fulldev and used the functions in an enrichment or field transformation yet, so until I do, please refrain from committing (even if it gets a +1).  I'll be doing that evaluation on tuesday.

**Comment by cestella** [comment]
Ok, I tested this via a custom enrichment and custom parser field transformation and ensured that no adverse classpath issues happened.  I'm ready to call this ready for review.

Manual testing should follow the squid example:
* Add a new parser field transformation:
```
{
  "parserClassName": "org.apache.metron.parsers.GrokParser",
  "sensorTopic": "squid",
  "parserConfig": {
    "grokPath": "/patterns/squid",
    "patternLabel": "SQUID_DELIMITED",
    "timestampField": "timestamp"
  },
  "fieldTransformations" : [
    {
      "transformation" : "STELLAR"
    ,"output" : [ "full_hostname", "domain_without_subdomains", "geo_hash_parser"]
    ,"config" : {
      "full_hostname" : "URL_TO_HOST(url)"
      ,"domain_without_subdomains" : "DOMAIN_REMOVE_SUBDOMAINS(full_hostname)"
      ,"geo_hash_parser" : "GEOHASH_FROM_LOC(GEO_GET(ip_dst_addr))"
                }
    }
                           ]
}
```
* Add a new enrichment config:
```
{
  "enrichment" : {
    "fieldMap": {
      "stellar": {
       "config" : [
         "geo_hash_enrichment := GEOHASH_FROM_LOC(GEO_GET(ip_dst_addr))"
       ]
      }
    }
  },
  "threatIntel": { }
}
```
* Send squid data through and ensure that `geo_hash_enrichment` and `geo_hash_parser` yield a hash
* Test the various new stellar commands in the REPL (e.g. `GEOHASH_FROM_LOC(GEO_GET('172.168.2.3'))`

**Comment by justinleet** [comment]
This is a great submission, thanks for contributing!

Would you be able to show to how this works with the profiler and some of the SET stuff you added?  An example like the MAD outlier work would be great.

**Comment by cestella** [comment]
@justinleet that's fair.  I'll make an example and put it in the docs

**Comment by merrimanr** [comment]
I spun this up in full dev and it worked as advertised.  I was able to easily get the "geo_hash_parser" and "geo_hash_enrichment" fields correctly populated in ES.  I also tested all the new GEOHASH functions in the Stellar REPL and they all worked correctly.  

Also read through the documentation in the README.  The descriptions for the functions were clear and references were provided for further reading.  Awesome +1

**Comment by justinleet** [comment]
@cestella That absolutely makes sense.  Thanks a lot for adding it.

+1

**Pull request closed without merging**
