### PR TITLE
METRON-1078: Metron Indexing fails to stop during "Stop All Services"

### PR DESCRIPTION
**Pull request by dlyle65535**
## Contributor Comments
There is a corner-case where sometimes the Storm REST UI is stopped before the Metron topologies when 'STOP ALL' is selected from Ambari. This PR orders STORM_REST_API-STOP after the Metron topologies STOP.

To verify, spin up full-dev and select 'Stop All' from the UI. Verify that 'Storm UI Server Stop' comes after all the the Metron topologies.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [X] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [X] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [X] Have you included steps or a guide to how the change may be verified and tested manually?
- [X] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [N/A] Have you written or updated unit tests and or integration tests to verify your changes?
- [N/A] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [X] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by justinleet** [comment]
+1 by inspection

**Comment by dlyle65535** [comment]
Thanks @justinleet  - I'm going to hold off on this, @anandsubbu did some additional testing and it didn't actually solve the problem. :(

**Comment by justinleet** [comment]
@dlyle65535 Thanks for the update. That's pretty surprising, it seems like this should take care of it.  Ping me when there's some new info, and I'll hop back on this review.

**Comment by dlyle65535** [comment]
I'm starting to think the best approach would to assume the service is stopped if we can't get to the ui (which we kind of do anyway because of how status works).

Anybody absolutely hate that idea?

**Comment by anandsubbu** [comment]
Hi @dlyle65535 can it be a two step validation as follows: 
a) We first verify if we are able to hit the storm URL, if that fails -> then we mark the service as stopped. 
b) If the storm URL is up, and the service/topology (indexing, enrichment, parsers etc) is missing, then we mark the service as stopped.

**Comment by dlyle65535** [comment]
Oh yeah, thanks for clarifying, @anandsubbu - I'm not going to change the 'happy path' logic, so when the UI is up, it will work the way it did prior.

**Comment by anandsubbu** [comment]
Sounds great, @dlyle65535 !

**Comment by anandsubbu** [comment]
+1 (non-binding).
Validated the latest fix to be working great. Thank you, @dlyle65535 .

**Comment by dlyle65535** [comment]
@justinleet - this seems better. The change is to not error when the rest service is unavailable but use that as an indication that the topologies are stopped. The rest is code formatting because I've loaded the checkstyle template. :)

I'm not 100% happy with how this works, but wanted to get a quick-ish fix out while I got 100% happy. That work is described here: [METRON-1093](https://issues.apache.org/jira/browse/METRON-1093)

**Comment by dlyle65535** [comment]
@justinleet (or anyone really), I'd like to push this today, still good?

**Comment by justinleet** [comment]
I'm still +1.  Thanks for the contribution!

**Pull request closed without merging**
