### PR TITLE
METRON-1270 fix for warnings missing @return tag argument in metron-analytics/metron-profiler-common and metron-profiler-client

### PR DESCRIPTION
**Pull request by dbist**
## Contributor Comments
[WARNING] /Users/aervits/NetBeansProjects/METRON/metron/metron-analytics/metron-profiler-common/src/main/java/org/apache/metron/profiler/ProfileBuilder.java:66: warning - @return tag has no arguments.
[WARNING] /Users/aervits/NetBeansProjects/METRON/metron/metron-analytics/metron-profiler-common/src/main/java/org/apache/metron/profiler/hbase/ColumnBuilder.java:43: warning - @return tag has no arguments.
[WARNING] /Users/aervits/NetBeansProjects/METRON/metron/metron-analytics/metron-profiler-client/src/main/java/org/apache/metron/profiler/client/window/predicates/DateSpecifierPredicate.java:79: warning - @return tag has no arguments.
[WARNING] /Users/aervits/NetBeansProjects/METRON/metron/metron-analytics/metron-profiler-client/src/main/java/org/apache/metron/profiler/client/window/predicates/DayPredicates.java:109: warning - @return tag has no arguments.
[WARNING] /Users/aervits/NetBeansProjects/METRON/metron/metron-analytics/metron-profiler-client/src/main/java/org/apache/metron/profiler/client/window/predicates/HolidaysPredicate.java:82: warning - @return tag has no arguments.
[WARNING] /Users/aervits/NetBeansProjects/METRON/metron/metron-analytics/metron-profiler-client/src/main/java/org/apache/metron/profiler/client/window/Window.java:50: warning - @return tag has no arguments.
[WARNING] /Users/aervits/NetBeansProjects/METRON/metron/metron-analytics/metron-profiler-client/src/main/java/org/apache/metron/profiler/client/window/Window.java:63: warning - @return tag has no arguments.
[WARNING] /Users/aervits/NetBeansProjects/METRON/metron/metron-analytics/metron-profiler-client/src/main/java/org/apache/metron/profiler/client/window/Window.java:77: warning - @return tag has no arguments.
[WARNING] /Users/aervits/NetBeansProjects/METRON/metron/metron-analytics/metron-profiler-client/src/main/java/org/apache/metron/profiler/client/window/Window.java:91: warning - @return tag has no arguments.
[WARNING] /Users/aervits/NetBeansProjects/METRON/metron/metron-analytics/metron-profiler-client/src/main/java/org/apache/metron/profiler/client/window/Window.java:103: warning - @return tag has no arguments.
[WARNING] /Users/aervits/NetBeansProjects/METRON/metron/metron-analytics/metron-profiler-client/src/main/java/org/apache/metron/profiler/client/window/Window.java:115: warning - @return tag has no arguments.
[WARNING] /Users/aervits/NetBeansProjects/METRON/metron/metron-analytics/metron-profiler-client/src/main/java/org/apache/metron/profiler/client/window/Window.java:130: warning - @return tag has no arguments.
[WARNING] /Users/aervits/NetBeansProjects/METRON/metron/metron-analytics/metron-profiler-client/src/main/java/org/apache/metron/profiler/client/window/WindowProcessor.java:61: warning - @return tag has no arguments.
[WARNING] /Users/aervits/NetBeansProjects/METRON/metron/metron-analytics/metron-profiler-client/src/main/java/org/apache/metron/profiler/client/window/WindowProcessor.java:393: warning - @return tag has no arguments.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by cestella** [comment]
+1 by inspection

**Comment by justinleet** [comment]
@dbist Looks like this did get merged in (commit cf404f77d16daca5692f6197575bcc56c58fc2a9), but the PR is still open.  I don't see anything wrong with the commit.  Can you just close this PR after @cestella confirms we're in the clear (since I think he merged it)?

**Comment by dbist** [comment]
@justinleet thanks for looking into this, as soon as I get a confirmation, I'll close it.

**Comment by cestella** [comment]
It's merged.  The commit message looks acceptable too.  Not sure why it didn't automatically close.  Please close @dbist

**Pull request closed without merging**
