### PR TITLE
METRON-1204: UI does not time out after being idle, but stops functioning

### PR DESCRIPTION
**Pull request by merrimanr**
## Contributor Comments
This fix was verified running the Alerts UI against full dev.  To test this fix, spin up full dev and start the Alerts UI.  After logging into the Alerts UI, let it sit for a while until it idles out.  When this happens the UI should automatically navigate back to the login page.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by iraghumitra** [comment]
Tested, the UI redirects to log-in after the timeout. Should we show a message on the login page that session timeout happened ?.

**Comment by merrimanr** [comment]
That's not a bad idea.  It occurs to me that this issue may also exist with the Management UI and should be fixed there as well.  Stay tuned.

**Comment by merrimanr** [comment]
The latest commit adds a "Session Expired" message on the login page and also applies the fix to the Management UI.  You will notice the 2 files look identical between metron-alerts and metron-config.  We might want to investigate a way to share components in the future.

**Comment by ottobackwards** [comment]
This brings up the issue with having 'split' these uis.  They have common things that we shouldn't have to duplicate in each application.

**Comment by ottobackwards** [comment]
Our common components should be identified and moved to angular libraries as much as possible

**Comment by simonellistonball** [comment]
@ottobackwards should we push that as a follow up issue for now rather than expanding the scope of this PR?

**Comment by ottobackwards** [comment]
definitely

**Comment by iraghumitra** [comment]
+1 works as described ...

**Comment by ottobackwards** [comment]
[METRON-1221 Shared Metron Angular Components](https://issues.apache.org/jira/browse/METRON-1221)

**Comment by cestella** [comment]
+1 by inspection, great job @merrimanr

**Pull request closed without merging**
