### PR TITLE
METRON-1547: Solr Comment Fields

### PR DESCRIPTION
**Pull request by justinleet**
## Contributor Comments
Adding support for comments on Alerts in Solr.  Nested objects are absurdly painful, so this follows the ES expectation of these not needing to be queryable.

Solr doesn't have a great way to store these as-is, so they're stored as raw JSON, which is converted appropriately to ensure everything sees the same data as in the ES case.

The REST API has been adjusted to have add/remove comment calls, rather than just patching (since that won't work in Solr directly). However, index is required to avoid an error for Solr right now as a result of METRON-1585.  Once that is fixed, index will be optional.

There are currently a couple bugs that I would love some help with.

-  ~In ES, when you add a comment, it doesn't immediately show up on the comments list.  It looks like a findOne is fired off, but I assume ES isn't updated yet.  This doesn't appear to happen in Solr.~ Preexisting, related to UI's handling of new comments.
- ~When I hit delete on a comment in the UI (at least in Solr, unsure about ES), the comment is visually removed, but no remove request is fired off. I assume I have something misaligned, but I'm not sure what.~  Appears to be a browser issue, as it hasn't been reproducible and there's no code path difference between ES and Solr in this case.
- ~I patterned the optional index off of findOne, because it handles it a bit specially.  Delightfully, now I have an extra indexString field showing up in both findOne and the add remove comment.  There's some JsonGetter annotation thing I'm probably not using correctly.  This also happens in findOne currently, so it looks like it's probably a matter of getting the right fix and updating this to match.~ Index removed entirely, so this is moot.

To test,
This can be tested both via REST and the UI.  As noted above, at least right now the UI has more instability associated with it.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by cestella** [comment]
Did you specifically run this up in the UI backed by both solr and ES?

**Comment by justinleet** [comment]
@cestella I have, yes, but it'll need to happen again because there's an issue in ES, and issue in Solr, and a general issue.

The easiest way to go about it is generally to just spin up full dev, make sure it works in ES, swap over to Solr, make sure it works there.

**Comment by justinleet** [comment]
Having spun up #1040, it looks like the rest API indexString weirdness might be outside the scope of this PR, but I'll want to dig in a bit more before promising that.

**Comment by justinleet** [comment]
The ES not updating appears to be a preexisting issue, and I will file another bug.

**Comment by justinleet** [comment]
Comment not appearing created as https://issues.apache.org/jira/browse/METRON-1596

**Comment by justinleet** [comment]
I believe the Travis issues have been resolved by the commit yesterday reverting a log level change in testing.

**Comment by justinleet** [comment]
I haven't been able to reproduce Solr not making the delete call, and given that the code is the same between ES and Solr, I'm inclined to call it a browser issue.

I have spun this back up for both ES and Solr (with the caveat that the default "source.type.field" for ES is broken until master is merged all the way down.

At this point both work, after a minor fix that would result in an off by one error in the UI when deleting.  The UI is functional for both, although with the previously mentioned preexisting latency issue in updating, I do recommend closing and reopening the tab or things don't line up correctly.

At this point, the only issue is the indexString.

**Comment by justinleet** [comment]
@cestella For that indexString thing, we could do a couple things

- Leave it as-is for now, and fix both when they need to be.
- Figure out how to fix it and fix both here.
- Drop index from this query entirely. Given that we have source type, it should be sufficient.

I personally lean towards the last one, unless we either know a fix is imminent or it's easy to do.  Index is pretty extraneous given that we use source type everywhere and we can do a lookup on the source type  anyway.

Any preference?

**Comment by justinleet** [comment]
Kick Travis for cache bug

**Comment by merrimanr** [comment]
I agree with you @justinleet, we should drop the optional index from the query.

**Comment by cestella** [comment]
Yes, we should drop index from the query, agreed.

**Comment by justinleet** [comment]
Index removed from rest calls. I spun up full dev and confirmed both ES and Solr still work as expected, and that the calls do not pass along index anymore.  Feature branch merged in to resolve conflicts.

**Comment by cestella** [comment]
This looks good to me.  +1 by inspection

**Comment by justinleet** [comment]
Closing PR now that this is merged into the feature branch.

**Pull request closed without merging**
