### PR TITLE
METRON-811:  Enforce Maven Version in Top Level POM

### PR DESCRIPTION
**Pull request by zezutom**
## Contributor Comments
Enforcing Maven version >= 3.3.1 and Java 8

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### CODE REVIEW

**Comment by ottobackwards** [comment]
+1 by inspection, thanks for the contribution

**Comment by zezutom** [comment]
Thanks @ottobackwards. Anyone else, can I please get one more thumb up to get this PR over the line?

**Comment by ottobackwards** [comment]
I would have merged it already, but since the repo move out of incubator, our permissions are incorrect.  If nobody merges this, I'll land it when that is all taken are of.

**Comment by ottobackwards** [comment]
Thanks again for the contribution.  Please don't forget to take care of the Jira issue as well

**Pull request closed without merging**
