### PR TITLE
METRON-890: Intermittent unit test errors in shutting down Storm in memory component

### PR DESCRIPTION
**Pull request by cestella**
## Contributor Comments
Cross your fingers.  This may or may not work.  Please don't merge until this runs at least 10 times in a row in travis.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root incubating-metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by mmiklavc** [comment]
Is the belief here that killing the topologies first might allow full cluster shutdown and cleanup?

**Comment by cestella** [comment]
yep, that's the belief.  We're going to test it out here, in front of everyone. :)

**Comment by cestella** [comment]
*sigh* there it is again.  Stupid error.

**Comment by ottobackwards** [comment]
https://issues.apache.org/jira/browse/STORM-1730 ?

**Comment by cestella** [comment]
@ottobackwards oh man, that may be it.  I'll see what bumping the storm version does.

**Comment by cestella** [comment]
wait, no, we're using 1.0.3 already.

**Comment by ottobackwards** [comment]
I was looking at the <base.storm.version> which is 1.0.1

**Comment by ottobackwards** [comment]
Are we sure we are pulling in the version you think in the tests?

**Comment by cestella** [comment]
@ottobackwards I'm not even sure of my own name.

**Comment by ottobackwards** [comment]
What is the status of this PR?

**Comment by justinleet** [comment]
@cestella Any update on this?

**Comment by cestella** [comment]
sorry, the status of this PR is that none of my work seems to have accomplished anything here.  This is a placeholder for me to try other stuff.

**Comment by ottobackwards** [comment]
I don't think we should abandon this, there are some good fixes, would you accept PR's to your branch @cestella ?

**Pull request closed without merging**
