### PR TITLE
METRON-1030: Metron JDBC platform REST option should accept a blank value

### PR DESCRIPTION
**Pull request by merrimanr**
## Contributor Comments
Ambari should allow the metron_jdbc_platform option to be set to '' which it currently does not.  To verify, you should be able to spin up full dev, navigate to the REST tab and set that property to ''.  This is needed when configuring MySQL for Metron REST because this property must be '' and not 'mysql'.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by nickwallen** [comment]
When would a user want to set this property to an empty string?

**Comment by ottobackwards** [comment]
^^^^^^^ 
" This is needed when configuring MySQL for Metron REST because this property must be '' and not 'mysql'."

**Comment by merrimanr** [comment]
Spring provides a mechanism for running sql scripts for different databases on startup.  This is useful for initializing tables and such.  We provide 2 right now:  schema-h2.sql and schema-mysql.sql.  If you set this property to "h2" it will run the schema-h2.sql script automatically at startup.  Same goes for mysql.  It's possible that someone may want to use a different database and in that case they would want to set this to a blank string.

**Comment by ottobackwards** [comment]
That seems like a configuration that is rather confusing... 
Is there a way we can clarify that?

**Comment by lvets** [comment]
"This is needed when configuring MySQL for Metron REST because this property must be '' and not 'mysql'.". So this needs to be empty when you use mysql? I'm not following... :)

**Comment by merrimanr** [comment]
The comment "This is needed when configuring MySQL for Metron REST because this property must be" is actually incorrect now that I go back and look at it.  The schema-mysql.sql was initially incorrect because it was dropping the tables (MySQL doesn't support "create table if not exists") and recreating them every time.  

Fortunately Spring just ignores any errors thrown when running these scripts so the drop statements were just removed and creating a table that already existed is safely ignored.  This is just a convenience feature that keeps people from having to manually create database assets.

**Comment by merrimanr** [comment]
@ottobackwards it's in metron-rest README but I can expand it a little bit.

**Comment by ottobackwards** [comment]
It needs to be documented in the ambari ui, if it needs clarification.  The user in ambari isn't going to be using the readme

**Comment by ottobackwards** [comment]
this is a general problem I think

**Comment by merrimanr** [comment]
Here's the challenge with all this.  Maybe we can collaborate on the right approach.

The REST app requires a relational database and setting that up is a prerequisite, unless you want to use h2.  We can provide a way to automatically run a script and make this setup easier (we do that for h2 and mysql).  But it's likely that different orgs will want to use their own database and we probably don't want to try and maintain scripts for every possible database out there.

So what's the best approach?  Do we:

- Remove the convenience scripts and document setup as best we can (again providing the exact SQL statements for every database is not feasible).  In this case we would just remove this metron_jdbc_platform property from Ambari because it's not needed anymore.
- Limit our database support to a handful of databases and provide setup scripts for those?  In this case the metron_jdbc_platform could be a dropdown with the databases we support but users would be forced to use one of those.
- Keep it like it is now, provide a convenient way to initialize MySQL with other databases requiring manual setup.  In this case metron_jdbc_platform would accept h2, mysql, or empty meaning the user is responsible for setup.

Either way, the READMEs need to be improved which probably includes moving this database setup prerequisite to a higher level so that it's more obvious and providing more detail around manual setup.

**Comment by ottobackwards** [comment]
What do other HDP / ambari configured services do to support multiple databases? There are other services/projects we can look to for ideas

**Comment by ottobackwards** [comment]
Your fix, plus some clarity in the documentation / ambari label etc + some idea that we need to think of something long term would be good right?

**Comment by merrimanr** [comment]
Hive provides a list of supported databases:  https://cwiki.apache.org/confluence/display/Hive/AdminManual+MetastoreAdmin#AdminManualMetastoreAdmin-Local/EmbeddedMetastoreDatabase(Derby)

**Comment by nickwallen** [comment]
I don't think we need any major changes here.  Just something more descriptive.

> Keep it like it is now, provide a convenient way to initialize MySQL with other databases requiring manual setup. In this case metron_jdbc_platform would accept h2, mysql, or empty meaning the user is responsible for setup.

Yes, something along these lines (^^^)  is what I think we need.  

More specifically, I would suggest...
* Change the name of `metron_jdbc_platform` to something more descriptive.  Maybe `metron_rest_db_setup`, `metron_rest_ddl`, or something better?  

* Update the brief description in Ambari so that it reflects what you described above.

* Instead of an '' empty option let's call it something along the lines of 'Manual Database Setup'.

*  Updates to the README as you already suggested.

**Pull request closed without merging**
