### PR TITLE
METRON-1433: Only emit debugging timing fields in enrichment when debugging is turned on

### PR DESCRIPTION
**Pull request by cestella**
## Contributor Comments
Right now we always emit performance debugging fields in the split/join bolts.  We should only do that when debug logging is turned on for `org.apache.metron.enrichment.bolt`

Test:
Spin up full-dev and ensure that `adapter.*.begin.ts` and `adapter.*.end.ts` fields do not show up unless you set debug logging for `org.apache.metron.enrichment.bolt`

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by mmiklavc** [comment]
https://github.com/apache/metron/blob/master/metron-platform/metron-enrichment/src/main/java/org/apache/metron/enrichment/bolt/EnrichmentJoinBolt.java#L89

**Comment by cestella** [comment]
Whoops, missed one. Thanks @mmiklavc !

**Comment by mmiklavc** [comment]
+1, lgtm via inspection.

**Comment by simonellistonball** [comment]
Does anyone anticipate using (or even use) these fields to do things like monitor the flow and latency of their pipelines? I can imagine people wanting to build data quality monitoring reports on these fields, but would like to verify that assumption.

**Comment by mraliagha** [comment]
@simonellistonball We are using threat intel joiner timestamp currently. I am not sure indexing timestamp is added to the latest version or not, but we need the ES indexing one as well.

**Comment by cestella** [comment]
@mraliagha Well, if it's being used explicitly and on an on-going manner, then I'll remove this PR.  Do you think there's some value to being able to slice and dice in the global config the ability to turn on and off these by:
* type - threatintel vs enrichment
* adapter - stellar vs hbase vs geo
* frequency - kinda like a tracer, have 1 in k messages have them

Thoughts?

**Comment by mmiklavc** [comment]
Perhaps we can leverage parts of the performance logging code for this
purpose? The frequency/sampling bit was something I had wanted to add for
some time now.

https://github.com/apache/metron/pull/665

**Comment by mraliagha** [comment]
@cestella Definitely there will be value for having an ability to turn it on and off especially since you have already implemented that. However, won't be a sort of premature disk optimization? We are storing original_string and lots of other things that generally we may not really use them. Are those timestamp fields really troublemaker?

**Comment by cestella** [comment]
@mraliagha Nah, they're not a troublemaker.  I'm removing the PR since there's interest in them staying turned on by default.

**Pull request closed without merging**
