### PR TITLE
METRON-1587: Make collection utility work for HDP search

### PR DESCRIPTION
**Pull request by merrimanr**
## Contributor Comments
This PR improves the metron-solr create_collection.sh and delete_collection.sh scripts by switching to the Solr REST api instead of the Solr CLI tools.  This removes the requirement that Metron is colocated with a Solr client and makes the scripts easier to use with different versions and distributions.  Now only a zookeeper client is required for retrieving a Solr node address.

I refactored the Ambari code a little bit to match the rest of our MPack.  The solr_schema_install and 
solr_schema_delete functions were moved from indexing_master.py to indexing_commands.py because specific, low-level functions are generally in the *_commands.py scripts.  If this is confusing, doesn't make sense or makes reviewing this harder I'm happy to move them back.

I also added Kerberos support to these scripts.  The way I've done it creates a dependency on the HDP Search 3 Mpack but makes configuring Kerberos easy with no configuration required.  I would like to hear what the community thinks about this approach.  If we do decide to make this a dependency I can also remove the Solr zookeeper configuration setting in Ambari.  At that point using Solr is as easy as switching the "Random Access Search Engine" setting.

This has been tested in full dev with Kerberos enabled.  To test this PR, first install HDP Search 3 in full dev (https://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.6.4/bk_solr-search-installation/content/hdp-search30-install-mpack.html).  Kerberos can also be enabled now if desired.  Then in Ambari set "Solr Zookeeper Urls" in the "Index Settings" tab to `node1:2181/solr` and change the "Random Access Search Engine" setting in the Indexing tab to `Solr`.  Now stop the Metron Indexing component, then start it.  Note that restart does not trigger automatic Solr collection creation, matching how ES template loading works.  If we think adding collection creation on restart is desirable I can make that change.  Collections (bro, snort, metaalert, yaf, error) should now be present in Solr at node1:8983.

The scripts can also be tested independently from Ambari.  Just have to set a few environment variables first:
```
export ZOOKEEPER=node1:2181/solr
export SECURITY_ENABLED=true  # if Kerberos is enabled
```
Then the scripts should work when executed directly.  For example, to create the bro collection:
```
$METRON_HOME/bin/create_collection.sh bro
```
and to delete the bro collection:
```
$METRON_HOME/bin/delete_collection.sh bro
```

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by merrimanr** [comment]
As I update the documentation in the Solr README it occurs to me that we should consider installing HDP Search 3 in full dev with our Ansible scripts.  I have a feeling this will end up being the recommendation for using Solr with Metron.  The documentation in the README is a little outdated so I think it's worth figuring this out before I update it so it's accurate and complete.  Do you agree with that?  

Would you be ok doing it in this PR or would you prefer a separate PR?  If separate, it might be easier to update the documentation in the next PR because we'll have a clear installation path at that point (and the README will have to be rewritten anyways).  My preference would be to just do it here but I understand if you want to review them separately.  I guess my point is updating the documentation once makes more sense to me.

**Comment by justinleet** [comment]
@merrimanr There was a bit of discussion around this in #934, and it looks like the conclusion was that since HDP Search didn't support Solr 6 at the time, that we would hold off on it.  Given that HDP Search 3.0 does support Solr 6, it might be worth revisiting that discussion.

Personally, I'm okay with doing full dev off HDP Search (and having Ambari be able to setup config as needed automagically), as long as indexing can still be configured to work with a non HDP Solr instance.

Re: this ticket in particular, I'd do that as a separate PR.  Would we still want to use these scripts as part of that?  If we still want the scripts, I'd want them documented as part of this ticket (even if it's not in the perfect place).

There was also a hesitance on relying on any mpack (internal or external) explicitly in that discussion.  I'm unsure if that objection extended to a full dev or not.  @cestella Can you expand on your POV?

**Comment by merrimanr** [comment]
Ok I'll hold off on that for now and will also hold off on documenting anything Ambari related since it's going to depend on what we decide to do with HDP Search.  For this PR I will document standalone usage of the collection scripts.  Will that work?

**Comment by merrimanr** [comment]
The latest commit adds documentation on script usage to the Solr README.

**Comment by cestella** [comment]
I'm ok with full-dev off of HDP search, but that's a separate ticket than this IMO.

**Comment by merrimanr** [comment]
I created a Jira for adding HDP Search 3 to full dev.

**Comment by merrimanr** [comment]
@justinleet is the documentation I added comprehensive enough for this PR?

**Pull request closed without merging**
