### PR TITLE
METRON-1609 Elasticsearch settings in Ambari should not be required if Solr is the Indexer

### PR DESCRIPTION
**Pull request by nickwallen**
NOTE: This PR has been submitted against the Solr feature branch; not master.

## Description

  When a user deploys Metron with Solr, the Mpack requires that the user populate the Index Settings > Elasticsearch Hosts field to continue, even when deploying a Metron cluster that indexes to Solr and does not use Elasticsearch.

  * The Elasticsearch related properties under the Ambari 'Index settings' tab should only be required if Elasticsearch is chosen as the indexer.

  * The Solr related properties under the 'Index Settings' tab should only be required if Solr is chosen as the indexer.

## Changes

  * Removed the static validation checks for each of the parameters on the 'Index Settings' tab.  Static validation no longer works because validation depends on which Indexer the user has chosen.

  * Added a function `check_indexing_parameters` that validates the parameters based on the Indexer that has been chosen by the user on the "Indexing" tab.

  * The parameters are checked before any of the following actions:
      * Updating global properties, which occurs when Parsers, Enrichment, Indexing, Profiler, and REST are started/configured in Ambari.
      * Start/Configure indexing
      * Service Check
      * Install Elasticsearch Template
      * Delete Elasticsearch Template
      * Install Kibana Dashboard

  * When updating the global properties, we only add either Solr or Elasticsearch properties, but not both as before. 

  * It seems logical to move the 'Indexing Settings' parameters to the "Indexing"  tab, especially when it on this page where the user selects the Indexer; Elasticsearch or Solr.  I am not sure if there are other implications in doing this, so I did not do that as part of this PR.

## Testing

  1. Start the development environment.

  1. Validate that the Alerts UI is receiving alerts and that the Ambari 'Service Check' passes.

  **Missing Elasticsearch parameters should be caught**

  1. Stop the Metron services in Ambari.

  1. Using Ambari, delete (define a blank value for) the `metron-env/es_binary_port` parameter in Metron > Index Settings.

  1. Attempt to start each of the Metron services; Parsers, Enrichment, Indexing, Profiler, and REST.  These should fail with the following error message.

      ```
      resource_management.core.exceptions.Fail: Missing required indexing parameters(s): indexer=Elasticsearch, missing=['metron-env/es_binary_port']
      ```

  1. Attempt the Elasticsearch Template Install.  This should fail with the same error message.

  1. Attempt the Elasticsearch Template Delete.  This should fail with the same error message.

  1. Attempt the Kibana Dashboard Install.  This should fail with the same error message.

  **Missing Elasticsearch parameters should not impact Solr**

  1. Go to Metron > Indexing and change "Random Access Search Engine" to "Solr".

  1. Attempt to start the Indexing topology in Ambari.  This should succeed even though we are missing Elasticsearch parameters.

  **Ensure Elasticsearch parameters are defined in globals**

   1. Open up the REPL.

   1. Check for the Elasticsearch parameters in the globals.

      ```
      [Stellar]>>> CONFIG_GET("GLOBAL")
      {
        "es.clustername" : "metron",
        "es.ip" : "node1:9300",
        "es.date.format" : "yyyy.MM.dd.HH",
        ...
      }
      ```

  **Missing Solr parameters should be caught**

  1. Stop the Indexing topology in Ambari.

  1. Using Ambari, delete (define a blank value for) the `metron-env/solr_zookeeper_url` parameter in Metron > Index Settings.

  1. Attempt to start the Indexing topology in Ambari.  This should fail with the following error message.

      ```
      resource_management.core.exceptions.Fail: Missing required indexing parameters(s): indexer=Solr, missing=['metron-env/solr_zookeeper_url']
      ```
      
  **Ensure Solr parameters are defined in globals**

   1. Open up the REPL.

   1. Check for the Elasticsearch parameters in the globals.

      ```
      [Stellar]>>> CONFIG_GET("GLOBAL")
      {
        ...
        "solr.zookeeper" : "node1:9983",
        ...
      }
      ```

## Pull Request Checklist

- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### CODE REVIEW

**Comment by merrimanr** [comment]
I spun this up in full dev and the only issue I could find was that starting REST doesn't throw an error when a required parameter is missing.  The action succeeds but the app won't start and Ambari will still report it as down.  Other than that everything else worked.

**Comment by nickwallen** [comment]
Thanks @merrimanr.  Good catch.  I will fix that.

**Comment by justinleet** [comment]
@nickwallen Can you conflict this?

**Comment by nickwallen** [comment]
I deconflicted and pushed some changes to catch any problems when the REST service is started.  I am in the middle of testing those changes now.

**Comment by nickwallen** [comment]
This is ready to review again.  Cheers

**Comment by justinleet** [comment]
I'm +1 by inspection assuming @merrimanr is good.

**Comment by merrimanr** [comment]
I tested this in full dev and went through the testing instructions.  REST now throws an error on restart.  Thanks!  +1

**Comment by nickwallen** [comment]
This has been merged

**Pull request closed without merging**
