### PR TITLE
METRON-1328: Enhance platform-info.sh script to check if docker daemon is running 

### PR DESCRIPTION
**Pull request by anandsubbu**
## Contributor Comments
Run the `docker info` command along with checking the version. 

**Case A - Docker daemon running**
- Same as existing behavior.

**Case B - Docker daemon not running**
- The `docker info` command would error out with the following message:
```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by ottobackwards** [comment]
Thanks for the contribution!  This is a great idea.  If I may, I think this may be more clear:

```bash
if docker info 2>&1  | grep -q 'Cannot connect to the Docker daemon'
then
    echo "Docker daemon is not running"
else
    echo "Docker daemon is running"
 fi

```

**Comment by anandsubbu** [comment]
Hi @ottobackwards , thanks for your review.

I prefixed a 'WARNING' to the message text so it would catch the eye of the user. Also, I removed the else bit for docker running scenario, since this will fail for the case where docker is not installed at all. If I retain the else block, it would report saying 'Docker daemon is running'. 

So, in summary here are the cases:

1. Docker installed and running would print:
```bash
Docker version 1.12.1, build 23cf638, experimental
```
2. Docker installed, but not running would print:
```bash
Docker version 1.12.1, build 23cf638, experimental
WARNING: Docker daemon is not running
```
3. Docker not installed would print:
```bash
-bash: docker: command not found
```
Let me know if this looks okay.

**Comment by nickwallen** [comment]
+1 Thanks, Anand.  I tested with Docker daemon running, not running and not installed.  Worked as advertised.

**Comment by ottobackwards** [comment]
I would prefer it always say docker is running or not, but this will work.  
+1

**Comment by JonZeolla** [comment]
+1 tested on my mac with and without the daemon running.

**Pull request closed without merging**
