### PR TITLE
METRON-2009: Address Javadoc checkstyle issues in metron-common

### PR DESCRIPTION
**Pull request by justinleet**
## Contributor Comments
Added a whole lot of Javadoc and fixed stuff based on checkstyle. People should double check that it's correct, I took an admittedly fairly quick pass in the interest of improving it, but it's quite possible I overlooked things or made mistakes.  Some of the older stuff occasionally can be a little murky if you don't already know how it hooks together (which I definitely do not)

From metron-platform/metron-common, `mvn site site:stage-deploy site:deploy`. Open up `file:///tmp/metron/site/metron-platform/metron-common/checkstyle.html`.  There should be no JavaDoc warnings anymore.

Other than newlines and other minor formatting here and there, code shouldn't be touched. I wanted to avoid touching it as much as possible for a purely doc oriented set of changes.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by nickwallen** [comment]
Nice.  Thanks for putting in the hard work on this.  

Is there some way to turn on "hard checkstyle checks" just on metron-common, so we don't regress after we merge your changes in?

**Comment by justinleet** [comment]
I'm not sure. I'll take a look into it. It might be possible to flag specific the specific Javadoc checkstyle issues.  My concern on something like Javadoc would be that it potentially causes problems during development if it's always enforced.  If we could do it at the Travis level, that might be more appropriate.

**Comment by nickwallen** [comment]
> My concern on something like Javadoc would be that it potentially causes problems during development if it's always enforced. If we could do it at the Travis level, that might be more appropriate.

Oh, I thought that was your goal in originally adding the checkstyle stuff long ago?  If it is not enforced, then what good is it?  As we've seen, we're all very good at just ignoring it. :)  

And right now, I think it makes the situation worse because it is difficult to dig through the thousands of lines of warnings that it kicks out to find actual errors.

Isn't it pretty common to enforce checkstyle?

**Comment by justinleet** [comment]
We have a couple thousand violations just in metron-common alone. That's the main reason we don't enforce checkstyle.  That's one of the reasons I've been trying to at least kick out a couple PRs to start getting things cleaned up a bit (for example the charset PR, which actually does enforce things)

I've looked at seeing if we can use yetus or something to monitor changes in violations, rather than having to clean everything up, but I haven't put in enough time to get it working (and performant).

**Comment by justinleet** [comment]
Sidenote, most of the issues printed in the build, iirc are from error-prone.  That charset PR should help fix a lot of them. I believe most of the other error prone issues are raw types resulting from our use of json-simple.  There's a forked/upgraded version of json-simple that actually has types enforced, but some of the APIs change, so there's a fairly widespread code changes that touches a ton of stuff involved in doing that.

Re: enforcing checkstyle, I'd like to see if we can get individual violations banned on a per project basis at CI time.  Completely cleaning out our project of violations is going to be a substantial effort, either on a module by module basis or on a violation basis (or some combination of the two).

**Comment by nickwallen** [comment]
> We have a couple thousand violations just in metron-common alone. That's the main reason we don't enforce checkstyle. That's one of the reasons I've been trying to at least kick out a couple PRs to start getting things cleaned up a bit.

Ok, that makes sense.  I thought you were saying we will never enforce checkstyle checks like javadoc.  You're just saying "hey, we have a lot of work to do before we can enforce checkstyle across the board."   And that makes sense to me.

I was just curious if there was a way to enforce specific checks, per project.  But if you think that is not possible, that is fine. This PR certainly moves us in the right direction as-is.

**Comment by ottobackwards** [comment]
+1.  If we find any errors or improvements in the Javadoc, I suggest those be opened as jiras post this.

**Comment by nickwallen** [comment]
+1 Your doc changes look great.  You deserve a service medal.

**Comment by justinleet** [comment]
@nickwallen Are you okay with this in general (minus any changes that anyone requests of course) ? I'll create a follow-on Jira for being able to enforce individual violations on a per module basis if that works for you?

**Comment by justinleet** [comment]
Nevermind, you commented right before I did

**Pull request closed without merging**
