### PR TITLE
METRON-1690: Add more context to PcapJob JobStatus

### PR DESCRIPTION
**Pull request by mmiklavc**
## Contributor Comments

https://issues.apache.org/jira/browse/METRON-1690

Adds more context for failure scenarios to the JobStatus object returned by PcapJob. Removes duplication between Timer status updates and the getStatus call.

## Pull Request Checklist

Follow test plan from the following: https://github.com/apache/metron/pull/1109

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by justinleet** [comment]
+1, thanks for the contribution!

**Comment by merrimanr** [comment]
Actually I did find a problem.  When I submit a normal query where results are included in the time range, I get:
```
{
  "jobId": "",
  "jobStatus": "SUBMITTED",
  "description": "Job submitted",
  "percentComplete": 0,
  "pageTotal": 0
}
```
The jobId is missing.

**Comment by mmiklavc** [comment]
@merrimanr - I added "SUBMITTED" as a new separate status where the MR job has been submitted but we potentially don't have a job ID yet. Let me check the API on whether we can return that reliably or not.

**Comment by mmiklavc** [comment]
@merrimanr - heads up this has been updated to address the jobId missing on submission

**Comment by merrimanr** [comment]
I tested this again and it looks like the job id is present now.  +1

**Comment by mmiklavc** [comment]
Merged into feature branch.

**Pull request closed without merging**
