### PR TITLE
METRON-1243: Add a REST endpoint which allows us to get a list of all indices

### PR DESCRIPTION
**Pull request by cestella**
## Contributor Comments
The Alerts UI currently hard-codes the set of indices. It would be preferred to use the REST API to get a list of index names for a given writer (e.g. elasticsearch, solr, hdfs).
This functions in the following way:
* If an index config exists, then the index name will be returned. If unspecified, then the sensor name is used
* If a parser exists and an index does NOT exist, then it will be included.
* If the writer is disabled in the index config, then it will NOT be included.

Test plan in the comments!

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by ottobackwards** [comment]
Can you assign METRON-1216 to you and link / complete it as necessary?  Thanks!

**Comment by ottobackwards** [comment]
Nevermind, I was mobile before, took care of it

**Comment by cestella** [comment]
# Testing Plan

## Basic Functionality
* Ensure you can retrieve the elasticsearch indices set up in Metron and
  they include the default sensors:
  `curl -u user:password -X GET --header 'Accept: application/json' 'http://node1:8082/api/v1/sensor/indexing/config/list/indices/elasticsearch'`
  * You should see the default sensors:
    * websphere
    * jsonMap
    * squid
    * error
    * snort
    * asa
    * bro
    * yaf
* Delete the `websphere` parser
  `curl -u user:password -X DELETE --header 'Accept: */*' 'http://node1:8082/api/v1/sensor/parser/config/websphere'`
* Delete the `websphere` index config
  `curl -u user:password -X DELETE --header 'Accept: */*' 'http://node1:8082/api/v1/sensor/indexing/config/websphere'`
* Run the list indices command and ensure that websphere does not appear
  `curl -u user:password -X GET --header 'Accept: application/json' 'http://node1:8082/api/v1/sensor/indexing/config/list/indices/elasticsearch'`
## Add a new parser
* Add the websphere parser back
```
curl -u user:password -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
  "parserClassName":"org.apache.metron.parsers.websphere.GrokWebSphereParser",
  "sensorTopic":"websphere",
  "parserConfig":
  {
    "grokPath":"/patterns/websphere",
    "patternLabel":"WEBSPHERE",
    "timestampField":"timestamp_string",
    "dateFormat":"yyyy MMM dd HH:mm:ss"
  }
}' 'http://node1:8082/api/v1/sensor/parser/config'
```
* Run the list indices command and ensure that `websphere` does appear
  `curl -u user:password -X GET --header 'Accept: application/json' 'http://node1:8082/api/v1/sensor/indexing/config/list/indices/elasticsearch'`

## Rename index name
* Add the `websphere` indexing config back, renaming the index for elasticsearch to `webspheroid`
```
curl -u user:password -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
  "hdfs" : {
    "index": "websphere",
    "batchSize": 5,
    "enabled" : true
  },
  "elasticsearch" : {
    "index": "webspheroid",
    "batchSize": 5,
    "enabled" : true
  },
  "solr" : {
    "index": "websphere",
    "batchSize": 5,
    "enabled" : true
  }
}' 'http://node1:8082/api/v1/sensor/indexing/config/websphere'
```
* Run the list indices command and ensure that `websphere` does not appear, but `webspheroid` does
  `curl -u user:password -X GET --header 'Accept: application/json' 'http://node1:8082/api/v1/sensor/indexing/config/list/indices/elasticsearch'`
* Run the list indices command for the hdfs writer and ensure that `websphere` exists and not `webspheroid`
  `curl -u user:password -X GET --header 'Accept: application/json' 'http://node1:8082/api/v1/sensor/indexing/config/list/indices/hdfs'`

**Comment by merrimanr** [comment]
Just tested this and worked as expected.  The only question I have is whether the "error" index should be included since it is used to store errors and not alerts.  I can't think of a case where you would include "error" in a search along with other indices.  I'm looking at this from the perspective of the Alerts UI so I don't necessarily think it needs to be done in this PR but it will need to be filtered out at some point.

**Comment by cestella** [comment]
So, I did think about this and decided to include it.  It is an index in ES with data.  If we think it should be filtered, I can certainly do so, but thought the decision really should be best done downstream (I expect sometimes you want to include it and sometimes you don't).

**Comment by cestella** [comment]
and by downstream, I mean in whatever UI we have.

**Comment by merrimanr** [comment]
Makes sense to me.  +1 Nice job

**Pull request closed without merging**
