### PR TITLE
METRON-949 Change from error to warning message for Metron REST in Ambari service_advisor

### PR DESCRIPTION
**Pull request by anandsubbu**
## Contributor Comments
Reduced the level to WARN in service_advisor.py.

Steps to validate:
- Fire up Ambari wizard after installing Mpack
- In the Assign Masters page, Metron REST should now show a 'WARN' icon instead of 'ERROR'

I have not carried out the full suite of tests, since this is a minor rename from ERROR to WARN.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [NA] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [NA] Have you ensured that the full suite of tests and checks have been executed in the root incubating-metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [NA] Have you written or updated unit tests and or integration tests to verify your changes?
- [NA] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [NA] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [NA] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by anandsubbu** [comment]
Could I get some love for this PR? :-)

**Comment by merrimanr** [comment]
Why was this changed to WARN?

**Comment by anandsubbu** [comment]
@merrimanr , this is because of the following reason:

In the "Assign Masters" page of the Ambari deployment wizard, there is a check for the Metron REST host to have storm supervisor installed. This is currently displayed as an Error message.

However in the flow of the wizard, the storm supervisor selection can only be done in the subsequent screen. So, this message should be changed into a Warning instead.

This will be inline with the check that we have for Metron Parsers host co-location with Storm supervisor, which is also a WARN.  See [here](https://github.com/apache/metron/blob/master/metron-deployment/packaging/ambari/metron-mpack/src/main/resources/common-services/METRON/CURRENT/service_advisor.py#L65).

**Comment by merrimanr** [comment]
Why is the [Kafka Broker check for parsers host](https://github.com/apache/metron/blob/master/metron-deployment/packaging/ambari/metron-mpack/src/main/resources/common-services/METRON/CURRENT/service_advisor.py#L61) set to ERROR?  What's the difference between checking for a Kafka Broker and checking for a Storm Supervisor?

**Comment by anandsubbu** [comment]
Unlike the Storm supervisor or the Clients (which is the next screen away), you can select/add Kafka brokers in the same Assign Masters page, which is why it is set as ERROR.

**Comment by anandsubbu** [comment]
Please see METRON-592 where we fixed the Kafka broker and Enrichment checks.

**Comment by anandsubbu** [comment]
@merrimanr, let me know if the above comment answers your question.

**Comment by merrimanr** [comment]
Makes sense @anandsubbu.  +1

**Comment by anandsubbu** [comment]
Thank you, @merrimanr . Can you please help merge this pull request?

**Pull request closed without merging**
