### PR TITLE
METRON-2318: Merge master into feature branch

### PR DESCRIPTION
**Pull request by sardell**
## Contributor Comments
Link to ASF Jira ticket: https://issues.apache.org/jira/browse/METRON-2318

The feature branch is once again out-of-date, and there are many conflicts to resolve. For this reason, a pull request is being opened to keep resolved conflicts separate from other work in the branch.

Note: Due to the way we had to cherry-pick our work, way more commits are appearing than are actually part of this set of work. The only commit belonging to this PR is the last commit in this change set.

### Testing
Everything should build and test fine, as it does on master. I was able to build full-dev and run tests via the mvn command in the checklist.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

- [ ] Have you ensured that any documentation diagrams have been updated, along with their source files, using [draw.io](https://www.draw.io/)? See [Metron Development Guidelines](https://cwiki.apache.org/confluence/display/METRON/Development+Guidelines) for instructions.

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by mmiklavc** [comment]
How are we getting commits showing as going back to May? The last merge happened Oct 9 - https://github.com/apache/metron/pull/1507

**Comment by sardell** [comment]
@mmiklavc Unfortunately, this is how every PR has been when merging master into the feature branch. For example: https://github.com/apache/metron/pull/1507/commits

As you can see, a lot of the commits listed here were merged into the feature branch already. Unfortunately, the squash merge does not retain the history in the feature branch. It gets even more complicated by the fact that we had to cherry-pick & re-write commits to accommodate the Apache attribution standards of the project.

If there were no conflicts, I would merge master into the feature and push directly upstream, but since there are so many conflicts I followed previous examples of feature branch work like this one here by @nickwallen (which also contains a lot of commits unrelated to the PR): https://github.com/apache/metron/pull/1502

**Comment by mmiklavc** [comment]
@sardell - I think I see what's going on here. I don't think I realized the previous merge was squashed. That's more an issue of community documentation than anything else - I don't think we have a page with our past learnings put together yet. In other FB's, I don't think we squashed the merge commit. It makes the git history more jagged, but also preserves history so we don't have to deal with gnarly redundant merges (like we see in the history for this PR). When we're confident in this merge, I think we should commit it to the FB as a normal merge commit, not squashed.

**Comment by sardell** [comment]
@mmiklavc That makes sense. I would use the `prepare-commit.sh` script out of habit, which would squash things. When the time comes, I'll commit as a normal merge commit.

**Comment by mmiklavc** [comment]
+1 by inspection pending your manual smoke test checks out. Considering the squashing in the past couple merge commits, we'll want to do a broader system check before we merge the FB as well as another git diff.

**Comment by sardell** [comment]
@mmiklavc This branch is now merged into the feature branch (ie. no squash commit). Thanks again for taking the time to explain the process to me. Looking forward to documenting these steps to help future contributors.

**Pull request merged**
