### PR TITLE
METRON-1577: Solr searches don't include the index of the result

### PR DESCRIPTION
**Pull request by merrimanr**
## Contributor Comments
This PR adds a document's index or collection to search results.  Previously when using Solr, the index field would always be null.  An indexSupplier was recently added to the AccessConfig and is now used in the Solr Daos to get the index from a sensor type and populate that field.  

I had to fix a bug in the IndexingCacheUtil class where the index field was being retrieved directly instead of for a specific writer.  I think this wasn't caught before because sensor types always equal index in the various index configs and this class returns sensor type by default.  I added a unit test for this class that should cover the different cases and verify that this does default to sensor type.

I also adjusted unit and integration tests to accommodate this change.  Testing in full dev is still pending and I should have that done today.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by cestella** [comment]
When we test this in full-dev, we need to make sure we try it out with:
* a sensor with index named different than the sensor name (e.g. send bro to foobar)
* a sensor with index config not specified in zookeeper

**Comment by merrimanr** [comment]
I tested this in full dev and found a small bug where the index.writer.name wasn't being passed to the REST app on startup.  The latest commit fixes that. 

I was able to verify the 2 cases @cestella mentioned.  For the first test I update the bro sensor config:
```
{
  "hdfs": {
    "index": "bro",
    "batchSize": 5,
    "enabled": true
  },
  "elasticsearch": {
    "index": "bro",
    "batchSize": 5,
    "enabled": true
  },
  "solr": {
    "index": "bro_2",
    "batchSize": 5,
    "enabled": true
  }
}
```
A search result now looks like:
```
{
  "id": "44fc8391-474d-4b8e-a375-52f748735b2f",
  "source": {
    ...
    "source.type": "bro"
  },
  "score": 0,
  "index": "bro_2"
}
```
For the next test I deleted the snort indexing config.  A search result against that collection now looks like:
```
{
  "id": "71a0ca1a-b3c2-414b-9fde-c31e8dd5544a",
  "source": {
    ...
    "source.type": "snort"
  },
  "score": 0,
  "index": "snort"
}
```

**Comment by cestella** [comment]
@merrimanr I submitted a [PR](https://github.com/merrimanr/incubator-metron/pull/36) against your PR, which I think will clean up the rest of the loose ends around missing indexes and catches a small bug in the indexing supplier.  Merge if you think that makes sense.

**Comment by cestella** [comment]
+1 by inspection

**Pull request closed without merging**
