### PR TITLE
METRON-1130 - Updating Amazon EC2 README.md

### PR DESCRIPTION
**Pull request by as22323**
## Contributor Comments
Hello, This is my first time submitting a pull request to the Apache Metron project. Feel free to point me in the right direction if I am not doing this right. 

The suggested updates were based on my experience of using ClearOS 7.4.0 (Distro is based on CentOS) as a host to install Apache Metron 0.4.0 in Amazon EC2. 

FYI:
Here is a list of versions that seemed break/cause issues when installing:
-Ansible 2.0.0.2
-Maven 3.0.5

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?
<AS22323: README.md from branch "Metron_0.4.0"[METRON-979] and the latest greatest of today  [METRON-979] were the same>

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by nickwallen** [comment]
Hi @as22323  - Thanks for submitting a PR.  You want the "base branch" of this PR to be "master".  Right now it is set to "apache:Metron_0.4.0".

**Comment by as22323** [comment]
Thanks. I have updated to "master". 
According to the Metron Dev Guidelines I am suppose to assign the METRON JIRA ticket to my self. I'm not sure how to do that.

**Comment by cestella** [comment]
Hm, yeah, I can't seem to assign it to you either @as22323

**Comment by ottobackwards** [comment]
what is the status of this PR?

**Comment by as22323** [comment]
Closing PR.

**Pull request closed without merging**
