### PR TITLE
METRON-1553 Validate JIRA Script Error

### PR DESCRIPTION
**Pull request by nickwallen**
The `dev-utilities/release-utils/validate-jira-for-release` script has a minor error when run.

```
$ ./validate-jira-for-release --version="0.4.3" --start=tags/apache-metron-0.4.2-release
Cloning into 'metron-0.4.3'...
remote: Counting objects: 39871, done.
remote: Compressing objects: 100% (13140/13140), done.
remote: Total 39871 (delta 18078), reused 37550 (delta 17019)
Receiving objects: 100% (39871/39871), 54.34 MiB | 6.23 MiB/s, done.
Resolving deltas: 100% (18078/18078), done.
fatal: Not a git repository (or any of the parent directories): .git
Fetching origin
JIRA STATUS FIX VERSION ASSIGNEE FIX
METRON-1549 Done Michael Miklavcic https://issues.apache.org/jira/browse/METRON-1549
METRON-1541 To Do Unassigned https://issues.apache.org/jira/browse/METRON-1541
...
```

To test this, just run the same command as shown above and ensure no error messages are shown.

## Pull Request Checklist

- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### CODE REVIEW

**Comment by justinleet** [comment]
The only thing I'd add is maybe porting over the "directory already exists" from one of the other scripts (e.g. either delete and repull, or go into the directory and pull).

Right now clone gives an error that the dir already exists, which I believe means it won't pull or update, so I'm not sure if things get handled appropriately lining up source to jira.

Having said that, this is really helpful to have fixed, thanks!

**Comment by nickwallen** [comment]
> @justinleet: The only thing I'd add is maybe porting over the "directory already exists" from one of the other scripts...

Yes, that would be nice.   Did you previous PR already have that?  If it did, let's just go with your PR.

Otherwise, would it make to do that as a follow-on or do you see that necessarily fitting in here?

**Comment by justinleet** [comment]
I didn't handle it particularly cleanly (I just nuked the dir if the user was okay with it), and the way you're doing the other stuff is cleaner anyway, so I'm fine with using this. 

If we wanted to be more clean about it, we could have the directory just pull if it already exists.

What I did was 
```
# warn the user if the working directory exists
if [ -d "$WORK" ]; then
  read -p "  directory exists [$WORK].  overwrite existing repo? [yN] " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
  fi
fi

rm -rf "$WORK/metron-$VERSION"
git clone $REPO "$WORK/metron-$VERSION"
```

I'm pretty neutral on if we want to take care of that here, or we want to leave it as follow on.  I'll leave that up to you.

+1

**Comment by nickwallen** [comment]
@justinleet I added a check as you suggested.  There are some whitespace changes (tabs to spaces) that my editor slipped in there.  I can clean those out if it is a distraction.

**Comment by justinleet** [comment]
Thanks @nickwallen, this is a good fix. +1

**Pull request closed without merging**
