### PR TITLE
METRON-2064: Metron REST API overwriting global.json values

### PR DESCRIPTION
**Pull request by merrimanr**
## Contributor Comments
This PR fixes a documentation bug around enabling Solr.  These fields are defined in Ambari so any changes outside of Ambari will be overwritten whenever a Metron component is restarted.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by nickwallen** [comment]
+1 Thanks for the fix @merrimanr

**Comment by mmiklavc** [comment]
@merrimanr, @nickwallen - one small addition before we merge this - can you update the global config doc please? The properties are missing there as well - https://github.com/apache/metron/tree/master/metron-platform/metron-common#global-configuration

**Comment by merrimanr** [comment]
@mmiklavc I just checked and I do see these fields defined in https://github.com/apache/metron/tree/master/metron-platform/metron-common#global-configuration.

**Comment by mmiklavc** [comment]
We're missing this property https://issues.apache.org/jira/browse/METRON-2064?focusedCommentId=16811579&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16811579 as pointed out by @MohanDV. 

I created this Jira with the intention of:
1. Fixing any possible issues with global.json patching, and
2. Correcting any misunderstanding of what properties are managed by Ambari

There are a number of other properties that have been added to the global config but not updated in the documentation, e.g.
solr.commitPerBatch

I'd like to see the outstanding properties addressed before closing this ticket, and I am happy to take over on this work if it helps, but I don't want to create another ticket to track it.

**Comment by merrimanr** [comment]
Sure no problem.  I think we need to make a list of all the outstanding properties that need to be documented.  I will work on compiling this list and will update the PR.  If anyone else has a good idea of which properties we need to include, feel free to add a comment.

**Comment by merrimanr** [comment]
The latest commit adds these additional properties to the metron-common README:
- Properties managed by Ambari (defined [here](https://github.com/apache/metron/blob/master/metron-deployment/packaging/ambari/metron-mpack/src/main/resources/common-services/METRON/CURRENT/package/scripts/metron_service.py#L90))
- Solr properties

That should cover the properties discussed in this PR so far.  What else are we missing?

**Comment by mmiklavc** [comment]
lgtm @merrimanr, thanks for adding this. +1

**Pull request closed without merging**
