### PR TITLE
METRON-1444: Add Ubuntu Repositories for Elasticsearch to the Mpack

### PR DESCRIPTION
**Pull request by mmiklavc**
## Contributor Comments

https://issues.apache.org/jira/browse/METRON-1444

As of Ambari 2.6.0, the Ubuntu repoinfo.xml translation into an apt-get sources file has been fixed. See https://github.com/apache/ambari/commit/f8b29df9685b443d4a5c06c6e1725e4428c95b49#diff-6f26c26ed59462200d018c5e1e71e773

This PR updates Ambari from 2.5.2 to 2.6.1.0 in order to get the fix for Ubuntu repoinfo.xml processing.

**Test**

Spin up the Ubuntu full dev env. ES and Kibana should be installed without issue. Spot check that you see data populating the dashboard when you open Kibana.

Also check that centos full dev still works as expected with the Ambari upgrade.

## Pull Request Checklist

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

### CODE REVIEW

**Comment by ottobackwards** [comment]
Shouldn't the title of this PR be "Update ambari from 2.5.x to 2.6.x"?  That seems the bigger thing :)

**Comment by nickwallen** [comment]
I disagree @ottobackwards .  The core problem is that there is a bug in Ambari that prevented us from loading the repos directly in the Mpack.  The only way to fix this is to upgrade.

This looks solid. I'm going to spin this up now.  Glad this one will soon be in the rearview mirror.

**Comment by ottobackwards** [comment]
I'll add 2 smileys next time, to help get my point across.  I would have expected a response more along the lines of:
"Upgrading Ambari to the 2.6 release line shows little risk when I looked at it, as Ambari seems to be fairly important to Metron."

**Comment by nickwallen** [comment]
+1 Ran this up on Ubuntu.  Thanks for the fix!

**Comment by mmiklavc** [comment]
@ottobackwards, @nickwallen is correct. This was originally intended to deal with the Ubuntu repo problem, which ended up being fixed via the Ambari upgrade (due to fixes they made to how they handle repoinfo processing)

fyi, I have successfully spun this up on both Centos and Ubuntu and see data in the Kibana dashboard.

**Pull request closed without merging**
