### PR TITLE
METRON-2100: Update developer documentation for full dev management UI parser aggregation feature gap

### PR DESCRIPTION
**Pull request by mmiklavc**
https://issues.apache.org/jira/browse/METRON-2100

This is a pure documentation update/clarification per the discussion here - https://lists.apache.org/thread.html/37e9727ae3053fb30dad86cca99f7c2bafea23bc4a5e36c6cf9cf10f@%3Cdev.metron.apache.org%3E. Testing in full dev should not be required.

**Testing**

Review the proposed documentation change. You can run through the site-book build if desired. I verified the change looks correct and that the added links to parser aggregation work as expected.

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- n/a Have you written or updated unit tests and or integration tests to verify your changes?
- n/a If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- n/a Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

### CODE REVIEW

**Comment by ottobackwards** [comment]
This doesn't help them if they actually want to _work_ with the full_dev.
- how do you get rid of the aggregations?
- what happens if you try to edit the configuration for bro, will a second bro topology be started?
- how would you work with the sensors in the aggregation?

I asked in the discuss and got no answer to the *real* number of issues with usability around this issue, for people that are using full_dev to test or doc or do things other than what our committers think developers do and can deal with.

**Comment by mmiklavc** [comment]
Ok, I see what you're saying here. I can add that context as well. Any thoughts on where that should go? This doc is currently organized like an Edwin Starr song, so I'm on the fence about adding it here.

**Comment by ottobackwards** [comment]
I would guess both in the README here and the release notes

**Comment by mmiklavc** [comment]
@ottobackwards - I don't believe we have a formal "release notes" document other than a pure listing of all the Jiras in the release. I'm assuming you're referring to Upgrading.md, so I'll make a note there that points at the comments I've added. New commit coming in just a bit - just need to validate the site-book looks good.

**Comment by mmiklavc** [comment]
@ottobackwards Take another spin through this when you have a moment. I did some acceptance test-like tinkering in full_dev to see what the implications are for everything from lifecycle management to configuration management. This should be much better now. I've added a note and links to Upgrading.md, and I also made another correction - my enrichment refactoring PR was incorrectly listed under "0.7.1 - 0.7.2." That has been moved to the appropriate heading "0.7.0 - 0.7.1."

**Comment by ottobackwards** [comment]
+1, thanks

**Pull request closed without merging**
