### PR TITLE
METRON-1397  Support for JSON Path and complex documents in JSONMapParser

### PR DESCRIPTION
**Pull request by ottobackwards**
It would be useful for implementors to have the ability to ingest more complex documents without having to stand up a NiFi node/cluster.

This PR adds support for splitting multiple messages from a single message by way of using JSON Path statements to select the List element in the document.

Since the parse() interface already returns a List<JSONObject> the scope of this change is in the parser.

Example:

```json
    {
    "foo" :
    [
    { "name" : "foo1", "value" : "bar", "number" : 1.0 },
    { "name" : "foo2", "value" : "baz", "number" : 2.0 }
    ]
    }
 ```

with JSON Path statement "$.foo" will result in two messages emitted from the parser

```json
 { "name" : "foo1", "value" : "bar", "number" : 1.0 }
```

```json
{ "name" : "foo2", "value" : "baz", "number" : 2.0 }
```
Support in the configuration for a new configuration parameter: jsonpQuery has been added.
An example of the new configuration:

```json
{
  "parserClassName":"org.apache.metron.parsers.json.JSONMapParser",
  "sensorTopic":"jsonMapQuery",
  "parserConfig": {"jsonpQuery":"$.foo"}
}
```

In order to integration test both with and without the query present, a new jsonMapQuery parser configuration has been added, with test data.

##Testing
- tests should run
- deployment should work

> NOTE.  There are three commits here to start
1. The basic functionality
2. checkstyle fixes
3. small fix found later

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

### CODE REVIEW

**Comment by mmiklavc** [comment]
This seems cool. Can you provide some guidance via some examples or just a link to what's possible syntax/query-wise with JSON path queries in the docs for this?

**Comment by ottobackwards** [comment]
http://goessner.net/articles/JsonPath/
https://github.com/json-path/JsonPath
http://jsonpath.herokuapp.com

https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html

**Comment by ottobackwards** [comment]
yeah, you said in the docs, will do

**Comment by ottobackwards** [comment]
Just a note on parser docs, part of the mythical 777 is support for per parser readme, that would be nice here.

**Comment by simonellistonball** [comment]
@ottobackwards Really want that myth to be a reality... as soon as we can get the config overwrite problem solved... but this really isn't the ticket to discuss that on :)

I'm kinda keen on this parser looking at things like CloudTrail logs and such like which appear with merged JSON right now. The other thing that I think this would link up to is the idea that's been floating around about chaining parsers. This parser could well be a split parser, which then routes to other parsers with different transformations for example depending on the message, but again, that's deep future and should probably be on a discuss thread about parser chaining.

**Comment by simonellistonball** [comment]
And in more topical an relevant points... we're introducing a net new dependency here... Do we need to also update the NOTICES file (and the dependencies_with_url.csv list)?

**Comment by ottobackwards** [comment]
Um, it is updated.

**Comment by simonellistonball** [comment]
My bad: the dependencies file is updated, but not the NOTICES.

**Comment by simonellistonball** [comment]
And in fairness to you, we don't do the NOTICES properly for anything else either I see. That's probably a separate scope.

**Comment by cestella** [comment]
I love this, sorry I didn't review it sooner @ottobackwards +1 by inspection.  This is great.

**Pull request closed without merging**
