### PR TITLE
Metron-1083: Add filters using faceted search capabilities of metron-rest-api

### PR DESCRIPTION
**Pull request by iraghumitra**
## Contributor Comments
This PR is on top of [METRON-1068](https://github.com/apache/metron/pull/699). This PR adds faceted search capabilities to the UI.

- A new facet pane is added to GUI that groups data based on the following 'hard coded' fields ('source:type', 'ip_src_addr', 'ip_dst_addr', 'host', 'enrichments:geo:ip_dst_addr:country') 
- The count of unique values for each facet and count for individual values in facet are displayed in the UI 
- User can expand collapse each facet
- Clicking on one of the facet value would add the facet value to search and the facet values are updated in accordance with the new search criteria
- All the functionality in the search like hover delete, clear is intact
- If you rename a column using the rename option in column settings the renamed field name would appear in the Facet filter as well as in the search

image

image

## Testing

If you run the metron-alerts UI using any one of the ways mentioned below you would notice that UI has a new facet pane on the left of the page and all the functionality described above should be working.

There are through E2E tests written to test the faceted seacrh functionality.

**Dev:** From 'metron/metron-interface/metron-alerts' you can run `./scripts/start-dev.sh` and open the GUI at `localhost:4200`

**E2E:** From 'metron/metron-interface/metron-alerts' you can run `./scripts/start-server-for-e2e.sh` in one terminal and run `npm run e2e` in a seperate terminal

**Deployment:** Follow the steps mentioned in [Readme](https://github.com/apache/metron/tree/master/metron-interface/metron-alerts#installing-on-an-existing-cluster) and you should see a login page and data being fetched from rest-api's

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by james-sirota** [comment]
I can't comment on implementation details, but + 1 on the capabilities.  I spun it up and every time I click on a facet I see my search results filtered by that facet.  I can do that on a number of fields and have them filter by a combination of facets.  When I remove the facet from search the facet filter is removed and the query is reset.  Works as expected. +1 from me

**Comment by nickwallen** [comment]
Hi @iraghumitra - The commit history looks a little odd.  There are commits going back a few months and seem unrelated to this PR.  Can you double check that the code that you have submitted is what you expect?

**Comment by iraghumitra** [comment]
@nickwallen The PR was raised before I go to know about the concept of squash commits mind me for my ignorance. I had to make few modifications since a PR that was raised after this got in to master before. I tested the PR again looks good feel free to review.

**Comment by nickwallen** [comment]
> A new facet pane is added to GUI that groups data based on the following 'hard coded' fields ('source:type', 'ip_src_addr', 'ip_dst_addr', 'host', 'enrichments:geo:ip_dst_addr:country')

I am assuming that we will "un-hard code" the list of fields included in the facet panel in a future PR.  But even as a first pass, I don't think 'host' should be included.  This is not a common field.  It is only present in a subset of Bro records.  Most records do not have this field.

**Comment by nickwallen** [comment]
Everything else is looking really good though, @iraghumitra .  
* The way that the UI it is laid out is obvious and intuitive.
* I manually tested the faceted functionality and all the counts and fields sync'd as I would expect.   
* It looks like you have solid e2e tests and I was able to run them successfully.

**Comment by iraghumitra** [comment]
@nickwallen The idea is to have the Facets and Groups in sync with the table column names at the same time avoid the ones that might be too discrete. I will have a discussion around what's the best way to find out the discrete fields, I don't want a blacklist of fields that would be hardcoded again.
Can you raise a jira on my name I would pick it as a follow-up if you feel it can be picked in a follow-up PR?

**Comment by james-sirota** [comment]
Ok, I opened 

https://issues.apache.org/jira/browse/METRON-1250

as a follow on jira for this

**Comment by nickwallen** [comment]
+1 That works for me.  This is a good first pass.  Taking care of METRON-1250 would totally side step a probably contentious (and unwinnable) debate as to what the most important fields are. :)

**Comment by iraghumitra** [comment]
@nickwallen we can make the fields configurable too.

**Pull request closed without merging**
