### PR TITLE
METRON-1932: Update ES and Kibana to 5.6.14

### PR DESCRIPTION
**Pull request by JonZeolla**
## Contributor Comments
This upgrades ES and Kibana from 5.6.2 to 5.6.14, specifically with the goal to fix [this](https://github.com/elastic/elasticsearch/pull/27069) which was backported to 5.6.4.  Thanks to the great work in #1242 this was a piece of cake.  I spun it up and poked around in ES, Kibana, the Alerts UI, and did some digging through logs looking for errors or warnings.  Found some things that can be improved for the future, but don't appear to have been introduced by this PR.

### Testing
Spin up full-dev, ensure ES/Kibana is healthy/working as expected, and is version 5.6.14.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by JonZeolla** [comment]
This should be ready for review.

**Comment by ottobackwards** [comment]
are you going to update the metron-contrib/docker ?

**Comment by JonZeolla** [comment]
I didn't expect that would need an update.  In looking at it, they've released a 5.6.14 which I'm going to move things to.

**Comment by JonZeolla** [comment]
@ottobackwards Is [this](https://github.com/apache/metron/pull/1296/commits/b47d1808785a12a78d94739c69ec66fde508bb8e#diff-efd719d636b235ed83e2ded856682e93R17) what you would expect to upgrade docker?  I'll have to spin it up later.  Looks like that got missed in the initial move to 5.6.

**Comment by ottobackwards** [comment]
actually, I don't think you should touch it. although there might be a follow on jira for that stuff

**Comment by JonZeolla** [comment]
Why not?  It makes sense to me that it should be kept in sync.

**Comment by merrimanr** [comment]
I thought we put that in contrib so that it didn't need to be maintained?

**Comment by ottobackwards** [comment]
I'm sorry, I've made a mess of this.  I should not have mentioned it.  @merrimanr is right, this should be done in a separate pr

**Comment by JonZeolla** [comment]
Since it appears ES was broken in docker I'm not going to look to fix it here.

**Comment by mmiklavc** [comment]
@JonZeolla, thanks for doing this! We had hoped that moving to the ES client would make updating patch releases a lot easier, and that appears to be the case. For a minor patch version, I'd expect no breaking changes, but before I +1 this can you double check that nothing has changed around X-Pack and SSL connections? Any other upgrade notes we should be aware of? Also, can you update your notes in the initial comment 5.6.13 -> 5.6.14 to avoid confusion?

**Comment by JonZeolla** [comment]
Valid point.  Updated my initial comment, can look at X-Pack and SSL.

**Comment by JonZeolla** [comment]
Do we have any previously used testing steps for X-Pack and/or SSL?  I briefly looked at [METRON-939](https://github.com/apache/metron/pull/840) but didn't see anything.  I can try to use some of the guidance from [here](https://github.com/apache/metron/blob/master/metron-platform/metron-elasticsearch/README.md) if that's the best documentation.

**Comment by mmiklavc** [comment]
@JonZeolla - have a look at this - https://github.com/apache/metron/pull/1242#issuecomment-436802370

**Comment by JonZeolla** [comment]
Aha perfect thank you I knew I read that somewhere in a PR before.

**Comment by JonZeolla** [comment]
First off, huge ty @mmiklavc for those great testing steps.  It worked flawlessly, and I was able to confirm that both X-Pack and SSL work as expected as of HEAD of this branch.

**Comment by mmiklavc** [comment]
That's great @JonZeolla! Thanks for taking the extra time to verify this - I had originally anticipated just some release doc review on the ES side, but this is wonderful. Big +1 from me.

We've touched on this before, but this work is yet another reason we might want to take another look at dev docs for testing in the project. Right now we hunt and search across old PR's for test scripts and that's probably time better spent simply keeping a core set of test instructions under version control.

**Comment by JonZeolla** [comment]
Thanks.  Yeah, I started with the release doc review, which is what made me think this would be so straightforward.  =)

You are totally right.  Is there a JIRA for that sort of follow-on?  I really think that your steps should be captured somewhere for the future.

**Comment by mmiklavc** [comment]
I don't think so, but ping @ottobackwards as he's suggested we do this in the past. I've accidentally  duplicated his Jiras before, so it's worth asking haha :-)

**Comment by JonZeolla** [comment]
I opened METRON-1943 to address my comment earlier:
> Found some things that can be improved for the future, but don't appear to have been introduced by this PR.

**Comment by ottobackwards** [comment]
I have not opened a jira on this, you may want to have a discuss.
If we can figure out a way to flag things that should be added to it, and how to maintain it, then some repo of testing steps would be great.

Unless we want to write a testing framework, where you can do common things and plugin scripts to validate etc etc

**Pull request closed without merging**
