### PR TITLE
METRON-959 Trivial documentation formatting bugs

### PR DESCRIPTION
**Pull request by JonZeolla**
## Contributor Comments
I noticed there were some bugs rendering README.md files in GitHub MD, so I did a quick search by cloning the metron repo and then running `egrep -r "^#{1,6}[a-zA-Z]" * | grep -i README.md | cut -f1 -d\: | sort -u` from the metron folder and then manually adding spaces between `#` symbols and the header text where necessary.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by justinleet** [comment]
+1 by inspection.  Good catch, and thanks for fixing it.

**Comment by JonZeolla** [comment]
Thanks.  Just waiting on [INFRA-14159](https://issues.apache.org/jira/browse/INFRA-14159) so I can commit it.

**Comment by cestella** [comment]
@JonZeolla Just let me know if you want me to commit in the meantime.  I'd be happy to, but I'll understand if you want to use this to test whether your commit rights are restored.

**Comment by JonZeolla** [comment]
Planning to use this as a test commit once the permissions are fixed, unless that doesn't happen until after 0.4.0 (unlikely).  In that case I would want this in the release.

**Comment by JonZeolla** [comment]
@cestella (or another PMC member) can you take a look at [INFRA_14159](https://issues.apache.org/jira/browse/INFRA-14159)?  It is waiting on user right now.

**Comment by justinleet** [comment]
@JonZeolla Sounds like Otto got his commit working.  You should be good to try this now.

**Pull request closed without merging**
