### PR TITLE
METRON-2292: [UI] Manual query can't be saved on the Alerts UI

### PR DESCRIPTION
**Pull request by ruffle1986**
## Contributor Comments

Link to the ASF Jira: https://issues.apache.org/jira/browse/METRON-2292

The problem
=========

When users switch to manual query mode and type something in the search field, it doesn't count when they want to save the search. However the manual mode is visible on the screen, it always saves the recent query built by the query builder (if it's anything else but '*')

Testing
=====

1. Go to the alerts-ui
2. Switch to manual query mode
3. Type something in the search field
4. Click on the search button
5. Click on the "Save" search button (floppy disc icon on the right of the magnifier)
6. Open the saved searches pane (Click the button on the left of the search field)
7. Choose your saved search from the list
8. Please try to choose it from the recent searches list to make sure it works properly.

Repeat the same with a saved search built by the query builder. The app should turn into the proper filtering mode based on the filtering mode of the saved search.

It's worth to refresh the browser between steps randomly just to make sure it's persisted properly. Since we only store saved and recent searches in the local storages, I recommend you to flush it before testing.

====

During testing, I've realised that the recent search means recent saved search. It was a bit confusing for the first time. I expected the recent search to be my latest search and not the recent saved search from the list below. Anyone else who thinks it might be confusing and misleading for the users?

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [X] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [X] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [X] Have you included steps or a guide to how the change may be verified and tested manually?
- [X] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [X] Have you written or updated unit tests and or integration tests to verify your changes?
- [X] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [X] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [X] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

- [X] Have you ensured that any documentation diagrams have been updated, along with their source files, using [draw.io](https://www.draw.io/)? See [Metron Development Guidelines](https://cwiki.apache.org/confluence/display/METRON/Development+Guidelines) for instructions.

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by ruffle1986** [comment]
Closing and re-opening due to one dependency is unavailable to download at the time

**Comment by sardell** [comment]
I just tested this and I noticed that after I make and save a few searches where I edit the timestamp out of the search, it will be added back into the saved search.

**Comment by ruffle1986** [comment]
Nice catch! I'll take a look at it.

**Comment by sardell** [comment]
Any update on the status of this work?

**Comment by ruffle1986** [comment]
No, not yet. Sorry for the delay. This is going to be the first thing I'll check once I'm done with my other tasks.

**Comment by ruffle1986** [comment]
According to the gif, I tried to reproduce the problem by following the exact same steps. Could you please provide a detailed guide on what you did so I can do the same? I might have missed something.

This is what I did:

1. Get all the alerts of he last 1 year.
2. Click on the `source:type` cell to filter by a certain type like bro.
3. Switch to manual query and save the search
4. Then change the query in manual query mode and remove the time related stuff
5. Click on the magnifier to apply the query
6. Save the new query with a different name
7. Load the previous query (the time should be there)
8. Load the recently saved query (the time is not there as expected)

**Comment by sardell** [comment]
@ruffle1986 I'm actually unable to reproduce the bug now. I think I might've been using an old VM build before to test, though I'm not sure if that would've caused the issue. Either way, I've tested this pretty thoroughly and I cannot reproduce the bug.

With that said, I'm giving this a +1. Thanks for the contribution, @ruffle1986!

**Pull request closed without merging**
