### PR TITLE
METRON-2275 Solr Indexing Topology Fails to Start on Secure Cluster with HDP 3.1

### PR DESCRIPTION
**Pull request by nickwallen**
The Solr indexing topology will fail to start on a secure, kerberized cluster with HDP 3.1.  The following error will occur when starting the topology.  The topology will not start successfully.

```
+-         Apache Storm        -+
+-  data FLow User eXperience  -+
Version: 1.0.1
Parsing file: /usr/hcp/1.9.2.0-94/metron/flux/indexing/random_access/remote.yaml
797  [main] INFO  o.a.s.f.p.FluxParser - loading YAML from input stream...
804  [main] INFO  o.a.s.f.p.FluxParser - Performing property substitution.
808  [main] INFO  o.a.s.f.p.FluxParser - Not performing environment variable substitution.
1118 [main] INFO  o.a.c.f.i.CuratorFrameworkImpl - Starting
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.storm.flux.FluxBuilder.buildObject(FluxBuilder.java:294)
	at org.apache.storm.flux.FluxBuilder.buildComponents(FluxBuilder.java:342)
	at org.apache.storm.flux.FluxBuilder.buildTopology(FluxBuilder.java:75)
	at org.apache.storm.flux.Flux.runCli(Flux.java:153)
	at org.apache.storm.flux.Flux.main(Flux.java:98)
Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
	at org.apache.curator.framework.listen.ListenerContainer.addListener(ListenerContainer.java:40)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:246)
	at org.apache.metron.common.utils.KafkaUtils.getBrokersFromZookeeper(KafkaUtils.java:49)
	at org.apache.metron.storm.kafka.flux.SimpleStormKafkaBuilder.getBootstrapServers(SimpleStormKafkaBuilder.java:246)
	at org.apache.metron.storm.kafka.flux.SimpleStormKafkaBuilder.<init>(SimpleStormKafkaBuilder.java:203)
	at org.apache.metron.storm.kafka.flux.SimpleStormKafkaBuilder.<init>(SimpleStormKafkaBuilder.java:187)
	... 9 more
```

### Root Cause

When kerberized, Storm adds a bunch of jars from `$STORM_HOME/contrib/storm-autocreds` to the classpath. These jars are not added to the classpath when the cluster is unsecure (no kerberos).

The exception here occurs because...
* We build against Guava 17.0 and Curator 2.7.1.
* Curator 2.7.1 calls a Guava method MoreExecutors.sameThreadExecutor.
* The method [MoreExecutors.sameThreadExecutor](https://guava.dev/releases/20.0/api/docs/com/google/common/util/concurrent/MoreExecutors.html#sameThreadExecutor--) was removed in Guava 21.0
* At runtime Storm is providing Guava 28.0 (which does not include MoreExecutors.sameThreadExecutor) from `/usr/hdp/current/storm-client/contrib/storm-autocreds/guava-28.0-jre.jar` 

### The Fix

We need to relocate Guava 17.0 in the Solr uber jar.  This will allow Curator 2.7.1 to use Guava 17.0.  This is the same relocation that occurs for the Elasticsearch indexing topology.

### Testing

1. Spin-up the `centos7` development environment.
1. Kerberize the cluster.
1. Attempt to start the Indexing topologies.  The topologies should start successfully.

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### CODE REVIEW

**Comment by tigerquoll** [comment]
Ok, I could not get his one to work.
Spun up a centos7 cluster (1 hour 45 minutes for a deployment :( ) and then kerberised it ok.
The followed the instructions at:
  https://metron.apache.org/current-book/metron-platform/metron-solr/index.html
Which should have got solr up and running, unfortunately when restarted Metron in Ambari, I started getting:
```


Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/common-services/METRON/0.7.2/package/scripts/enrichment_master.py", line 118, in <module>
    Enrichment().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/common-services/METRON/0.7.2/package/scripts/enrichment_master.py", line 110, in restart
    from params import params
  File "/var/lib/ambari-agent/cache/common-services/METRON/0.7.2/package/scripts/params/params.py", line 27, in <module>
    from params_linux import *
  File "/var/lib/ambari-agent/cache/common-services/METRON/0.7.2/package/scripts/params/params_linux.py", line 266, in <module>
    hostname_lowercase = config['hostname'].lower()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/config_dictionary.py", line 73, in __getattr__
    raise Fail("Configuration parameter '" + self.name + "' was not found in configurations dictionary!")
resource_management.core.exceptions.Fail: Configuration parameter 'hostname' was not found in configurations dictionary!
``` 
I could use the metron solr collection scripts to create the various collections, and I could then log into http://node1:8983/solr/#/bro/query and see that the solr collections were created.


And then I realised I could curl to the SOLR admin interface without any kerberos ticket 
```
klist
klist: No credentials cache found (filename: /tmp/krb5cc_0)
set | grep SECURITY
KAFKA_SECURITY_PROTOCOL=SASL_PLAINTEXT
SECURITY_ENABLED=false./create_collection.sh yaf
  adding: schema.xml (deflated 80%)
  adding: solrconfig.xml (deflated 72%)
{
  "responseHeader":{
    "status":0,
    "QTime":16}}
{
  "responseHeader":{
    "status":0,
    "QTime":2731},
  "success":{
    "10.0.2.15:7574_solr":{
      "responseHeader":{
        "status":0,
        "QTime":1368},
      "core":"yaf_shard1_replica_n1"}}}
```
Is SOLR supposed to be kerberised as well?  
I dug up some instructions at https://docs.cloudera.com/HDPDocuments/HDP3/HDP-3.1.4/managing-auditing/content/configuring_solrcloud_for_kerberos.html
Is this supposed to be for lucidwork's distrubtion or well this work for the (I assume) apache solr-cloud distro?

**Comment by anandsubbu** [comment]
+1

Ran this up on a multi node kerberized solr cluster and I could see the `random_indexing_topology` comes up fine. Thanks for the fix @nickwallen !

These are the step I followed:
* Deployed a 10-node cluster w/solr as indexing server
* Followed the kerberization steps
* At the end of the kerberization steps (during start services), verified that the `start_solr_topology.sh` script is able to bring up the RA Indexing topology fine.

**Comment by mmiklavc** [comment]
> +1
> 
> Ran this up on a multi node kerberized solr cluster and I could see the `random_indexing_topology` comes up fine. Thanks for the fix @nickwallen !
> 
> These are the step I followed:
> 
> * Deployed a 10-node cluster w/solr as indexing server
> * Followed the kerberization steps
> * At the end of the kerberization steps (during start services), verified that the `start_solr_topology.sh` script is able to bring up the RA Indexing topology fine.

@anandsubbu Did you deviate in any way from the steps that @tigerquoll followed? Would be good to get an understanding of any gaps we potentially have here.

**Comment by tigerquoll** [comment]
I suspect its probably due to me still being on the learning curve when it comes to Metron and kerberos.  @anandsubbu , where you following https://metron.apache.org/current-book/metron-platform/metron-solr/index.html to turn SOLR on, ir were you using some other means?   Is there an option to install Metron from scratch with SOLR?   Does a multi-node Metron install by default use lucid works SOLR?

**Comment by anandsubbu** [comment]
@mmiklavc and @tigerquoll -

I typically follow these steps on a multi-node cluster
* Spin up bare metal VMs
* Install ambari-server
* Install metron mpack
* Install the HDP-Search 4.0.0 mpack from [this link](http://public-repo-1.hortonworks.com/HDP-SOLR/hdp-solr-ambari-mp/solr-service-mpack-4.0.0.tar.gz)
* Deploy the cluster

Once the cluster comes up, I follow the kerberization steps here - https://github.com/apache/metron/blob/master/metron-deployment/Kerberos-ambari-setup.md

**Comment by nickwallen** [comment]
This has been merged to the feature branch.

**Pull request closed without merging**
