### PR TITLE
METRON-975: Normalize logging and switch to common idiom with SLF4J

### PR DESCRIPTION
**Pull request by mmiklavc**
https://issues.apache.org/jira/browse/METRON-975

We currently have a mixture of logging approaches scattered throughout the codebase. Log4j, slf4j, and commons logging. In addition, there are some deprecated idioms being used to declare loggers (post-jdk 7) and format strings within the logging statements.

This PR handles converting and normalizing Metron's logging over to slf4j in all major metron-platform areas except for tests. It also converts logging in metron-analytics, with the exception of MaaS which is currently leveraging commons logging.

I've made a few types of changes (change varietals?).
1. Normalized logger factory calls to the following `LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());` , per https://www.slf4j.org/faq.html#declaration_pattern
2. Removed `LOG.isDebugEnabled()` in instances where the SLF4J parameterized messages is a better option, e.g. `logger.debug("The entry is {}.", entry);`. I have *not* changed this implementation in instances where more costly operations are being done, like string concatenation derived from parsing or serializing json into string form, per https://www.slf4j.org/faq.html#logging_performance
3. Replaced string concatenation with parameterized nessages. I did this even when a formatted string precedes an exception/throwable. The javadoc wasn't immediately clear about this, but as of SLF4J 1.6 a final exception argument will be treated as an exception rather than as an object for use during parameterization - https://www.slf4j.org/faq.html#paramException

Testing instructions to follow. For starters, I've compared the number of lines in the Travis build output before and after this change and see no notable difference in total number of lines.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root incubating-metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by mmiklavc** [comment]
Kick Travis - rest api test failure

**Comment by ottobackwards** [comment]
I will give you real imaginary money to rebase this onto METRON-777 so I don't have to port ;)

**Comment by simonellistonball** [comment]
Is it worth us getting this in sooner rather than later, before we get too many other bits of logging that will need to be backported?

**Comment by mmiklavc** [comment]
I would love to get this in

**Comment by merrimanr** [comment]
@mmiklavc looks like there are some merge conflicts.  If you don't mind resolving those I will get this reviewed.

**Comment by mmiklavc** [comment]
@merrimanr Conflicts resolved

**Comment by cestella** [comment]
I'm damned confused about these test errors.  This PR didn't seem to touch anything near the test and I haven't seen that test (which is a mock test) fail intermittently before.  I'd love a debrief after you figure out the unit test failure cause, @mmiklavc .  If it's test weirdness or something intermittent, let's make sure we capture a JIRA about it.

**Comment by nickwallen** [comment]
I saw this same test failure yesterday on another PR.  I opened a [METRON-1048](https://issues.apache.org/jira/browse/METRON-1048) for it.

**Comment by mmiklavc** [comment]
Any comments on this? I've been merging/resolving conflicts with master as they come in.

**Comment by simonellistonball** [comment]
+1 (non-binding) the sooner we get this in the better. It has performance benefits, and the longer we wait the more work and trouble it will create. No reason not to get it done, lots to get it in.

**Comment by cestella** [comment]
+1 by inspection

**Pull request closed without merging**
