### PR TITLE
METRON-1714 Create RPM Packaging for the Batch Profiler [Feature Branch]

### PR DESCRIPTION
**Pull request by nickwallen**
This creates an RPM that makes it simple to install the Batch Profiler.  There are now two separate RPM packages created for the Profiler; one for Storm and another for Spark.
* metron-profiler-storm-*.rpm
* metron-profiler-spark-*.rpm

This also ensures that the MPack installs both of these Profiler packages.

This is a pull request against the `METRON-1699-create-batch-profiler` feature branch.

This is dependent on the following PRs .  By filtering on the last commit, this PR can be reviewed before the others are reviewed and merged.
- [x] #1161

### Testing

1. Spin-up the development environment.

1. Validate the development environment by ensuring alerts are visible within the Alerts UI and that the Metron Service Check in Ambari passes.

1. Take a look at what was installed by each package.

    ```
    [root@localhost ~]# rpm -ql metron-profiler-storm
    /usr/metron
    /usr/metron/0.5.1
    /usr/metron/0.5.1/bin
    /usr/metron/0.5.1/bin/start_profiler_topology.sh
    /usr/metron/0.5.1/config
    /usr/metron/0.5.1/config/profiler.properties
    /usr/metron/0.5.1/flux
    /usr/metron/0.5.1/flux/profiler
    /usr/metron/0.5.1/flux/profiler/remote.yaml
    /usr/metron/0.5.1/lib
    /usr/metron/0.5.1/lib/metron-profiler-0.5.1-uber.jar
    ```
    ```
    [root@localhost ~]# rpm -ql metron-profiler-spark
    /usr/metron
    /usr/metron/0.5.1
    /usr/metron/0.5.1/bin
    /usr/metron/0.5.1/bin/start_batch_profiler.sh
    /usr/metron/0.5.1/config
    /usr/metron/0.5.1/config/batch-profiler.properties
    /usr/metron/0.5.1/lib
    /usr/metron/0.5.1/lib/metron-profiler-spark-0.5.1.jar
    ```

1. Ensure that the following files have been installed in `${METRON_HOME}`.
    ```
    /usr/metron/
    └── 0.5.1
        ├── bin
        │   ├── start_batch_profiler.sh
        │   └── start_profiler_topology.sh
        ├── config
        │   ├── batch-profiler.properties
        │   └── profiler.properties
        ├── flux
        │   └── profiler
        │       └── remote.yaml
        └── lib
            ├── metron-profiler-0.5.1-uber.jar
            └── metron-profiler-spark-0.5.1.jar
    ```

## Pull Request Checklist

- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### CODE REVIEW

**Comment by nickwallen** [comment]
FYI - I need to create a README for the Spark Profiler project.  I'll add that to this PR before it goes in.

**Comment by nickwallen** [comment]
I added a README for the Spark Profiler in this PR.

**Comment by merrimanr** [comment]
I tested this in full dev and everything is as expected.  The README is clear to me too.  +1

**Comment by nickwallen** [comment]
Many thanks for the review. This PR has been merged into the feature branch.

**Pull request closed without merging**
