### PR TITLE
METRON-1590: validate-jira-for-release script checks out project into current directory not workdir

### PR DESCRIPTION
**Pull request by justinleet**
## Contributor Comments
Altering the script a bit. Note that you can't just `git clone git clone $REPO "$WORKDIR/metron-$VERSION"` while leaving `WORKDIR="~/tmp"` because git clone is always relative to current dir and you'll end up with a new folder named `~`.

Also moved `WORKDIR` down to where it's actually used for clarity, since it gets created earlier than it needs to be.

To test, run `./validate-jira-for-release --version=0.5.0 --start=tags/apache-metron-0.4.2-release` and ensure that the checkout occurs in `~/tmp/metron-0.5.0`, rather than in current directory.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron 

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by justinleet** [comment]
I added the `rm` anyway, since I made another adjustment.  Before it was trying to checkout before cd.

**Comment by ottobackwards** [comment]
I would say that the scripts we have wrt PR's and RC's and Commits should be as common as possible.  With the goal that they actually share code down the line.  So I would say that the configuration and preference persistence for working dir and other options be done as nick's scripts

**Comment by justinleet** [comment]
@ottobackwards I think the main thing there would be to do something like this instead of the rm:

https://github.com/apache/metron/blob/master/dev-utilities/committer-utils/prepare-commit#L100-L107

I wouldn't really want to do a whole lot more refactoring in this PR, just because it's a pretty minor change.

**Comment by nickwallen** [comment]
Does this also fix the issue from #1013?  Or is #1013 also needed?  I'm good either way.

**Comment by justinleet** [comment]
@nickwallen Either seems to hit the main issues, I'll close this one out and we can go with #1013.  I'll also close this ticket as a dupe.

**Pull request closed without merging**
