### PR TITLE
METRON-1883 Updated org.apache.rat from 0.13-SNAPSHOT to 0.13

### PR DESCRIPTION
**Pull request by aurelienduarte**
## Contributor Comments
[Please place any comments here.  A description of the problem/enhancement, how to reproduce the issue, your testing methodology, etc.]

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by ottobackwards** [comment]
Hi, thanks for the contribution!  Can you have a look at filling out the pr template?  This this it is especially important to look at the part about saying you have tried:
`mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh `

Thanks!

**Comment by aurelienduarte** [comment]
> mvn -q clean integration-test install 
Failed, due to an unrelated issue. See summary below.

Tests run: 567, Failures: 1, Errors: 0, Skipped: 2

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test (unit-tests) on project stellar-common: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/aurelienduarte/Google Drive/Research/metron/metron/metron-stellar/stellar-common/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :stellar-common

**Comment by justinleet** [comment]
@aurelienduarte This is unfortunately a duplicate of https://github.com/apache/metron/pull/1264 (https://issues.apache.org/jira/browse/METRON-1872). Would you please close this PR?

We definitely still appreciate the contribution, and I'm always glad to see people participating in the community!

**Comment by aurelienduarte** [comment]
always a pleasure :)

**Pull request closed without merging**
