### PR TITLE
METRON-1881: Update the bro plugin used in metron development

### PR DESCRIPTION
**Pull request by JonZeolla**
## Contributor Comments
Once the metron-bro-plugin-kafka v0.3 is released, this will move full-dev to use it.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [X] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [X] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by ottobackwards** [comment]
What is up with this?

**Comment by JonZeolla** [comment]
I was expecting a 0.3 release in the plugin sooner rather than later, but that didn't happen.

Right now the 0.3 release is pending the test for topic selection logic, and then to be put up to a vote.

**Comment by mmiklavc** [comment]
@JonZeolla just checking in on this - still TBD for 0.3? Heh, that rhymes.

**Comment by JonZeolla** [comment]
Yeah, so once [METRON-2069](https://issues.apache.org/jira/browse/METRON-2069) is completed we should be ready to cut an 0.3 release, and then merge this PR.  However, I'm not aware of anyone actively working on METRON-2069.

**Comment by JonZeolla** [comment]
As a side note, 0.2 has an issue (segfaults bro/zeek on shutdown) which hasn't been resolved, and a large number of features and time has passed since it was released.  I wish I could return to it but that doesn't seem likely in the short term.

**Comment by ottobackwards** [comment]
@JonZeolla what exactly needs to be done?  I'll take a look if you can layout what we need to do

**Comment by ottobackwards** [comment]
maybe another jira? or something spelling it all out

**Comment by JonZeolla** [comment]
[METRON-2069](https://issues.apache.org/jira/browse/METRON-2069) is that other JIRA spelling it out.  Essentially we had a regression in METRON-1992 which was fixed in METRON-2003 (#26) but we never added a test to ensure it doesn't happen again.

**Comment by ottobackwards** [comment]
So, once 2069 is done, we are all set?

**Comment by JonZeolla** [comment]
In my opinion, yes.

**Comment by justinleet** [comment]
@JonZeolla @ottobackwards Is this good to go, and is it something we should try to get into 0.7.2 (or whatever it winds up being)?

**Comment by ottobackwards** [comment]
So I landed https://github.com/apache/metron-bro-plugin-kafka/pull/36, and I believe this would be good to go now.  @JonZeolla please confirm

**Comment by JonZeolla** [comment]
Yeah should be good

Jon Zeolla

**Comment by justinleet** [comment]
+1 by inspection.

@ottobackwards anything you need to see?

**Comment by mmiklavc** [comment]
> +1 by inspection.
> 
> @ottobackwards anything you need to see?

Bump - @ottobackwards?

**Comment by ottobackwards** [comment]
+1

**Comment by JonZeolla** [comment]
Closing due to the official decision to move Apache Metron to the ASF attic

**Pull request closed without merging**
