### PR TITLE
METRON-1491: The indexing topology restart logic is wrong

### PR DESCRIPTION
**Pull request by cestella**
## Contributor Comments
If either topology is down, Ambari shows all of Indexing as dead. Clicking start attempts to start them both and fails if either is still running. Furthermore, it appears to retry 3 times before finally failing the command.

In order to test this, kill one of the indexing topologies then attempt to start indexing from ambari.  Things should go smoothly.  Also, try restarting and starting in various states.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by ottobackwards** [comment]
Should we think about exposing them as separate things in ambari over all?  Go all the way with this?

**Comment by cestella** [comment]
@ottobackwards yeah, definitely; I think that's ultimately where we want to go.  The first step to that is separating out these functions like I have in this PR.  The next is doing the ambari work which will utilize it.  Shall I create a follow-on JIRA?

**Comment by ottobackwards** [comment]
Yes, lets get it in there

**Comment by cestella** [comment]
Ok, created [METRON-1492](https://issues.apache.org/jira/browse/METRON-1492).

**Comment by cestella** [comment]
Ok, I ran this up in full-dev and it functions as advertised.  Killing one of the indexing topologies and then starting, does not try to start the other topology.

**Comment by ottobackwards** [comment]
+1 by inspection

**Comment by mmiklavc** [comment]
+1 by inspection from me also

**Pull request closed without merging**
