### PR TITLE
METRON-1081:  Fix Alerts and Ops UI Notices file

### PR DESCRIPTION
**Pull request by james-sirota**
## Contributor Comments
[Please place any comments here.  A description of the problem/enhancement, how to reproduce the issue, your testing methodology, etc.]

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [ ] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [ ] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by ottobackwards** [comment]
I am not sure how to verify or review this

**Comment by james-sirota** [comment]
go to /Users/jsirota/Documents/hcp_release/metron-interface/metron-config and delete the node_modules folder.  then run npm install -prod to only pull in production libraries.  then run npm i npm-license-crawler -g to install the crawler program. then run npm-license-crawler --csv licenses.csv

**Comment by ottobackwards** [comment]
Are the modules/versions pulled in dependent on the version of node or something?  My list is different.  I have more things, and different versions for some.

[licenses.txt](https://github.com/apache/metron/files/1199144/licenses.txt)

**Comment by mmiklavc** [comment]
Is this still relevant?

**Comment by simonellistonball** [comment]
Yes, and needs to be done as an ongoing thing really. We have to keep on top of our Node licenses. I note that recent version of angular cli actually seem to generate licence and notice files for you, but not had chance to verify their depth and correctness yet. This may make life easier in future, but for now we're on older angular-cli, so have to use this method to keep on top of things.

**Comment by cestella** [comment]
+1 by inspection

**Comment by ottobackwards** [comment]
So, no comment on the discrepancy I found then?

**Comment by simonellistonball** [comment]
@ottobackwards I just re-ran this. We're not fixing versions in the UIs at the moment, so I would expect this kind of minor variance. This is mainly to ensure licenses are at least covered. The solution to the version fixing is the yarn stuff we're discussing elsewhere.

**Comment by ottobackwards** [comment]
I assume we are doing this for apache compliance.  Our acceptance of this variance is compliant then.  That was not my understanding.  But I'm sure the chair knows. 
Thanks

**Comment by cestella** [comment]
Sorry otto, I didn't see that comment, I'll admit.  I apologize.  Let me take a look at them and if there's further notices work to do, I'll make a follow-on PR.  Again, sorry, ignoring your discrepancy wasn't my intent.

**Pull request closed without merging**
