### PR TITLE
METRON-1450:Add rest endpoint documentation for splitting the indexing topology into random_access_indexing and batch_indexing

### PR DESCRIPTION
**Pull request by MohanDV**
## Contributor Comments

Added documentation for random access and batch indexing topology rest endpoints.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by JonZeolla** [comment]
Would you also mind updating the main README?

**Comment by MohanDV** [comment]
@JonZeolla are you referring to metron-platform/metron-indexing/README.md ?

**Comment by JonZeolla** [comment]
Yes

**Comment by MohanDV** [comment]
updated the main README for indexing

**Comment by JonZeolla** [comment]
I'm specifically referring to [this](https://github.com/MohanDV/metron/blob/4cb99e7186c408159cb41b0e5e8761fdcbfe74d2/metron-platform/metron-indexing/README.md#indexing-architecture) which is no longer accurate.

**Comment by MohanDV** [comment]
@JonZeolla it's out of the scope of this PR, This PR is intended to update the doc for rest endpoints.  I have created another PR (METRON-1458) to update the main README for indexing.

**Comment by JonZeolla** [comment]
I don't see a PR for METRON-1458, did you mean you opened a [JIRA](https://issues.apache.org/jira/projects/METRON/issues/METRON-1458)?  In the JIRA for [METRON-1450](https://issues.apache.org/jira/projects/METRON/issues/METRON-1450) the summary is:
```
Add documentation for splitting the indexing topology into random_access_indexing and batch_indexing
```

Based on that description, this would be the ticket to address the indexing README.  If you think it's worth splitting this into two JIRAs that's fine with me, but I already had [METRON-1454](https://issues.apache.org/jira/projects/METRON/issues/METRON-1454) open to remediate the main indexing README, but I closed it because the description of [METRON-1450](https://issues.apache.org/jira/projects/METRON/issues/METRON-1450) mirrored what I was looking to accomplish.  Let me know where you'd like to go from here, but regardless we should make sure that the PR title here matches the JIRA summary.

**Comment by MohanDV** [comment]
@JonZeolla Sorry I dint notice the METRON-1454 , I have updated the description for METRON-1450. 
I will mark my METRON-1458 as the duplicate of METRON-1454.

**Comment by MohanDV** [comment]
Bump. Can anyone offer a binding +1 ? I Would like to get this in.

**Comment by nickwallen** [comment]
+1 Thanks for correcting this @MohanDV.  This looks good.  

Let's give @JonZeolla a chance to respond before we merge this.

**Comment by JonZeolla** [comment]
The PR title here doesn't match the [JIRA](https://issues.apache.org/jira/projects/METRON/issues/METRON-1450?filter=allopenissues) but as long as we account for that during merging, I'm a +1 on this.  Thanks @MohanDV

**Comment by MohanDV** [comment]
@nickwallen / @JonZeolla can you please merge this request.

**Comment by MohanDV** [comment]
@nickwallen  / @JonZeolla  can you please merge this request.

**Comment by nickwallen** [comment]
Thanks @MohanDV .  Will merge this now.

**Pull request closed without merging**
