### PR TITLE
METRON-1795 Initial commit for a general purpose regular expressions …

### PR DESCRIPTION
**Pull request by jagdeepsingh2**
…parser.

## Contributor Comments
This is the PR to contribute a general purpose regular expression parser to metron.

### CODE REVIEW

**Comment by nickwallen** [comment]
Thanks for the contribution @jagdeepsingh2.  To take this any further we need at a minimum the following items.
* An explanation of what itch this scratches (Why is this needed over Grok parser?)
* Documented Instructions on how to use your parser. Include a README.md in your code contribution.
* A test plan including in your PR description showing us how to spin-up and test your parser
* A description of how you have personally tested this
* The checklist of items that you must have accidentally deleted from the PR description.

**Comment by mmiklavc** [comment]
@jagdeepsingh2 Some emphasis on the configuration options for this parser would be particularly useful. Please refer to https://github.com/apache/metron/tree/master/metron-platform/metron-parsers for some good examples of how we document existing Metron parsers.

**Comment by mmiklavc** [comment]
@jagdeepsingh2 - can you review your recent commits? It looks like there's a bad merge somewhere considering the jump to 6k+ lines in the diff.

**Comment by jagdeepsingh2** [comment]
Yeah, I performed a rebase yesterday as I had to pull the latest changes from upstream. What is the best way out? Should I discard this PR and create a fresh and clean PR?

**Comment by mmiklavc** [comment]
@jagdeepsingh2  - you *could* try this - https://stackoverflow.com/questions/134882/undoing-a-git-rebase, but at this point it might be better to just open a new PR bc pushing up to github is going to cause some additional drama as well. You'll want to keep the default checklist that's populated in the description when you open the PR. Please note the comments from @nickwallen and myself regarding what should also be included in your description.

In general, once you've pushed a branch to the public it's better to just git merge, otherwise you can get into trouble like this. We flatten PR's once they're committed to master anyhow.

**Comment by jagdeepsingh2** [comment]
Closing this PR because of corrupted git commits history. I will create a new PR for this.

**Pull request closed without merging**
