### PR TITLE
METRON-984 Stellar functions to decode encoded fields or strings

### PR DESCRIPTION
**Pull request by ottobackwards**
This functionality involves ( as a start ) encodings based on the Apache Commons Codec library ( binary )

Support exists for the following encodings:
 * Base32
 * Base32 as hex
 * Base 64
 * Binary
 * Hex

The Stellar functions added:
* LIST_SUPPORTED_ENCODINGS : List the supported encodings
* IS_ENCODING : is this string encoded this way?
* DECODE : decode a string with a given encoding, optionally verify it is in fact encoded that way
* ENCODE: encodes a string with a given encoding

## Contributor Comments
[Please place any comments here.  A description of the problem/enhancement, how to reproduce the issue, your testing methodology, etc.]

### Testing
- Build and tests should run
- run the stellar shell
```bash
cd metron/metron-stellar/stellar-common
mvn -DskipTests package && mvn exec:java -Dexec.mainClass="org.apache.metron.stellar.common.shell.StellarShell"
```
```bash
[Stellar]>>> Functions loaded, you may refer to functions now...

[Stellar]>>> baseString:="METRON is a top level project!"
[Stellar]>>> encoded:=ENCODE(baseString,'BASE64')
[Stellar]>>> encoded
TUVUUk9OIGlzIGEgdG9wIGxldmVsIHByb2plY3Qh
[Stellar]>>> decoded:=DECODE(encoded,'BASE64')
[Stellar]>>> decoded
METRON is a top level project!
[Stellar]>>> IS_ENCODING(encoded,'BASE64')
true
```

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [na] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by cestella** [comment]
Ok, I dig this a lot.  +1 by inspection.  The only thing I ask is that since you're adding a new dependency, would you ensure a smoketest in full-dev and maybe pass through a couple of records with the stellar fucntions exercised?  I do this only because new dependencies may introduce classpath issues that don't rear their heads until runtime.

**Comment by ottobackwards** [comment]
Will do

**Comment by ottobackwards** [comment]
@cestella, I don't see my functions listed in the config ui, but they are in the shell.  That doesn't seem right?

**Comment by ottobackwards** [comment]
And they do get returned from the rest api stellar controller

**Comment by ottobackwards** [comment]
Ok @cestella , I used the Stellar management functions : 
```bash
[Stellar]>>> bro_parser_config:= CONFIG_GET('PARSER','bro')
[Stellar]>>> PARSER_STELLAR_TRANSFORM_PRINT( bro_parser_config )
╔═══════╤════════════════╗
║ Field │ Transformation ║
╠═══════╧════════════════╣
║ (empty)                ║
╚════════════════════════╝
[Stellar]>>> original_string:='foo'
[Stellar]>>> encoded_original:=ENCODE(original_string,'BASE64')
[Stellar]>>> SHELL_LIST_VARS(40)
╔═══════════════════╤═══════════════════════════════════════════════════════════════════╤══════════════════════════════════╗
║ VARIABLE          │ VALUE                                                             │ EXPRESSION                       ║
╠═══════════════════╪═══════════════════════════════════════════════════════════════════╪══════════════════════════════════╣
║ encoded_original  │ Zm9v                                                              │ ENCODE(original_string,'BASE64') ║
╟───────────────────┼───────────────────────────────────────────────────────────────────┼──────────────────────────────────╢
║ original_string   │ foo                                                               │ 'foo'                            ║
╟───────────────────┼───────────────────────────────────────────────────────────────────┼──────────────────────────────────╢
║ bro_parser_config │ {                                                                 │ CONFIG_GET('PARSER','bro')       ║
║                   │                                                                   │                                  ║
║                   │ "parserClassName":"org.apache.metron.parsers.bro.BasicBroParser", │                                  ║
║                   │                                                                   │                                  ║
║                   │ "sensorTopic":"bro",                                              │                                  ║
║                   │   "parserConfig":                                                 │                                  ║
║                   │ {}                                                                │                                  ║
║                   │ }                                                                 │                                  ║
╚═══════════════════╧═══════════════════════════════════════════════════════════════════╧══════════════════════════════════╝
[Stellar]>>> bro_parser_config_new:= PARSER_STELLAR_TRANSFORM_ADD( bro_parser_config , SHELL_VARS2MAP( 'encoded_original' ) )
[Stellar]>>> PARSER_STELLAR_TRANSFORM_PRINT( bro_parser_config_new )
╔══════════════════╤══════════════════════════════════╗
║ Field            │ Transformation                   ║
╠══════════════════╪══════════════════════════════════╣
║ encoded_original │ ENCODE(original_string,'BASE64') ║
╚══════════════════╧══════════════════════════════════╝

[Stellar]>>> CONFIG_PUT('PARSER', bro_parser_config_new , 'bro' )
[Stellar]>>> PARSER_STELLAR_TRANSFORM_PRINT( CONFIG_GET('PARSER', 'bro' ))
╔══════════════════╤══════════════════════════════════╗
║ Field            │ Transformation                   ║
╠══════════════════╪══════════════════════════════════╣
║ encoded_original │ ENCODE(original_string,'BASE64') ║
╚══════════════════╧══════════════════════════════════╝

[Stellar]>>>
```

and in kibana observed : 

screen shot 2017-07-13 at 17 53 58

**Comment by ottobackwards** [comment]
@cestella  are we still OK with this?  I'd like to get it in

**Pull request closed without merging**
