### PR TITLE
METRON-1709 : Added the required scripts to start / stop PCAP topology from Ambari

### PR DESCRIPTION
**Pull request by MohanDV**
## Contributor Comments

Created PCAP topology as Metron component, Created  required scripts to create kafka topic, hdfs folder for pcap sequence files with required ACL's and added controls to start / stop the PCAP topology from Ambari.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by nickwallen** [comment]
I am not able to spin-up the Full Dev environment with this.  It keeps failing here.  Have you run this up in Full Dev?
```
TASK [ambari_config : Deploy cluster with Ambari; http://node1:8080] ***********
fatal: [node1]: FAILED! => {"changed": false, "failed": true, "msg": "Ambari client exception occurred: Could not create blueprint: request code 400,                     request message {\n  \"status\" : 400,\n  \"message\" : \"Cluster Topology validation failed.  Invalid service component count: [METRON_PCAP(actual=0, required=1)].  To disable topology validation and create the blueprint, add the following to the end of the url: '?validate_topology=false'\"\n}"}
	to retry, use: --limit @/Users/nallen/tmp/metron-pr1201/metron-deployment/development/centos6/ansible/playbook.retry

PLAY RECAP *********************************************************************
node1                      : ok=76   changed=42   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by nickwallen** [comment]
Can you merge this with master?  It is hard to tell what is part of this PR.

**Comment by MohanDV** [comment]
@nickwallen having separate panel for PCAP configs is been addressed in the pull request  [1132](https://github.com/apache/metron/pull/1132). It will be a duplicate effort here.

**Comment by nickwallen** [comment]
> @MohanDV ... pull request 1132. It will be a duplicate effort here.

Gotcha.  I was not aware of the other PR.  That will work.

**Comment by nickwallen** [comment]
+1 Looks great.  Thanks a bunch for the contribution.

**Comment by nickwallen** [comment]
I want to hold off on the merge until we get the pcap properties change sorted on this. @anandsubbu  is opening a re-opening a PR on that.

**Comment by anandsubbu** [comment]
Hi @nickwallen , I would like to create a fresh pull request based on these changes. Could you go ahead and merge this please ?

**Pull request closed without merging**
