### PR TITLE
METRON-1923: change default consumer name

### PR DESCRIPTION
**Pull request by Condla**
## Contributor Comments

Fixes https://issues.apache.org/jira/browse/METRON-1923

* Default consumer name used sensor topic name.
* This caused problems when using multiple parsers reading from the same topic.
* New default contains sensor type/name.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by Condla** [comment]
@simonellistonball  the inputTopic is used in the SimpleStormKafkaBuilder.

https://github.com/apache/metron/blob/877b510146456f2eed6eb12c35b1124c35b00aa5/metron-platform/metron-parsers/src/main/java/org/apache/metron/parsers/topology/ParserTopologyBuilder.java#L213

**Comment by simonellistonball** [comment]
Good point. I would say this is a very good thing to have.

**Comment by james-sirota** [comment]
+1 by inspection, looks like a fairly minor change.  there seems to be a merge conflict that needs fixing

**Comment by mmiklavc** [comment]
@Condla can you please provide the test steps you followed to validate this and resolve the merge conflicts when you get a chance?

**Comment by mmiklavc** [comment]
Here's an example - https://github.com/apache/metron/pull/1368#issuecomment-477798665. Yours will be a fraction of the size, but this is just to give you an idea.

**Comment by mmiklavc** [comment]
Any updates on this? It appears that even with this change there aren't any automated tests breaking, which is not ideal.

**Comment by mmiklavc** [comment]
@Condla nudge

**Comment by mmiklavc** [comment]
Due to inactivity I'm closing this PR

**Pull request closed without merging**
