### PR TITLE
METRON-1693: Fix Pcap CLI local FS finalizer

### PR DESCRIPTION
**Pull request by mmiklavc**
## Contributor Comments

https://issues.apache.org/jira/browse/METRON-1693

This is to fix a regression in Pcap CLI. This should be validated with both the cli AND the REST API.

**Testing**

Preferably, run this up with pycapa (instructions in comments below)

**REST API test script**

https://github.com/apache/metron/pull/1109

**Pcap CLI**

Run through the steps outline here - https://github.com/apache/metron/pull/256

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [ ] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [ ] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
n/a

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by mmiklavc** [comment]
Notes on installing and using pycapa in full dev (CentOS 7).

```
Installing pycapa
====================
# env vars
PYCAPA_HOME=/opt/pycapa
PYTHON27_HOME=/opt/rh/python27/root

# Install these packages via yum (RHEL, CentOS)
#     epel-release
#     centos-release-scl
#     "@Development tools"
#     python27
#     python27-scldevel
#     python27-python-virtualenv
#     libpcap-devel
#     libselinux-python

# You can run this command to loop through installing the needed deps
for item in epel-release centos-release-scl "@Development tools" python27 python27-scldevel python27-python-virtualenv libpcap-devel libselinux-python; do yum install -y $item; done

#Setup directories
mkdir $PYCAPA_HOME && chmod 755 $PYCAPA_HOME

# Create virtualenv
export LD_LIBRARY_PATH="/opt/rh/python27/root/usr/lib64"
cd $PYCAPA_HOME
${PYTHON27_HOME}/usr/bin/virtualenv pycapa-venv

# Install librdkafka (must use 0.11.5 or greater these days)
export PREFIX=/usr
wget https://github.com/edenhill/librdkafka/archive/v0.11.5.tar.gz   -O - | tar -xz
cd librdkafka-0.11.5/
./configure --prefix=$PREFIX
make
make install

echo "$PREFIX/lib" >> /etc/ld.so.conf.d/pycapa.conf
ldconfig -v

# Copy pycapa
# copy incubator-metron/metron-sensors/pycapa from the Metron source tree into $PYCAPA_HOME on the node you would like to install pycapa on. Files should end up in $PYCAPA_HOME/pycapa/<files>

# Build it
cd ${PYCAPA_HOME}/pycapa
# activate the virtualenv
source ${PYCAPA_HOME}/pycapa-venv/bin/activate
pip install -r requirements.txt
python setup.py install

# Run it
cd ${PYCAPA_HOME}/pycapa-venv/bin
pycapa --producer --topic pcap -i eth1 -k $BROKERLIST
```

**Comment by cestella** [comment]
+1 by inspection.

**Comment by justinleet** [comment]
+1, tested in full dev and it successfully wrote locally instead of trying to write to HDFS. REST continued to work as expected.

**Comment by mmiklavc** [comment]
Merged with feature branch

**Pull request closed without merging**
