### PR TITLE
METRON-1507 Added support for vagrant cachier

### PR DESCRIPTION
**Pull request by simonellistonball**
## Contributor Comments
This is a Vagrant config change to enable the use of vagrant-cachier to reduce build times for the full dev platform. Time saving is heavily network dependent, but anecdotally I've found it saves me around 10 mins per provision of vagrant development environment. YMMV.

To test:

1. Install vagrant-cachier, and spin up centos and ubuntu vagrant development platforms.
2. Verify that packages are populated into your local (the client running vagrant) ~/.vagrant/cache directories.
3. vagrant destroy your development environments
4. spin up vagrant environments again, packages should be pulled from the cache instead of the network at this point.

Note that the vagrant-cachier plugin is not required, nor shipped, bundled or in any way distributed by this change. It does have a compatible license (MIT) but it is outside of the Metron project scope to install this, so there is no need to update license or dependency documentation.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [ ] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by ottobackwards** [comment]
Should this work with ubuntu as well?  Would it have to be different?  Can you describe how it works?

**Comment by simonellistonball** [comment]
The PR includes ubuntu support, the cachier would just cache debs from apt instead of rpms from yum. TBH I've tested centos more than ubuntu. The use is still the same though, should be transparent to the user.

**Comment by ottobackwards** [comment]
I didn't think ubuntu had yum repos.d in the image?

**Comment by simonellistonball** [comment]
The yum stuff only happens in the centos include in ansible, it's not necessary in the ubuntu version, which uses a different ansible include.

An extra test for the record... manual run of the ubuntu14 development environment: 

building ubuntu14 (measuring start to end of ansible logs)
without cache: 45m13
with cache populated: 28m57

so won't change the world, but will hopefully save some coffee during dev-test cycles.

**Comment by nickwallen** [comment]
I think this is great.  I appreciate that the environments will continue to work with or without the Cachier plugin installed.  Anything we can do to speed-up the dev environments is a big win in my book.

One ask would be to embed a link to 'vagrant-cashier' in the README so that a user can easily find the plugin installation instructions.  I believe this is the right location; https://github.com/fgrehm/vagrant-cachier.

**Pull request closed without merging**
