### PR TITLE
METRON-1462: Separate ES and Kibana from Metron Mpack

### PR DESCRIPTION
**Pull request by mmiklavc**
## Contributor Comments

https://issues.apache.org/jira/browse/METRON-1462

This splits ES and Kibana into their own MPacks. Two comments for reviewers:
- The original discuss thread mentioned putting this in metron-contrib. Are we dead set on this, or is my split in metron-deployment reasonable?
- I kept the Kibana templates and associated documentation in their current location and migrated them with the Kibana service. This is consistent with our current deployment and means we don't need to add a new set of features to the Metron MPack to publish them. A point in favor of moving this to Metron's MPack would be that we think this is in the purview of Metron and would make the Ambari design more consistent when we introduce Solr. 
**UPDATE** - Kibana dashboard moved to Metron MPack.

**Testing**
Spin up full dev and verify the Kibana dashboard is displaying information.

## Pull Request Checklist

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

### CODE REVIEW

**Comment by ottobackwards** [comment]
I think I mentioned contrib.  They don't have to go in contrib, I think at the time someone mentioned not wanting to maintain them.. If we don't then I thought contrib would make sense.
We can keep them normal.

Metron installation artifacts ( templates, schemas, kibana objects, queries, and dashboards ) should be managed separate from the kibana / es / solr /  packs.
They are artifacts of metron and we need to support installing them on existing installations.
If they need to be installed in a different phase, or as their own component, then fine.
we need to break that down more anyway ( like package the 'demo' system + parser configs as optional ) maybe.

**Comment by anandsubbu** [comment]
+1

Works as advertised. I used both mpacks to deploy a 12-node CentOS 7 cluster (Ambari 2.6.0.0 and HDP 2.6.3.0). Was able to kerberize the cluster and get bro indices into ES.

**Comment by merrimanr** [comment]
I spun this up in full dev and everything worked as expected.  The organization looks good to me and I can't find anything wrong with it.  +1

**Comment by ottobackwards** [comment]
What about upgrading.md?

**Comment by mmiklavc** [comment]
@ottobackwards I believe the repercussions are the same as they are for the existing MPack since the services are distinct from the MPack itself. We should probably consider a separate test for this.

**Comment by mmiklavc** [comment]
Also, I will look at moving the Kibana templates to Metron as this is something that will need to be done for Solr as well.

**Comment by mmiklavc** [comment]
@ottobackwards @merrimanr @anandsubbu - I've moved the Kibana dashboard from the Elasticsearch MPack to the Metron one. Can you reaffirm your +1's or let me know if there's anything more I need to address?

**Comment by mmiklavc** [comment]
Kick Travis re: profiler test failure

**Comment by mmiklavc** [comment]
I re-tested this via full dev spin-up from scratch. The dashboard comes up as expected.

**Comment by nickwallen** [comment]
When I spin this up in Ubuntu, the Indexing topology is unable to write to Elasticsearch.  This may very well be a resource constraint issues in my environment, but I thought I'd mention it before I spend too much more time digging into this.
```
2018-04-04 15:51:05.707 o.a.s.d.executor Thread-6-indexingBolt-executor[3 3] [ERROR] 
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{rZcTXccfSPq4fH4IRLQ0zg}{node1}{127.0.1.1:9300}]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347) ~[stormjar.jar:?]
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245) ~[stormjar.jar:?]
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59) ~[stormjar.jar:?]
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363) ~[stormjar.jar:?]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408) ~[stormjar.jar:?]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80) ~[stormjar.jar:?]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54) ~[stormjar.jar:?]
	at org.apache.metron.elasticsearch.writer.ElasticsearchWriter.write(ElasticsearchWriter.java:92) ~[stormjar.jar:?]
	at org.apache.metron.writer.BulkWriterComponent.flush(BulkWriterComponent.java:239) [stormjar.jar:?]
	at org.apache.metron.writer.BulkWriterComponent.write(BulkWriterComponent.java:217) [stormjar.jar:?]
	at org.apache.metron.writer.bolt.BulkMessageWriterBolt.execute(BulkMessageWriterBolt.java:236) [stormjar.jar:?]
	at org.apache.storm.daemon.executor$fn__7590$tuple_action_fn__7592.invoke(executor.clj:730) [storm-core-1.1.0.2.6.4.0-91.jar:1.1.0.2.6.4.0-91]
	at org.apache.storm.daemon.executor$mk_task_receiver$fn__7511.invoke(executor.clj:462) [storm-core-1.1.0.2.6.4.0-91.jar:1.1.0.2.6.4.0-91]
	at org.apache.storm.disruptor$clojure_handler$reify__7166.onEvent(disruptor.clj:40) [storm-core-1.1.0.2.6.4.0-91.jar:1.1.0.2.6.4.0-91]
	at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:472) [storm-core-1.1.0.2.6.4.0-91.jar:1.1.0.2.6.4.0-91]
	at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:451) [storm-core-1.1.0.2.6.4.0-91.jar:1.1.0.2.6.4.0-91]
	at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:73) [storm-core-1.1.0.2.6.4.0-91.jar:1.1.0.2.6.4.0-91]
	at org.apache.storm.daemon.executor$fn__7590$fn__7603$fn__7656.invoke(executor.clj:849) [storm-core-1.1.0.2.6.4.0-91.jar:1.1.0.2.6.4.0-91]
	at org.apache.storm.util$async_loop$fn__553.invoke(util.clj:484) [storm-core-1.1.0.2.6.4.0-91.jar:1.1.0.2.6.4.0-91]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by nickwallen** [comment]
I was able to replicate this same problem in master running on the ubuntu14 dev environment.  This does not seem to be a problem caused by your PR.  I will open a separate defect for this.

+1 That being said, nice work!

**Comment by mmiklavc** [comment]
Awesome, thanks @anandsubbu and @nickwallen!

**Pull request closed without merging**
