### PR TITLE
METRON-1733: PCAP UI - PCAP queries don't work on Safari

### PR DESCRIPTION
**Pull request by sardell**
## Contributor Comments
This PR fixes a bug where Safari cannot read the format of the date we are passing to the startTimeMs and endTimeMs parameters. To resolve this, I used moment js (which was already being used in the project) to get the numeric value of the time strings instead of new Date().getTime().

## Testing
Using Safari, run a PCAP query in the Alerts UI. If you check the request payload, it should contain the correct numeric values for the startTimeMs and endTimeMs instead of NaN, and your search results should complete the same as they would in Chrome or another browser.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- n/a ~~Have you written or updated unit tests and or integration tests to verify your changes?~~
- n/a ~~If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?~~
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- n/a ~~Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:~~

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by mmiklavc** [comment]
Pending Travis, lgtm via inspection. +1. Thanks for the contribution @sardell!

**Comment by ruffle1986** [comment]
I think it's just enough the trigger a travis rebuild to make it pass.

**Comment by merrimanr** [comment]
@sardell can you close and reopen this PR to trigger another travis run?

**Comment by sardell** [comment]
Closing and reopening to rerun Travis.

**Comment by merrimanr** [comment]
I verified this in full dev.  +1

**Comment by merrimanr** [comment]
Can you close this @sardell?

**Pull request closed without merging**
