### PR TITLE
METRON-1417: Disable pcap-service by default in Monit

### PR DESCRIPTION
**Pull request by mmiklavc**
## Contributor Comments

https://issues.apache.org/jira/browse/METRON-1417

Free up some full dev mem. We don't run the pcap topology atm, so little point in running this service by default. Users can manually re-enable

I'm spinning up full dev to finish testing now.

## Testing

Spin up full dev and verify pcapservice is not running
```
ps aux|grep pcapservice
```

That is all. Now enjoy a nap, you've earned it. ;-)

## Pull Request Checklist

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### CODE REVIEW

**Comment by cestella** [comment]
+1, anything to save room on vagrant at the moment.

**Comment by mmiklavc** [comment]
Just a heads up my first manual test failed with full dev because of this guy:
https://github.com/apache/metron/blob/master/metron-deployment/roles/monit-start/tasks/main.yml#L36
```
- name: Find the services installed on the host
  shell: monit summary | tail -n +3 | awk -F"'" '{print $2}'
  register: installed_services

# which services that need started are actually installed on this host?
- set_fact:
    installed_services_to_start: "{{ services_to_start | intersect(installed_services.stdout_lines) }}"
```

It grabs all the things in monit and attempts to start them.

I removed the pcapservice monit script since we don't really need it for full dev. Full dev still spins up as normal and the pcapservice is no longer running.

```
[root@node1 ~]# ps aux|grep pcapservice
root      2167  0.0  0.0 103312   888 pts/0    S+   01:00   0:00 grep pcapservice

[root@node1 ~]# monit summary
The Monit daemon 5.14 uptime: 2h 31m

Process 'snort'                     Running
Process 'bro'                       Running
System 'node1'                      Not monitored
```

This is all set, pending Travis getting fixed.

**Comment by nickwallen** [comment]
I one-up'd you in #903 by just removing Monit all-together.  There is really no need for it any longer.  It was useful before the MPack; now not so much.

**Comment by nickwallen** [comment]
I should also say, #903 certainly doesn't preclude this.   This has a +1 from me.

**Comment by mmiklavc** [comment]
Thanks @nickwallen, I plan to spend some time reviewing 903 as well.

**Pull request closed without merging**
