### PR TITLE
METRON-1355: Convert metron-elasticsearch to new infrastructure

### PR DESCRIPTION
**Pull request by merrimanr**
## Contributor Comments
This PR switches metron-elasticsearch integration tests from using in-memory components to the e2e Docker infrastructure.  A high-level summary of the changes:

- Updated travis to only run the metron-elasticsearch tests
- Updated the Elasticsearch Docker image to the same version as Metron
- Removed the requirement to build a base "metron-centos" image.  Removes an extra Docker build step and I'm not sure caching this helps much anyways.
- Updated each integration test to use index names that are namespaced with the test class name
- Replaced the in-memory component setup with an Elasticsearch client configured for the Elasticsearch Docker container
- Added steps to setup/delete indices before/after each test
- Moved Elasticsearch in-memory helper methods and common integration tests methods to a utils class
- Fixed a minor bug in the ElasticsearchMetaAlertDao class where the index is always hardcoded to "metaalert"
- Added some initial documentation for the metron-docker-e2e module

The scope of this PR are 3 of the 4 metron-elasticsearch integration tests:

- org.apache.metron.elasticsearch.integration.ElasticsearchMetaAlertIntegrationTest
- org.apache.metron.elasticsearch.integration.ElasticsearchSearchIntegrationTest
- org.apache.metron.elasticsearch.integration.ElasticsearchUpdateIntegrationTest

Most of the test logic in org.apache.metron.elasticsearch.integration.ElasticsearchIndexingIntegrationTest is actually in metron-indexing so that test will be updated when we convert that module.

At this point only the metron-elasticsearch tests are run in travis.  My plan is to slowly add tests for each module until we reach feature parity with master.  At that point the "install" section of .travis.yml will be the same.  The alerts ui e2e tests were removed for now until the work being done to stabilize them is complete.

The ES in-memory component starts up pretty fast so performance improved for the 3 tests by about 7 seconds.  Curious to hear what people think.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [ ] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by justinleet** [comment]
I'm unable to get the integration tests running locally.  I've been able to get the docker containers up and running, but ES isn't exposed at localhost, only through the explicit docker-machine ip.  This causes the integration tests to fail, as they are unable to successfully query against ES.
Any idea why this is happening? Am I missing an env config or something?

Also, is it worthwhile to wrap most of the setup in a script? There's enough steps that have to be taken that I'd really like a script that's just "setup_integration_env.sh".  Extra credit if it can be rolled into the maven build such that it just automagically takes care of it when we run the maven integration test target (or it's run by install or whatever).  It would be super nice if we didn't have to worry about anything other than just running the maven target.

Regardless of what wrapping we do, it would be really nice to clean some stuff up so the integration test instructions become a one-shot "Here's the step by step". Right now, I had to look at the Travis run to figure out (remember) the semi-odd way we split unit and integration test calls in maven, etc.

**Comment by merrimanr** [comment]
Sorry I should have documented this better in the PR description.  The docker-machine ip address needs to be substituted in ElasticsearchTestUtils temporarily if you want to run this on your local Mac OS.  There is a Jira for this work here:  https://issues.apache.org/jira/browse/METRON-1356.  Everything you've described including the TODO is intended to be handled there.  Do you think that needs to come first before you review this PR?

**Comment by justinleet** [comment]
No, that can wait for the follow-on ticket.  Could you add a quick one-sentence blurb about the ElasticsearchTestUtils in the README so things are easier for anyone to test later (with the knowledge that it'll drop out in the later ticket)?

**Comment by justinleet** [comment]
+1, thanks for the contribution.  Glad to see this making progress, it's definitely valuable.

**Pull request closed without merging**
