### PR TITLE
METRON-1370 Create Full Dev Equivalent for Ubuntu

### PR DESCRIPTION
**Pull request by nickwallen**
This PR adds a single node, VM based deployment mechanism based on Ubuntu Trusty.  This has feature parity with the existing CentOS single node VM.  This will help us continue to improve and support the Ubuntu-based DEB packages that were added in #868.

### Changes

* The Metron, Elasticsearch, and Kibana MPacks were updated to support installation on Ubuntu.  This included making the following changes.

    * Adding repo definitions for Ubuntu
    * Changing the default location of the `/etc/sysconfig/elasticsearch` configuration to work across platforms
    * Adding an additional configuration in the MPack to allow Elasticsearch to perform a memory lock on Ubuntu
    * Support configuration of Elasticsearch on a platform running Systemd; like Ubuntu 

* The Elasticsearch MPack was enhanced to correctly perform a service check.  Previously the hostname and port were hard coded and the service check was not functional in most environments.

* The Ubuntu DEBs were enhanced to allow for the addition of "maintainer scripts".  This allows the Management UI and Alerts UI service scripts to be installed with the DEBs.  This was needed to reach feature parity with the RPMs.

* The name `full-dev-platform` no longer makes sense IMHO.  We do not have a `quick-dev-platform` any longer to distinguish it from.  Now the main distinguisher is the underlying operating system.  I renamed our "Full Dev" development environment to `metron-on-centos` and `metron-on-ubuntu`.  I am completely open to community suggestions on what these should be named.

    ```
    metron-deployment/development/
    ├── README.md
    ├── fastcapa
    ├── centos6
    └── ubuntu14
    ```
    
* The organization of `metron-deployment` had to change so that assets could be reused across both the CentOS and Ubuntu deployments.  All shared Ansible assets were moved to `metron-deployment/ansible`.  This includes the Ansible modules, playbooks and roles that are all used across multiple environments.

    ```
    metron-deployment/ansible/
    ├── extra_modules
    ├── playbooks
    └── roles
    ```

* The following Ansible roles had to be updated to support both CentOS and Ubuntu based on small differences in package names and conventions.

    * `ambari-common` 
    * `ambari-config`
    * `ambari-master`
    * `ambari-slave`
    * `libselinux-python`
    * `ntp`

* A new role was added to enable swap space; `enable-swap`.  This is required for the Ubuntu deployment as the underlying Ubuntu Trusty image does not have swap space enabled by default.

* The `metron-builder` role was changed to selectively build either the DEBs or the RPMs as needed.

* The `metron-rpms` role was renamed to `metron-packages` and was also enhanced to create the local repository on a Ubuntu host.  This also selectively copies either RPMs or DEBs to the VM as needed.

* Monit is no longer needed and so has been removed from all VM deployments.  Monit was added prior to the existence of our Mpack installer.  It is no longer needed

* Removed the `metron-streaming` role which is no longer applicable since these functions are now performed by the MPack.

### Testing

I have performed the following testing based on these changes.

- [x] Run Metron on CentOS.  

    ```
    cd metron-deployment/development/centos6
    vagrant up
    ```

    * Validate that alerts are visible within the Alerts UI.
    * Validate that the Metron Service Check completes successfully.
    * Validate that the Elasticsearch service check completes successfully.

    Be sure to shutdown and halt or destroy this VM before moving on to the next step.

- [x] Run Metron on Ubuntu.

    ```
    cd metron-deployment/development/ubuntu14
    vagrant up
    ```

    * Validate that alerts are visible within the Alerts UI.
    * Validate that the Metron Service Check completes successfully.
    * Validate that the Elasticsearch service check completes successfully.

    Be sure to shutdown and halt or destroy this VM before moving on to the next step.

- [x] Run one of the Fastcapa test environments.

    ```
    cd metron-deployment/development/fastcapa/centos-7.1/
    vagrant up
    ```

    * If the process fails at the task "fastcapa : Restart for modified kernel params" simply run `vagrant provision` again.
    * Ensure that the deployment process reports success.  Automated validation is performed as part of the deployment process.

- [x] Deploy Metron to AWS EC2.

    ```
    cd metron-deployment/amazon-ec2
    ./run.sh
    ```

    * Validate that alerts are visible within the Alerts UI.
    * Validate that the Metron Service Check completes successfully.
    * Validate that the Elasticsearch service check completes successfully.

### CODE REVIEW

**Comment by nickwallen** [comment]
I am continuing a final round of testing to make sure these changes are solid.  I wanted to get the PR open so I could start getting feedback as soon as possible.

**Comment by ottobackwards** [comment]
Trying this now.   
Only comment on the content here is there is a _lot_ going on in this pr.  A lot of while I'm here I might as well work.
It might have been better to have kept this more narrow ( although it was never going to be narrow ).
I wouldn't change anything at this point however.

**Comment by ottobackwards** [comment]
Failure during vagrant up for metron-on-ubuntu

```

2018-01-25 10:41:49,302 p=37541 u=ottofowler |  [0;31mfatal: [node1]: FAILED! => {"changed": true, "cmd": "dpkg-scanpackages . /dev/null | gzip -9c > dists/METRON/main/binary-amd64/Packages.gz", "delta": "0:00:00.062622", "end": "2018-01-25 15:41:49.325958", "failed": true, "rc": 2, "start": "2018-01-25 15:41:49.263336", "stderr": "/bin/sh: 1: cannot create dists/METRON/main/binary-amd64/Packages.gz: Directory nonexistent\ndpkg-scanpackages: info: Wrote 0 entries to output Packages file.", "stdout": "", "stdout_lines": [], "warnings": []}[0m
2018-01-25 10:41:49,332 p=37541 u=ottofowler |   ____________ 
< PLAY RECAP >
 ------------ 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```


------------------
platform_info
------------------

```
Metron 0.4.3
--
* pr-903
--
commit d2cf8fca52d746ec65597cbb826f4cb9ac886a21
Author: Nick Allen <nick@nickallen.org>
Date:   Wed Jan 24 19:07:49 2018 -0500

    The sensors and pcap replay need to start themselves since Monit will not do it
--
--
ansible 2.0.0.2
  config file = /Users/ottofowler/tmp/metron-pr-903/metron-deployment/vagrant/metron-on-ubuntu/ansible.cfg
  configured module search path = ../../ansible/extra_modules
--
Vagrant 2.0.1
--
Python 2.7.14
--
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T03:58:13-04:00)
Maven home: /usr/local/Cellar/maven/3.5.2/libexec
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.3", arch: "x86_64", family: "mac"
--
Docker version 17.12.0-ce, build c97c6d6
--
node
v6.10.2
--
npm
3.10.10
--
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
--
Compiler is C++11 compliant
--
Darwin Winterfell 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
--
Total System Memory = 16384 MB
Processor Model: Intel(R) Core(TM) i7-4870HQ CPU 
Processor Speed: 2.50GHz
Total Physical Processors: 4
Total cores: 4
Disk information:
/dev/disk1s1   465Gi  380Gi   81Gi    83% 3929490 9223372036850846317    0%   /
/dev/disk1s4   465Gi  3.0Gi   81Gi     4%       3 9223372036854775804    0%   /private/var/vm
This CPU appears to support virtualization
```

**Comment by ottobackwards** [comment]
@nickwallen let me know when you feel ok about it, I'll run it through again.

**Comment by nickwallen** [comment]
I spun this up again on both Ubuntu and CentOS.  Both worked successfully.  I am happy with it now @ottobackwards .  Give her another go when you can.  Thanks.

**Comment by ottobackwards** [comment]
Sure.  
Question.  Do we expect there to be issues with 2.6?  Is this PR and Casey's 2.6 pr going to conflict or have issues?  How will we know to retest this after that one lands if this lands first? etc etc

**Comment by nickwallen** [comment]
> @ottobackwards : Do we expect there to be issues with 2.6? Is this PR and Casey's 2.6 pr going to conflict or have issues?

Yes, we will need to retest one or the other.  I am open to helping retest either this or #907, whichever goes in last.  If you or @cestella see an advantage to one or the other going first, I am all ears.

Fortunately, I do not expect there to be a problem.  Portions of this PR were previously tested against Ambari 2.6.  But of course, anything can happen, so we will need to retest either way.

**Comment by ottobackwards** [comment]
+1 -> ran up both images, everything checked out
Ship it

**Comment by nickwallen** [comment]
Thanks @ottobackwards .  I'll see if we can get any more reviewers before I merge this.

**Comment by cestella** [comment]
Honestly my only beef with this is the directory naming.  I think I'd prefer `metron-deployment/vagrant/{centos_$VERSION,ubuntu_$VERSION}` because it's possible that we may want 2 separate versions of centos and the `on_metron` is kinda redundant.

**Comment by lvets** [comment]
- Wouldn't `dev-on-centos` and `dev-on-ubuntu` or even `metron-dev-centos` and `metron-dev-ubuntu` make more sense? I don't think we want people to expect that this VM is sufficient to run in production?
- Just for my understanding, but why Ubuntu Trusty? In April that will be 2 full Ubuntu LTS versions behind the then current one...

**Comment by JonZeolla** [comment]
@lvets trusty is 14.04.  As far as I'm aware the only newer LTS is 16.04, with a new one expected in April.  https://wiki.ubuntu.com/Releases

**Comment by nickwallen** [comment]
> @lvets: Just for my understanding, but why Ubuntu Trusty? In April that will be 2 full Ubuntu LTS versions behind the then current one...

Because that's the requirement that I need to support.  All the work around the DEBs, the Mpack, Ansible setup was driven towards that.  

If you or anyone else wants to add support for a newer version that can also be done, but someone will have to put in the effort to do so.

**Comment by nickwallen** [comment]
I am liking a combination of the suggestions from @lvets and @cestella.  Something like this maybe?
* `dev-on-centos6`
* `dev-on-ubuntu14`

I like the name because of points made by others...
* The name identifies these as development environments
* Allows us to support multiple versions of the same platform; Ubuntu 16, CentOS 7, etc.

**Comment by nickwallen** [comment]
Ok, I renamed the development environments.  

I went with a slightly different name than I previously mentioned, but it still matches the suggestions that I received earlier.  I thought this made more sense.  Feel free to tell me if you don't like it.

Instead of `vagrant/full-dev-environment` or `vagrant/metron-on-centos` or `vagrant/dev-on-centos6`, we have `development/centos6` which is concise and very clear as to the intended purpose. 

* `metron-deployment/development/centos6`
* `metron-deployment/development/ubuntu14`
* `metron-deployment/development/fastcapa`

I also added `metron-deployment/ansible/README.md` to clarify the purpose and use of those shared Ansible assets.  I really do not want to see people trying to use those for anything outside of the development environments.

I edited `metron-deployment/development/README.md` to describe the various development environments.

Let me know if this jives for everyone; @ottobackwards, @cestella, @lvets, etc.

**Comment by lvets** [comment]
@nickwallen Fine for me :) This might be even better if you ever decide to make production ready pre-made ansible deployments (if that makes sense?)

**Comment by JonZeolla** [comment]
+1 to that latest round of naming

**Comment by ottobackwards** [comment]
+1 still stands

**Comment by cestella** [comment]
Looks good to me!

**Pull request closed without merging**
