### PR TITLE
Metron-846: Add E2E tests for metron management ui

### PR DESCRIPTION
**Pull request by iraghumitra**
## Contributor Comments
This PR adds e2e test support for management ui. We have few e2e tests in management ui but they do not work on quick-dev-platform. The PR makes significant changes to the existing e2e code so I would request to review the entire e2e tests in total.

- The e2e tests are written to run on quick-dev-platform
- Prerequisites for running e2e test are documented in metron-config README
- Steps to run the e2e tests are documented in metron-config README 
- Implemented promises wherever applicable in .po files

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron (Incubating).  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). 
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root incubating-metron folder via:
  ```
  mvn -q clean integration-test install && build_utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  bin/generate-md.sh
  mvn site:site
  ```

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommened that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by merrimanr** [comment]
I am not able to get this to run.  Here are the steps I followed:
- Deploy and start the REST app on node1:8082
- Run "npm install" in metron-config
- Start the UI with ./scripts/start_dev_quickdev.sh http://node1:8082 (verified UI works)
- Run the e2e tests with "npm run e2e-all"

This is the error I get:
`Using standard to parse output
Re-running tests: test attempt 3

Tests failed but no specs were found. All specs will be run again.

[09:33:53] I/direct - Using ChromeDriver directly...
[09:33:53] I/launcher - Running 1 instances of WebDriver
Spec started
[09:34:06] E/launcher - unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.11.6 x86_64)
[09:34:06] E/launcher - WebDriverError: unknown error: cannot get automation extension
from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
  (Session info: chrome=57.0.2987.133)
  (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.11.6 x86_64)
    at WebDriverError (/Users/rmerriman/Projects/Metron/code/forks/merrimanr/incubator-metron/metron-interface/metron-config/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/Users/rmerriman/Projects/Metron/code/forks/merrimanr/incubator-metron/metron-interface/metron-config/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/Users/rmerriman/Projects/Metron/code/forks/merrimanr/incubator-metron/metron-interface/metron-config/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/Users/rmerriman/Projects/Metron/code/forks/merrimanr/incubator-metron/metron-interface/metron-config/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/Users/rmerriman/Projects/Metron/code/forks/merrimanr/incubator-metron/metron-interface/metron-config/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/Users/rmerriman/Projects/Metron/code/forks/merrimanr/incubator-metron/metron-interface/metron-config/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/Users/rmerriman/Projects/Metron/code/forks/merrimanr/incubator-metron/metron-interface/metron-config/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/Users/rmerriman/Projects/Metron/code/forks/merrimanr/incubator-metron/metron-interface/metron-config/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /Users/rmerriman/Projects/Metron/code/forks/merrimanr/incubator-metron/metron-interface/metron-config/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.manage().window().setSize(2560, 1370)`

**Comment by merrimanr** [comment]
Also, the commit history looks strange in this PR.  Any idea why?  Did you start this branch from master?

**Comment by iraghumitra** [comment]
Looks like you are running into this [issue](http://www.kenst.com/2015/03/installing-chromedriver-on-mac-osx/). The only way as of now is either not using WebDriver.manage().window().setSize method or upgrading chrome web driver manually. I will check and update what could be the best way for us.

As for commit history, looks like git smartly picked commit history when I merged code my changes from 623 branch to master. I can resubmit the PR on a fresh branch if this looks awkward :)

**Comment by iraghumitra** [comment]
I removed usage of WebDriver.manage().window().setSize. It is a best practice to maximize the window before running the test cases probably we need to hold back on this practice till we upgrade to next version of angular-cli.

**Comment by merrimanr** [comment]
I am now able to get this to run and all tests passed.  Really great work so far.

I have a couple of requests.  First there are some very minor style issues.  Several lines are not terminated so that should be cleaned up.  

I feel like the organization of the "Sensor Config for parser e2e1" is too broad.  I would prefer tests to be broken down a little bit more, by feature or editor pane if possible.  For example, as a test I swapped the sort orders in threat triage editor.  The tests failed (yay!) but the test description reported in the failure was "Sensor Config for parser e2e1 should add e2e parser".  That is too vague and gives me no indication of where the error happened and what part of the code I need to inspect. 

I think there may also be some gaps in testing.  Is the raw JSON editor tested?  Advanced config?  Are we testing how we format field names and values in the read-only and list view?  When we're editing sensors are we verifying the correct config is saved?  Are we verifying the editor looks correct when we open an existing sensor (not just the primary form but child panes as well)?  Are we testing the general settings page?

Another concern I have is that we're expecting a static list of sensors.  These tests will break if a sensor is ever added to Metron and it won't be obvious because these tests are not part of the build workflow.  Is it possible/reasonable to add some kind of setup script to create the test cases so that they will not be affected by new parsers being added?

Still more work to do but this is a solid start.

**Comment by ottobackwards** [comment]
What is the status of this PR?

**Comment by iraghumitra** [comment]
Yeah got busy with other stuff I will jump on to this ASAIC

**Comment by iraghumitra** [comment]
@merrimanr Here is the list of consolidated suggestion on this PR. I worked on the comments that are related to code guidelines and readability of the code. As for improving coverage, i can submit a separate PR ?.


- First, there are some very minor style issues. Several lines are not terminated so that should be cleaned up. _-Done_
-  I feel like the organization of the "Sensor Config for parser e2e1" is too broad. I would prefer tests to be broken down a little bit more, by feature or editor pane if possible.  _-Done_
-  Is the raw JSON editor tested? _-Will cover in a separate PR_
- Advanced config?  _-The advanced config is asserted in edit flow. We can a case to test in add flow too_
- Are we testing how we format field names and values in the read-only and list view?  _-This is indirectly tested when we try to get the field value by css class names_
- When we're editing sensors are we verifying the correct config is saved?  _-Yes_
- Are we verifying the editor looks correct when we open an existing sensor (not just the primary form but child panes as well)? _-This is indirectly tested when we try to get the field value by css class names_
- Are we testing the general settings page? _-Will cover in separate PR_
- setup script to create the test cases so that they will not be affected by new parsers being added?  _-Will cover in seperate PR_

**Comment by ottobackwards** [comment]
What is the status of this?

**Comment by ottobackwards** [comment]
What is the status of this pr?  Can it be closed?  I has no updates since August and it is conflicted.

**Comment by ottobackwards** [comment]
@iraghumitra What is up with this?  Can you close it if you are not going to de-conflict?

**Comment by ottobackwards** [comment]
@iraghumitra what is the story with this?

**Comment by iraghumitra** [comment]
@ottobackwards I got busy with few commitments. i am discussing this with @anandsubbu to take this forward.

**Comment by anandsubbu** [comment]
I am testing and updating this PR to get it to work on latest master.

**Comment by ottobackwards** [comment]
please close this

**Comment by nickwallen** [comment]
I opened a ticket to get this closed; https://issues.apache.org/jira/browse/INFRA-17251

**Pull request closed without merging**
