### PR TITLE
METRON-2205: Introducing staleDataState on Alerts UI

### PR DESCRIPTION
**Pull request by tiborm**
## Contributor Comments

Currently, Alerts UI sends a query request to the REST API every time the user 
- add new filter
- clear filters
- change time range

This behavior keeps the list of alerts and the state of the filtering in sync: every time the filter changes the visualized data change with it.

The drawback of this behavior is it fires multiple query requests while the user tries to set up a more complex filter.

The following scenario:
1. clearing the current filter
2. changing the time range
3. adding a filter for ip_src_addr
4. adding a filter for source:type
5. pressing the query button

leads 5 queries instead of one. In the case of large data sets, this could lead to unnecessary load and UI glitches (results update the alerts table with partially filtered data).

To fix this I ceased automatic querying on time-range or filter change and introduced staled data state. This means when the user making any changes in filtering compared to the previous result UI shows the following warning:

Screenshot from 2019-08-07 15-52-22

## Testing
Check out this branch and fire up the Alerts UI with the following script:
/metron-interface/metron-alerts/scripts/start-dev.sh
PR contains no backend changes so no rebuild of the full dev VM needed to test.

## Pull Request Checklist

Thank you for submitting a contribution to Apache Metron.  
Please refer to our [Development Guidelines](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=61332235) for the complete guide to follow for contributions.  
Please refer also to our [Build Verification Guidelines](https://cwiki.apache.org/confluence/display/METRON/Verifying+Builds?show-miniview) for complete smoke testing guides.  

In order to streamline the review of the contribution we ask you follow these guidelines and ask you to double check the following:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? If not one needs to be created at [Metron Jira](https://issues.apache.org/jira/browse/METRON/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel).
- [x] Does your PR title start with METRON-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.
- [x] Has your PR been rebased against the latest commit within the target branch (typically master)?

### For code changes:
- [x] Have you included steps to reproduce the behavior or problem that is being changed or addressed?
- [x] Have you included steps or a guide to how the change may be verified and tested manually?
- [x] Have you ensured that the full suite of tests and checks have been executed in the root metron folder via:
  ```
  mvn -q clean integration-test install && dev-utilities/build-utils/verify_licenses.sh 
  ```

- [x] Have you written or updated unit tests and or integration tests to verify your changes?
- [x] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [x] Have you verified the basic functionality of the build by building and running locally with Vagrant full-dev environment or the equivalent?

### For documentation related changes:
- [x] Have you ensured that format looks appropriate for the output in which it is rendered by building and verifying the site-book? If not then run the following commands and the verify changes via `site-book/target/site/index.html`:

  ```
  cd site-book
  mvn site
  ```

- [x] Have you ensured that any documentation diagrams have been updated, along with their source files, using [draw.io](https://www.draw.io/)? See [Metron Development Guidelines](https://cwiki.apache.org/confluence/display/METRON/Development+Guidelines) for instructions.

#### Note:
Please ensure that once the PR is submitted, you check travis-ci for build issues and submit an update to your PR as soon as possible.
It is also recommended that [travis-ci](https://travis-ci.org) is set up for your personal repository such that your branches are built there before submitting a pull request.

### CODE REVIEW

**Comment by sardell** [comment]
+1. I think the behavior @tiborm implemented here is much better than sending off a request every time we add a new condition to the query, especially if those queries can be expensive to perform on the backend.

**Comment by mmiklavc** [comment]
> leads 5 queries instead of one. In the case of large data sets, this could lead to unnecessary load and UI glitches (results update the alerts table with partially filtered data).

Wow. Agreed, DDOS-ing our indexing layer is very much undesirable.

+1 pending @tiborm confirms checking off the items in the checklist. Thanks for the contribution.

**Comment by tiborm** [comment]
Closing PR temporarily bc I found out this change has an unexpected impact on timer-based polling. Fix is on the way!

**Comment by tiborm** [comment]
I investigated the behavior seemed suspicious first and I think it's ok to go with it.
Short desc:
If Alerts UI in a stale data state and queries triggered by the turned-on auto polling also reflect this stale state. But, hence the warning is there I don't think is an issue.

**Comment by sardell** [comment]
@tiborm Yeah, I also think the current behavior for time-based polling as implemented in your PR is fine. User inputs a query, turns on polling, user updates input and a warning shows that their data is in a stale state. By turning off and turning back on polling (or by clicking the search icon again), the query is refreshed and the message disappears.

I'm sure we can think of better ways of handling this in the future as part of a bigger effort to refactor/rebuild the query builder, but I think this is a big improvement for now.

**Pull request closed without merging**
